#!/usr/bin/env python3
"""Write a cohort's durable reference package — CSV always, XLSX when openpyxl imports.

    tools/export_resident_research_package.py T-0442 --build
    tools/export_resident_research_package.py T-0442 --check
    tools/export_resident_research_package.py --check-all       (the gate)

`chicago/reference/resident-research/README.md` is the contract: one folder per
cohort ticket, a machine-readable CSV, a human-reviewable workbook, and four
sheets — Residents, Candidates, Sources, Search_Log. T-0478 to T-0486 each wrote
theirs by hand, in nine slightly different shapes; the pilot, pass 2 and pass 3
(T-0442, T-0462, T-0463 — the first 225 people the owner is counting) wrote none
at all. This is the writer those three get, and the shape any later cohort can use.

EVERYTHING HERE IS A VIEW. Nothing is decided in this file: every cell is copied
from `data/research/residents/<cohort>.json` (who was in the cohort and what
evidence they started from), `data/residents/research_pilot.json` (the reviewed
outcome, its summary, its queries, its sources and its candidates) and
`data/sources/*.json` (what each cited source is). A column those files do not
carry is left EMPTY — filling it by inference would be inventing research, which
is the one thing a research receipt may not do.

WHAT THESE PACKAGES DO NOT SAY. A reviewed outcome is not a promotion. None of
these 225 people carries a `resident_research` block on their household record —
that is the finding behind T-0508 to T-0510, measured in
`tools/select_resident_research_pass_13.py`, and the package makes it legible
rather than resolving it.
"""
from __future__ import annotations

import argparse
import csv
import io
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESEARCH = ROOT / "data" / "research" / "residents"
REVIEWS = ROOT / "data" / "residents" / "research_pilot.json"
SOURCES = ROOT / "data" / "sources"
REFERENCE = ROOT.parent / "reference" / "resident-research"
TEMPLATE = REFERENCE / "cohort_research_template.csv"

# The cohorts this tool writes. A ticket joins the table when its manifest and its
# reviews are both committed; T-0478..T-0486 predate the tool and are checked for
# PRESENCE only (--check-all), because rewriting nine hand-built packages would
# rewrite nine research receipts and none of them is wrong.
EXPORTED = {
    "T-0442": {"cohort": "pilot_75", "manifest": "pilot_75_cohort.json",
               "findings": None, "label": "the pilot cohort"},
    "T-0462": {"cohort": "pass_02_75", "manifest": "pass_02_75_cohort.json",
               "findings": "pass_02_findings.json", "label": "the second cohort"},
    "T-0463": {"cohort": "pass_03_75", "manifest": "pass_03_75_cohort.json",
               "findings": "pass_03_findings.json", "label": "the third cohort"},
}

# Every cohort ticket that has closed. T-0508, T-0509 and T-0510 (passes 13-15)
# join this list when they close; the presence gate is what makes forgetting the
# package a red gate rather than a discovery two months later.
COMPLETED_COHORTS = [
    ("T-0442", "pilot", "pilot_75_cohort.json", None),
    ("T-0462", "pass 2", "pass_02_75_cohort.json", "pass_02_findings.json"),
    ("T-0463", "pass 3", "pass_03_75_cohort.json", "pass_03_findings.json"),
    ("T-0478", "pass 4", "pass_04_75_cohort.json", "pass_04_findings.json"),
    ("T-0479", "pass 5", "pass_05_75_cohort.json", "pass_05_findings.json"),
    ("T-0480", "pass 6", "pass_06_75_cohort.json", "pass_06_findings.json"),
    ("T-0481", "pass 7", "pass_07_75_cohort.json", "pass_07_findings.json"),
    ("T-0482", "pass 8", "pass_08_75_cohort.json", "pass_08_findings.json"),
    ("T-0483", "pass 9", "pass_09_75_cohort.json", "pass_09_findings.json"),
    ("T-0484", "pass 10", "pass_10_75_cohort.json", "pass_10_findings.json"),
    ("T-0485", "pass 11", "pass_11_75_cohort.json", "pass_11_findings.json"),
    ("T-0486", "pass 12", "pass_12_11_cohort.json", "pass_12_findings.json"),
]

INDEX_BEGIN = "<!-- package-index: generated by chicago/4d/tools/export_resident_research_package.py --index -->"
INDEX_END = "<!-- /package-index -->"

OUTCOME = {"corroborated_enrichment": "corroborated",
           "candidate_identity": "candidate",
           "no_corroboration": "no_corroboration"}

# Mechanical, and stated so it can be argued with: the recommendation restates the
# project's own identity rule for the outcome, and adds nothing to it.
ACTION = {
    "corroborated": "promote per attribute, carrying the source and its tier",
    "candidate": "retain as an unasserted candidate; do not promote on name alone",
    "no_corroboration": "no data action; a documented negative search, not an absence",
}

CANDIDATE_HEADER = ["ticket", "person_id", "person_name", "candidate_id",
                    "candidate_name", "assessment", "asserted", "basis",
                    "conflicts", "source_ids"]
SOURCE_HEADER = ["ticket", "source_id", "cited_by_people", "type", "citation",
                 "date", "describes_date", "tier", "rights_status", "url",
                 "locator", "limitations"]
SEARCH_LOG_HEADER = ["ticket", "person_id", "person_name", "query", "date_searched",
                     "result", "result_summary", "sources_returned"]
SUMMARY_HEADER = ["ticket", "cohort", "scene_date", "reviewed_on", "metric", "value"]


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def joined(values) -> str:
    return "; ".join(str(v) for v in values if str(v))


def stratum_of(member: dict) -> str:
    """The population frame's own stratum name, re-derived per person.

    The first three manifests carry `starting_evidence` and `starting_presence`
    but not the stratum label their frame counts by, so it is rebuilt here and
    checked against the frame's counts in build().
    """
    if member["starting_evidence"] == "letter_list_only":
        present = member["starting_presence"] == "present"
        return "letter_list_only_present" if present else "letter_list_only_uncertain"
    return member["starting_evidence"]


def source_record(source_id: str) -> dict:
    path = SOURCES / (source_id + ".json")
    return load(path) if path.exists() else {}


def candidate_id(person_id: str, n: int) -> str:
    return "%s-c%d" % (person_id, n)


def rows_for(ticket: str):
    """Return (residents, candidates, sources, search_log, summary) row lists."""
    spec = EXPORTED[ticket]
    manifest = load(RESEARCH / spec["manifest"])
    reviewed = {r["person_id"]: r for r in load(REVIEWS)["reviews"]}
    header = TEMPLATE.read_text(encoding="utf-8").splitlines()[0].split(",")

    residents, candidates, search_log = [], [], []
    cited: dict[str, int] = {}
    counts = {"corroborated": 0, "candidate": 0, "no_corroboration": 0}
    strata: dict[str, int] = {}

    for member in manifest["people"]:
        pid = member["person_id"]
        if pid not in reviewed:
            raise SystemExit("%s: %s is in the manifest and has no review" % (ticket, pid))
        review = reviewed[pid]
        outcome = OUTCOME[review["outcome"]]
        counts[outcome] += 1
        stratum = stratum_of(member)
        strata[stratum] = strata.get(stratum, 0) + 1

        cand_ids = []
        for n, cand in enumerate(review["candidates"], start=1):
            cid = candidate_id(pid, n)
            cand_ids.append(cid)
            candidates.append({
                "ticket": ticket, "person_id": pid,
                "person_name": review["name_as_recorded"], "candidate_id": cid,
                "candidate_name": cand.get("name", ""),
                "assessment": cand.get("assessment", ""),
                "asserted": "yes" if cand.get("asserted") else "no",
                "basis": cand.get("basis", ""),
                "conflicts": joined(cand.get("conflicts", [])),
                "source_ids": joined(cand.get("sources", [])),
            })
            for sid in cand.get("sources", []):
                cited[sid] = cited.get(sid, 0) + 1

        for sid in review["sources"]:
            cited[sid] = cited.get(sid, 0) + 1

        against = joined(c for cand in review["candidates"]
                         for c in cand.get("conflicts", []))
        recs = [source_record(s) for s in review["sources"]]

        row = {k: "" for k in header}
        row.update({
            "ticket": ticket,
            "cohort": spec["cohort"],
            "person_id": pid,
            "household_id": member["household_id"],
            "name_transcribed": member["name"],
            "name_normalized": review["name_as_recorded"],
            "stratum": stratum,
            "seed_source_id": joined(member["sources"]),
            "letter_list_dates": joined(member["letter_list_returns"]),
            "research_outcome": outcome,
            "identity_confidence": "high" if outcome == "corroborated" else "unresolved",
            "candidate_ids": joined(cand_ids),
            "evidence_for": review["summary"],
            "evidence_against": against,
            "source_ids": joined(review["sources"]),
            "source_urls_locators": joined(r.get("url", "") for r in recs),
            "source_tiers": joined(r.get("tier", "") for r in recs),
            "queries": joined(review["queries"]),
            "access_dates": review["reviewed_on"],
            "recommended_data_action": ACTION[outcome],
            "notes": "starting evidence %s, presence %s, grade %s, occupation %s. %s" % (
                member["starting_evidence"], member["starting_presence"],
                member["starting_grade"], member["starting_occupation"],
                member["selection_reason"]),
        })
        residents.append(row)

        for query in review["queries"]:
            search_log.append({
                "ticket": ticket, "person_id": pid,
                "person_name": review["name_as_recorded"], "query": query,
                "date_searched": review["reviewed_on"],
                "result": "found" if outcome != "no_corroboration" else "no result",
                "result_summary": review["summary"],
                "sources_returned": joined(review["sources"]),
            })

    frame = manifest["population_frame"]["strata"]
    if strata != frame:
        raise SystemExit("%s: re-derived strata %s do not match the frame's %s"
                         % (ticket, strata, frame))

    sources = []
    for sid in sorted(cited):
        rec = source_record(sid)
        sources.append({
            "ticket": ticket, "source_id": sid, "cited_by_people": cited[sid],
            "type": rec.get("type", ""), "citation": rec.get("citation", ""),
            "date": rec.get("date", ""), "describes_date": rec.get("describes_date", ""),
            "tier": rec.get("tier", ""), "rights_status": rec.get("rights_status", ""),
            "url": rec.get("url", ""), "locator": rec.get("locator", ""),
            "limitations": rec.get("note", "") if rec else
                           "no record under data/sources/ — cited by id only",
        })

    reviewed_on = (load(RESEARCH / spec["findings"])["reviewed_on"]
                   if spec["findings"] else
                   sorted({r["access_dates"] for r in residents})[-1])
    summary = [
        {"metric": "cohort size", "value": len(residents)},
        {"metric": "corroborated", "value": counts["corroborated"]},
        {"metric": "candidate", "value": counts["candidate"]},
        {"metric": "no_corroboration", "value": counts["no_corroboration"]},
        {"metric": "pending", "value": 0},
        {"metric": "candidate rows", "value": len(candidates)},
        {"metric": "sources cited", "value": len(sources)},
        {"metric": "search-log rows", "value": len(search_log)},
    ]
    for s in strata.items():
        summary.append({"metric": "stratum " + s[0], "value": s[1]})
    for r in summary:
        r.update({"ticket": ticket, "cohort": spec["cohort"],
                  "scene_date": manifest["scene_date"], "reviewed_on": reviewed_on})

    return residents, candidates, sources, search_log, summary, header


def to_csv(header: list[str], rows: list[dict]) -> str:
    buf = io.StringIO(newline="")
    writer = csv.DictWriter(buf, fieldnames=header, lineterminator="\n")
    writer.writeheader()
    for row in rows:
        writer.writerow(row)
    return buf.getvalue()


def files_for(ticket: str) -> dict[str, str]:
    residents, candidates, sources, search_log, summary, header = rows_for(ticket)
    return {
        "%s_resident_research.csv" % ticket: to_csv(header, residents),
        "%s_candidates.csv" % ticket: to_csv(CANDIDATE_HEADER, candidates),
        "%s_sources.csv" % ticket: to_csv(SOURCE_HEADER, sources),
        "%s_search_log.csv" % ticket: to_csv(SEARCH_LOG_HEADER, search_log),
        "%s_summary.csv" % ticket: to_csv(SUMMARY_HEADER, summary),
    }


def write_workbook(ticket: str, out: Path) -> bool:
    try:
        from openpyxl import Workbook
    except ImportError:
        return False
    residents, candidates, sources, search_log, summary, header = rows_for(ticket)
    book = Workbook()
    book.remove(book.active)
    sheets = [("Residents", header, residents), ("Candidates", CANDIDATE_HEADER, candidates),
              ("Sources", SOURCE_HEADER, sources), ("Search_Log", SEARCH_LOG_HEADER, search_log),
              ("Summary", SUMMARY_HEADER, summary)]
    for name, cols, rows in sheets:
        sheet = book.create_sheet(name)
        sheet.append(cols)
        for row in rows:
            sheet.append([row.get(c, "") for c in cols])
        sheet.freeze_panes = "A2"
    book.save(out / ("%s_resident_research_working.xlsx" % ticket))
    return True


def build(ticket: str) -> None:
    out = REFERENCE / ticket
    out.mkdir(parents=True, exist_ok=True)
    for name, text in files_for(ticket).items():
        (out / name).write_text(text, encoding="utf-8")
    made = write_workbook(ticket, out)
    print("%s: %d CSV files%s -> %s" % (
        ticket, len(files_for(ticket)),
        " and the workbook" if made else " (no openpyxl; workbook not written)",
        out.relative_to(ROOT.parent.parent)))


def check(ticket: str) -> int:
    out = REFERENCE / ticket
    bad = 0
    for name, text in files_for(ticket).items():
        path = out / name
        if not path.exists():
            print("  MISSING %s/%s" % (ticket, name))
            bad += 1
        elif path.read_text(encoding="utf-8") != text:
            print("  STALE   %s/%s — rebuild with --build" % (ticket, name))
            bad += 1
    for name in ("README.md", "%s_resident_research_working.xlsx" % ticket):
        if not (out / name).exists():
            print("  MISSING %s/%s" % (ticket, name))
            bad += 1
    return bad


def check_all() -> int:
    bad = 0
    bad += check_index()
    for ticket, _label, _manifest, _findings in COMPLETED_COHORTS:
        out = REFERENCE / ticket
        if not out.is_dir():
            print("  MISSING package folder for completed cohort %s" % ticket)
            bad += 1
            continue
        if not (out / "README.md").exists():
            print("  MISSING %s/README.md" % ticket)
            bad += 1
        if not (out / ("%s_resident_research.csv" % ticket)).exists():
            print("  MISSING %s/%s_resident_research.csv" % (ticket, ticket))
            bad += 1
    for ticket in EXPORTED:
        bad += check(ticket)
    if bad:
        print("%d package problem(s); tools/export_resident_research_package.py --build "
              "<ticket> rewrites the generated ones" % bad)
    return bad


def index_table() -> str:
    """The index the README carries: every cohort package, its counts, its date.

    Counts are RE-DERIVED from each cohort's manifest and findings ledger — a
    member with no override took the pass's documented default, which is a
    no-corroboration — so the table cannot drift away from the research behind it.
    The nine hand-built packages are indexed here even though this tool does not
    write them.
    """
    lines = [INDEX_BEGIN, "",
             "| package | pass | people | corroborated | candidate | no corroboration | researched | written by |",
             "|---|---|---:|---:|---:|---:|---|---|"]
    totals = [0, 0, 0, 0]
    for ticket, label, manifest, findings in COMPLETED_COHORTS:
        cohort = load(RESEARCH / manifest)
        overrides = load(RESEARCH / findings)["overrides"] if findings else {}
        reviewed = {r["person_id"]: r for r in load(REVIEWS)["reviews"]}
        counts = {"corroborated_enrichment": 0, "candidate_identity": 0,
                  "no_corroboration": 0}
        dates = set()
        for member in cohort["people"]:
            pid = member["person_id"]
            if findings:
                counts[overrides.get(pid, {}).get("outcome", "no_corroboration")] += 1
            else:
                counts[reviewed[pid]["outcome"]] += 1
            if pid in reviewed:
                dates.add(reviewed[pid]["reviewed_on"])
        when = (load(RESEARCH / findings)["reviewed_on"] if findings
                else sorted(dates)[-1])
        n = len(cohort["people"])
        totals = [totals[0] + n, totals[1] + counts["corroborated_enrichment"],
                  totals[2] + counts["candidate_identity"],
                  totals[3] + counts["no_corroboration"]]
        lines.append("| [`%s/`](%s/) | %s | %d | %d | %d | %d | %s | %s |" % (
            ticket, ticket, label, n, counts["corroborated_enrichment"],
            counts["candidate_identity"], counts["no_corroboration"], when,
            "T-0511" if ticket in EXPORTED else "the cohort ticket"))
    lines.append("| **total** | 12 cohorts | **%d** | **%d** | **%d** | **%d** | | |"
                 % tuple(totals))
    lines += ["",
              "[`T-0493/`](T-0493/) is the thirteenth package and not a cohort: the 345 "
              "entries of the four voter lists, written by `chicago/4d/tools/"
              "pack_t0493_reference.py`.",
              "",
              "Passes 13, 14 and 15 (T-0508, T-0509, T-0510) are open; each joins this "
              "table when its ticket closes.",
              "", INDEX_END]
    return "\n".join(lines)


def write_index() -> None:
    readme = REFERENCE / "README.md"
    text = readme.read_text(encoding="utf-8")
    if INDEX_BEGIN not in text:
        raise SystemExit("README.md has no %s marker" % INDEX_BEGIN)
    head, rest = text.split(INDEX_BEGIN, 1)
    _, tail = rest.split(INDEX_END, 1)
    readme.write_text(head + index_table() + tail, encoding="utf-8")
    print("index table rewritten in reference/resident-research/README.md")


def check_index() -> int:
    text = (REFERENCE / "README.md").read_text(encoding="utf-8")
    if INDEX_BEGIN not in text or INDEX_END not in text:
        print("  MISSING the package-index markers in README.md")
        return 1
    have = INDEX_BEGIN + text.split(INDEX_BEGIN, 1)[1].split(INDEX_END, 1)[0] + INDEX_END
    if have != index_table():
        print("  STALE   README.md package index — rebuild with --index")
        return 1
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("ticket", nargs="?", choices=sorted(EXPORTED))
    ap.add_argument("--build", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--check-all", action="store_true")
    ap.add_argument("--index", action="store_true")
    args = ap.parse_args()

    if args.index:
        write_index()
        return 0
    if args.check_all:
        return 1 if check_all() else 0
    if not args.ticket:
        ap.error("a ticket is required unless --check-all")
    if args.build:
        build(args.ticket)
        return 0
    if args.check:
        bad = check(args.ticket)
        if bad:
            return 1
        print("%s package matches its JSON" % args.ticket)
        return 0
    ap.error("choose --build or --check")


if __name__ == "__main__":
    sys.exit(main())
