#!/usr/bin/env python3
"""Reconcile the 665-roof programme against the town that has actually been built.

ROADMAP T-A1. `data/reconstruction/1835_building_inventory.json` states the target — 665
roofs, split by district, by group and by a 35-family schedule — and it has never been
subtracted from. The crosswalk still calls 617 roofs "remaining", a figure that predates
the North parcel, the West parcel, the inferred-household buildings and every documented
roof the research has since placed. A programme whose remainder is wrong by 185 roofs
cannot schedule the next block, which is why this runs before the block parcels do.

Everything here is DERIVED. The inputs are the structure records themselves, the
physical-roof reconciliation of the pre-existing ones, the inferred-household programme
and the platted grid; the output is `data/reconstruction/1835_665_roof_programme.json`,
regenerated by this tool and re-derived by `tools/check.sh`. Nothing in it is a number
somebody typed, which is the only way a ledger stays true to a dataset that grows nightly.

What each part of the output is entitled to claim:

* **What stands** is a count of committed records, not an estimate. A pre-existing record
  contributes the physical roofs the reconciliation credits it — 0 for a bridge, a pier, a
  parade ground or a building whose July existence the chronology contradicts; a generated
  or inferred-household record contributes one.
* **What remains** is arithmetic on the authored target and nothing else. Where evidence
  has already put MORE roofs into a family than the target allows, the excess is reported
  and the remainder comes out of the invented families with the most slack: a documented
  building is never removed to protect a family cap.
* **Where it can go** is the honest part and the uncomfortable one. A block can be named
  only where the plat module reaches it, which today is 19 blocks holding 152 lots. The
  schedule names every one of them with its own headroom, names the two blocks the module
  refuses for want of street control, carries the West recipe's own extension-gated
  figure, and puts the balance into one unit per district that says what it waits on
  rather than inventing a block number this project has never read off a sheet.
* **A per-unit family mix** is an apportionment of that district's remainder, not a claim
  about any block. It is what makes the schedule addable: every unit's families sum to its
  count, every district's units sum to its remainder, and the districts sum to 665.

    tools/reconcile_665.py            regenerate the programme file
    tools/reconcile_665.py --check    fail if the committed file is not what the dataset
                                      and the target re-derive
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
RECON = DATA / "reconstruction"
OUT_PATH = RECON / "1835_665_roof_programme.json"

# Groups are the inventory's own ten, and a family belongs to its group by its letter.
# The letters are checked against the target itself: each group's families must sum to
# that group's total, or the mapping below has drifted from the document it reads.
GROUP_OF_LETTER = {
    "D": "ordinary_dwellings",
    "H": "larger_boarding_houses",
    "C": "stores_mixed_use",
    "T": "inns_taverns",
    "W": "workshops",
    "F": "warehouses_freight",
    "I": "institutional_public",
    "M": "fort_principal",
}
ANCILLARY_GROUPS = {"barns_stables", "small_outbuildings"}

DISTRICTS = ["south", "west", "north", "fort"]

# One principal roof per platted lot, and ancillary at the programme's own ratio. Both
# halves come from the dataset rather than from tuning: the reviewed phase-1 parcel put 40
# principal roofs into five blocks of eight lots — exactly one per lot — and the
# inventory's targets are 511 principal to 154 ancillary. A denser core would be a
# decision about lot subdivision, and four lots to a face is a reading of ONE block that
# the grid itself grades `conjectural`, so that decision is not taken here.
ANCILLARY_PER_PRINCIPAL = 154 / 511

# The two blocks the plat module refuses for want of street control, as against the three
# it refuses because what lies between the streets is the river. Named here so that a
# block which starts being emitted stops being scheduled as gated.
STREET_CONTROL_OMISSIONS = {"blk_south_water_market", "blk_south_water_clinton"}

# The West recipe's own instantiation block: "do not emit structure records or meshes for
# any placement with centre E < -300 m until the heightfield, collision surface,
# vegetation sampler, minimap and water mask share the extended box." Read as a number
# here only to cross-check the recipe's remainder against the records actually emitted.
WEST_INSTANTIATION_BLOCK_E = -300.0

# What the balance of each district is waiting on. The South and West entries are the
# street control ROADMAP S9 records as owed; the North entry is the coverage the North
# parcel's own recipe names. No block can be named inside any of them, which is the point.
BALANCE_UNITS = {
    "south": (
        "south_plat_beyond_committed_control",
        "Committed street control reaches State Street on the east and Washington Street "
        "on the south; the plat continues past both. No block east of State or south of "
        "Washington has four committed centrelines, so none can be named, let alone "
        "measured (ROADMAP S9).",
    ),
    "west": (
        "west_division_beyond_committed_control",
        "West Division ground beyond the Wolf Point approaches: no committed street "
        "control west of Clinton and Canal, and no unified terrain, hydrology or map "
        "coverage past the recipe's own gate at local E -700 m.",
    ),
    "north": (
        "north_division_beyond_modelled_ground",
        "North Division ground beyond the initial parcel: the plat grid covers no North "
        "Division block at all — that street control is what ROADMAP S9 records as owed — "
        "and terrain, hydrology, flora and map coverage stop short of local N +760 m.",
    ),
    "fort": (
        "fort_dearborn_compound",
        "The compound's ten principal roofs are placed; the stockade, parade and props "
        "are outside the roof count by the inventory's own definition.",
    ),
}


def load(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def group_of(family: str) -> str:
    if family.startswith("A"):
        return "barns_stables" if family in ("A1", "A2") else "small_outbuildings"
    return GROUP_OF_LETTER[family[0]]


def apportion(total: int, weights: list[float]) -> list[int]:
    """Hamilton's method — proportional, integer, sums exactly, ties broken by position."""
    if total <= 0 or not weights:
        return [0] * len(weights)
    mass = sum(weights)
    if mass <= 0:
        out = [0] * len(weights)
        out[0] = total
        return out
    exact = [total * w / mass for w in weights]
    out = [int(x) for x in exact]
    order = sorted(range(len(weights)), key=lambda i: (-(exact[i] - out[i]), i))
    for i in order[: total - sum(out)]:
        out[i] += 1
    return out


def deal(counts: dict[str, int]) -> list[str]:
    """A deterministic mixed deal: each family's tokens are spread evenly over the whole
    run, so dealing the run to units in order gives every unit the district's mix rather
    than one family per block."""
    total = sum(counts.values())
    tokens = []
    for family, n in sorted(counts.items()):
        for i in range(n):
            tokens.append((((i + 0.5) * total) / n, family))
    tokens.sort(key=lambda t: (t[0], t[1]))
    return [family for _, family in tokens]


def inside(point, polygon) -> bool:
    x, y = point
    hit = False
    j = len(polygon) - 1
    for i in range(len(polygon)):
        xi, yi = polygon[i]
        xj, yj = polygon[j]
        if (yi > y) != (yj > y) and x < (xj - xi) * (y - yi) / (yj - yi) + xi:
            hit = not hit
        j = i
    return hit


def standing_roofs(grid, datum):
    """Every committed structure record, with the physical roofs it puts in the scene and
    the platted block it stands in, where the grid reaches it."""
    reconciliation = {
        r["structure_id"]: r
        for r in load(RECON / "1835_existing_roof_reconciliation.json")["records"]
    }
    households = {
        b["id"]: b
        for b in load(RECON / "1835_inferred_household_programme.json")["buildings"]
    }
    rows = []
    for path in sorted((DATA / "structures").glob("*.json")):
        record = load(path)
        rid = record["id"]
        if "reconstruction" in record:
            block = record["reconstruction"]
            row = {"id": rid, "source": "generated", "district": block["district"],
                   "family": block["family"], "roofs_min": 1, "roofs_max": 1,
                   "programme_phase": block.get("programme_phase")}
        elif rid in reconciliation:
            entry = reconciliation[rid]
            count = entry["inventory_roof_count"] if entry["inventory_eligible"] else 0
            row = {"id": rid, "source": "pre_existing", "district": entry["district"],
                   "family": entry.get("likely_family"),
                   "roofs_min": count["min"] if isinstance(count, dict) else count,
                   "roofs_max": count["max"] if isinstance(count, dict) else count}
        elif rid in households:
            entry = households[rid]
            row = {"id": rid, "source": "inferred_household_programme",
                   "district": entry["district"], "family": entry["family"],
                   "roofs_min": 1, "roofs_max": 1}
        else:
            raise SystemExit(
                f"{rid} belongs to no programme this ledger can read. A structure record "
                "must carry a reconstruction block, or be an entry in the physical-roof "
                "reconciliation, or be a building of the inferred-household programme — "
                "otherwise it stands in the scene and not in the count."
            )
        if row["family"] is None and row["roofs_min"]:
            raise SystemExit(f"{rid} contributes a roof with no family to count it under")
        position = next((p["position"] for p in record["phases"]
                         if p.get("position") and p["position"].get("utm_e") is not None), None)
        row["block"] = None
        if position:
            point = (position["utm_e"] - datum["origin_utm_e"],
                     position["utm_n"] - datum["origin_utm_n"])
            for block in grid["blocks"]:
                if inside(point, block["boundary_local_enu_m"]):
                    row["block"] = block["id"]
                    break
        rows.append(row)
    return rows


def district_of_block(block) -> str:
    """A block is West Division ground when it lies west of the South Branch, which at
    this datum is local easting 0 — the origin IS the forks. No block in the grid
    straddles a division line."""
    return "west" if max(p[0] for p in block["boundary_local_enu_m"]) < 0 else "south"


def programme_document():
    inventory = load(RECON / "1835_building_inventory.json")
    grid = load(DATA / "traces" / "vectors" / "thompson_lots.json")
    datum = load(DATA / "datum.json")
    west_recipe = load(RECON / "1835_phase2_west_wolf_point_approaches.json")
    targets = inventory["family_targets"]
    matrix = inventory["district_group_matrix"]

    for group, row in matrix.items():
        families = sum(t for f, t in targets.items() if group_of(f) == group)
        if families != row["total"]:
            raise SystemExit(f"family targets for {group} sum to {families}, "
                             f"not the group's own total of {row['total']}")

    rows = standing_roofs(grid, datum)

    # ---- what stands ------------------------------------------------------------
    built_family: dict[str, int] = {}
    built_district: dict[str, int] = {}
    built_source: dict[str, int] = {}
    built_district_group: dict[tuple[str, str], int] = {}
    built_block: dict[str, int] = {}
    for row in rows:
        n = row["roofs_min"]
        built_source[row["source"]] = built_source.get(row["source"], 0) + n
        if not n:
            continue
        built_family[row["family"]] = built_family.get(row["family"], 0) + n
        built_district[row["district"]] = built_district.get(row["district"], 0) + n
        key = (row["district"], group_of(row["family"]))
        built_district_group[key] = built_district_group.get(key, 0) + n
        if row["block"]:
            built_block[row["block"]] = built_block.get(row["block"], 0) + n
            # A record standing in a block of another division is a defect in one of the
            # two, and it would put a roof on one district's ledger and take the headroom
            # off another's. Nothing in the dataset does this today.
            block = next(b for b in grid["blocks"] if b["id"] == row["block"])
            if district_of_block(block) != row["district"]:
                raise SystemExit(
                    f"{row['id']} is a {row['district']} record standing inside "
                    f"{row['block']}, which is {district_of_block(block)} Division ground")
    standing_min = sum(r["roofs_min"] for r in rows)
    standing_max = sum(r["roofs_max"] for r in rows)

    # ---- what remains -----------------------------------------------------------
    roof_total = inventory["targets"]["roof_total"]
    remaining_total = roof_total - standing_min
    overrun = {f: built_family.get(f, 0) - t
               for f, t in sorted(targets.items()) if built_family.get(f, 0) > t}
    remaining_family = {f: max(0, t - built_family.get(f, 0)) for f, t in targets.items()}
    # The excess has to come out of somewhere, because 665 is the target and a documented
    # roof is not removable. It comes out one slot at a time, each from whichever invented
    # family has the most slack at that moment.
    absorbed: dict[str, int] = {}
    for _ in range(sum(overrun.values())):
        family = sorted(remaining_family, key=lambda f: (-remaining_family[f], f))[0]
        remaining_family[family] -= 1
        absorbed[family] = absorbed.get(family, 0) + 1
    if sum(remaining_family.values()) != remaining_total:
        raise SystemExit("family remainders do not sum to the programme remainder")

    remaining_district = {d: inventory["districts"][d]["target"] - built_district.get(d, 0)
                          for d in DISTRICTS}
    if sum(remaining_district.values()) != remaining_total:
        raise SystemExit("district remainders do not sum to the programme remainder")

    # A district's own mix: its group targets less what stands in it, apportioned across
    # that group's families in proportion to the global family remainder, with the same
    # absorption rule inside the district and for the same reason.
    district_families: dict[str, dict[str, int]] = {}
    district_group_remaining: dict[str, dict[str, int]] = {}
    for district in DISTRICTS:
        head = {g: max(0, matrix[g][district] - built_district_group.get((district, g), 0))
                for g in matrix}
        for _ in range(max(0, sum(head.values()) - remaining_district[district])):
            group = sorted(head, key=lambda g: (-head[g], g))[0]
            head[group] -= 1
        mix: dict[str, int] = {}
        for group, count in sorted(head.items()):
            families = sorted(f for f in targets if group_of(f) == group)
            weights = [remaining_family[f] for f in families]
            if sum(weights) == 0:
                weights = [1.0] * len(families)
            for family, n in zip(families, apportion(count, weights)):
                if n:
                    mix[family] = mix.get(family, 0) + n
        if sum(mix.values()) != remaining_district[district]:
            raise SystemExit(f"{district}: family mix does not sum to its remainder")
        district_families[district] = mix
        district_group_remaining[district] = {g: n for g, n in sorted(head.items()) if n}

    # ---- where it can go --------------------------------------------------------
    units: list[dict] = []
    for block in grid["blocks"]:
        lots = len(block["lots"])
        capacity = lots + round(lots * ANCILLARY_PER_PRINCIPAL)
        stands = built_block.get(block["id"], 0)
        units.append({
            "id": block["id"], "kind": "platted_block",
            "district": district_of_block(block), "bounded_by": block["bounded_by"],
            "lots": lots, "capacity_roofs": capacity, "standing_roofs": stands,
            "headroom": max(0, capacity - stands),
            "state": "open" if capacity > stands else "at_capacity",
        })
    for block in grid["omitted"]:
        if block["id"] not in STREET_CONTROL_OMISSIONS:
            continue
        lots = 8
        capacity = lots + round(lots * ANCILLARY_PER_PRINCIPAL)
        units.append({
            "id": block["id"], "kind": "platted_block_awaiting_street_control",
            "district": "west" if block["id"].endswith("clinton") else "south",
            "bounded_by": block["bounded_by"], "lots": lots,
            "capacity_roofs": capacity, "standing_roofs": 0, "headroom": capacity,
            "state": "gated",
            "waiting_on": f"{block['reason']} — the street control ROADMAP S9 records as owed",
            "lots_note": "eight lots assumed from the emitted blocks' own subdivision; the "
                         "block itself is not generated, so it has no measured geometry",
        })
    # The West recipe's own remainder, derived two ways and required to agree: its 55
    # reviewed placements less the ones already emitted as records, and the placements its
    # instantiation block holds back for standing beyond the modelled terrain box.
    # Counted by the phase each record names, not by the district it stands in. Every
    # anonymous roof in the West Division came from this one recipe until a platted block
    # parcel reached `blk_randolph_clinton`, so "generated and west" and "emitted by the
    # West recipe" were the same set — and the first West block parcel put seven roofs
    # into the district that this recipe never wrote, which read here as seven of its own
    # placements having been emitted out of order. The recipe's id IS the programme phase
    # its records carry, so the question can be asked exactly.
    west_built = sum(1 for r in rows if r.get("programme_phase") == west_recipe["id"])
    west_outer = west_recipe["roof_totals"]["all"] - west_built
    beyond_box = sum(1 for p in west_recipe["placements"]
                     if p["center_local_enu_m"][0] < WEST_INSTANTIATION_BLOCK_E)
    if west_outer != beyond_box:
        raise SystemExit(
            f"the West recipe has {west_outer} placements left to emit but {beyond_box} "
            "standing beyond its instantiation block — the parcel has been instantiated "
            "out of order and this schedule cannot say what is left")
    units.append({
        "id": "west_wolf_point_outer", "kind": "reviewed_recipe_remainder",
        "district": "west", "capacity_roofs": west_outer,
        "standing_roofs": 0, "headroom": west_outer,
        "state": "gated",
        "waiting_on": "unified terrain, hydrology, collision, flora and map coverage west "
                      "to local E -700 m; the recipe's placements are already written and "
                      "reviewed",
        "recipe": "data/reconstruction/1835_phase2_west_wolf_point_approaches.json",
    })

    for district in DISTRICTS:
        placed = sum(u["headroom"] for u in units if u["district"] == district)
        balance = remaining_district[district] - placed
        unit_id, waiting = BALANCE_UNITS[district]
        units.append({
            "id": unit_id, "kind": "district_balance", "district": district,
            "capacity_roofs": max(0, balance), "standing_roofs": 0,
            "headroom": max(0, balance),
            "state": "complete" if remaining_district[district] == 0 else "gated",
            "waiting_on": waiting,
        })
        if balance < 0:
            raise SystemExit(
                f"{district}: the named units hold {placed} roofs against a remainder of "
                f"{remaining_district[district]} — the schedule cannot over-subscribe a "
                "district, so the capacity rule or the district target has moved")

    # Deal each district's remaining families across its units, in schedule order. The
    # deal is what keeps every marginal exact: unit totals, district totals and the
    # 35-family schedule all close.
    for district in DISTRICTS:
        tokens = deal(district_families[district])
        cursor = 0
        for unit in units:
            if unit["district"] != district:
                continue
            take = tokens[cursor:cursor + unit["headroom"]]
            cursor += unit["headroom"]
            mix: dict[str, int] = {}
            for family in take:
                mix[family] = mix.get(family, 0) + 1
            unit["roofs"] = len(take)
            unit["families"] = {f: mix[f] for f in sorted(mix)}
            unit["principal"] = sum(n for f, n in mix.items()
                                    if group_of(f) not in ANCILLARY_GROUPS)
            unit["ancillary"] = unit["roofs"] - unit["principal"]
        if cursor != len(tokens):
            raise SystemExit(f"{district}: {len(tokens) - cursor} roofs were not scheduled")

    schedulable = sum(u["roofs"] for u in units if u["state"] == "open")
    gated = sum(u["roofs"] for u in units if u["state"] == "gated")

    return {
        "$schema_note": "DERIVED — regenerate with tools/reconcile_665.py; tools/check.sh "
                        "re-derives it. Do not hand-edit: every number here is a function "
                        "of the committed structure records, the physical-roof "
                        "reconciliation and the authored target in "
                        "1835_building_inventory.json.",
        "id": "chicago_july_1835_665_roof_programme",
        "target_date": "1835-07-01",
        "programme_id": inventory["id"],
        "derived_by": "tools/reconcile_665.py",
        "inputs": [
            "data/structures/*.json",
            "data/reconstruction/1835_building_inventory.json",
            "data/reconstruction/1835_existing_roof_reconciliation.json",
            "data/reconstruction/1835_inferred_household_programme.json",
            "data/reconstruction/1835_phase2_west_wolf_point_approaches.json",
            "data/traces/vectors/thompson_lots.json",
        ],
        "method": {
            "roof_not_record": "A structure record is not a roof. Bridges, piers, "
                               "palisades, parade grounds, yards and a building the "
                               "chronology puts outside July 1835 contribute nothing; the "
                               "physical-roof reconciliation decides, record by record.",
            "capacity": "One principal roof per platted lot plus ancillary at the "
                        f"programme's own {154}:{511} ratio. The lot rule is the reviewed "
                        "phase-1 parcel's own density — 40 principal roofs in five blocks "
                        "of eight lots.",
            "overrun": "Where evidence has put more roofs into a family than the target "
                       "allows, the excess is reported and the remainder is reduced in the "
                       "families with the most slack. A documented roof is never removed "
                       "to protect a family cap.",
            "family_mix": "An apportionment of the district's remainder across its "
                          "schedule units, not a claim about any block. Hamilton's method "
                          "throughout, so every marginal closes exactly.",
            "naming": "A unit is named for a block only where the plat module reaches it. "
                      "Everything else is a district balance that states what it waits on.",
        },
        "standing": {
            "structure_records": len(rows),
            "physical_roofs": {"min": standing_min, "max": standing_max,
                               "range_note": "one record — the Robinson/Caldwell cabins — "
                                             "is two or three cabins in its source; the "
                                             "ledger counts the low reading."},
            "by_source": {k: built_source[k] for k in sorted(built_source)},
            "by_district": {d: built_district.get(d, 0) for d in DISTRICTS},
            "by_group": {g: sum(built_district_group.get((d, g), 0) for d in DISTRICTS)
                         for g in matrix},
            "by_family": {f: built_family.get(f, 0) for f in sorted(targets)},
            "records_contributing_no_roof": sorted(r["id"] for r in rows if not r["roofs_min"]),
        },
        "remaining": {
            "roofs": remaining_total,
            "of_target": roof_total,
            "by_district": remaining_district,
            "by_district_group": district_group_remaining,
            "by_family": {f: remaining_family[f] for f in sorted(remaining_family)},
            "by_district_family": district_families,
            "family_targets_already_exceeded": overrun,
            "absorbed_from": absorbed,
        },
        "coverage": {
            "schedulable_on_committed_ground": schedulable,
            "gated_on_coverage": gated,
            "statement": f"{schedulable} of the {remaining_total} remaining roofs stand on "
                         "ground this project has already surveyed, platted and modelled. "
                         f"The other {gated} have nowhere to go until street control, "
                         "terrain and hydrology reach them. The binding constraint on the "
                         "665-roof programme is coverage, not recipes.",
            "platted_lots": sum(len(b["lots"]) for b in grid["blocks"]),
            "blocks_named": sum(1 for u in units if u["kind"].startswith("platted_block")),
        },
        "schedule": units,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed programme is not what the dataset and "
                             "the target re-derive")
    args = parser.parse_args()
    programme = programme_document()
    text = json.dumps(programme, indent=1, ensure_ascii=False) + "\n"
    if args.check:
        if not OUT_PATH.exists():
            print(f"665 PROGRAMME DRIFT\n  - {OUT_PATH.relative_to(ROOT)} is missing")
            return 1
        if OUT_PATH.read_text(encoding="utf-8") != text:
            print("665 PROGRAMME DRIFT\n  - data/reconstruction/"
                  "1835_665_roof_programme.json is not what the committed structure "
                  "records, the roof reconciliation and the authored target re-derive. "
                  "Re-run tools/reconcile_665.py and commit the result alongside the "
                  "records that moved it.")
            return 1
    else:
        OUT_PATH.write_text(text, encoding="utf-8")
    print(f"{'verified' if args.check else 'generated'} the 665-roof programme: "
          f"{programme['standing']['physical_roofs']['min']} standing, "
          f"{programme['remaining']['roofs']} remaining, "
          f"{programme['coverage']['schedulable_on_committed_ground']} of them on ground "
          "the project has coverage for")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
