#!/usr/bin/env python3
"""Reconcile the roof programme against the town that has actually been built.

THE 665 IN THIS TOOL'S NAME IS HISTORY, and it is kept deliberately. The authored total
became **662** on 2026-08-27 (ticket T-0032): three of family I3's six civic slots were
shown to count nothing — the town's public buildings with a roof on 1835-07-01 are three
named records — so the three came off the total rather than being re-typed into ordinary
families. Renaming the file, the tool and every reference to them is churn; the live total
is read from the inventory on every run and written to `remaining.of_target`. Nothing in
here hardcodes it.

ROADMAP T-A1. `data/reconstruction/1835_building_inventory.json` states the target —
roofs split by district, by group and by a 35-family schedule — and it has never been
subtracted from. The crosswalk still calls 617 roofs "remaining", a figure that predates
the North parcel, the West parcel, the inferred-household buildings and every documented
roof the research has since placed. A programme whose remainder is wrong by 185 roofs
cannot schedule the next block, which is why this runs before the block parcels do.

Everything here is DERIVED. The inputs are the structure records themselves, the
physical-roof reconciliation of the pre-existing ones, the inferred-household programme
and the platted grid; the output is `data/reconstruction/1835_665_roof_programme.json`,
regenerated by this tool and re-derived by `tools/check.sh`. Nothing in it is a number
somebody typed, which is the only way a ledger stays true to a dataset that grows nightly.

What each part of the output is entitled to claim:

* **What stands** is a count of committed records, not an estimate. A pre-existing record
  contributes the physical roofs the reconciliation credits it — 0 for a bridge, a pier, a
  parade ground or a building whose July existence the chronology contradicts; a generated
  or inferred-household record contributes one.
* **What remains** is arithmetic on the authored target and nothing else. Where evidence
  has already put MORE roofs into a family than the target allows, the excess is reported
  and the remainder comes out of the invented families with the most slack: a documented
  building is never removed to protect a family cap.
* **Where it can go** is the honest part and the uncomfortable one. A block can be named
  only where the plat module reaches it, which today is 19 blocks holding 152 lots. The
  schedule names every one of them with its own headroom, names the two blocks the module
  refuses for want of street control, carries the West recipe's own extension-gated
  figure, and puts the balance into one unit per district that says what it waits on
  rather than inventing a block number this project has never read off a sheet.
* **A per-unit family mix** is an apportionment of that district's remainder, not a claim
  about any block. It is what makes the schedule addable: every unit's families sum to its
  count, every district's units sum to its remainder, and the districts sum to the target.

    tools/reconcile_665.py            regenerate the programme file
    tools/reconcile_665.py --check    fail if the committed file is not what the dataset
                                      and the target re-derive
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
RECON = DATA / "reconstruction"
OUT_PATH = RECON / "1835_665_roof_programme.json"

sys.path.insert(0, str(ROOT / "tools"))

# Lot occupancy is derived in ONE place and imported by both halves of the T-A6 rule.
# See tools/plat_occupancy.py for why it is a module rather than a copied loop.
from plat_occupancy import (block_of_structure, exclusive_lots,  # noqa: E402
                            occupied_lots)
# The business-front term (T-0213). Both halves are measurements the census makes, not
# constants authored here: `trade_share_by_class` is the DOCUMENTED trade share per class
# of street, and `street_traffic` is the committed hierarchy those classes come from.
from measure_frontage_fabric import (TRADE_LETTERS, street_traffic,  # noqa: E402
                                     trade_share_by_class)

# Groups are the inventory's own ten, and a family belongs to its group by its letter.
# The letters are checked against the target itself: each group's families must sum to
# that group's total, or the mapping below has drifted from the document it reads.
GROUP_OF_LETTER = {
    "D": "ordinary_dwellings",
    "H": "larger_boarding_houses",
    "C": "stores_mixed_use",
    "T": "inns_taverns",
    "W": "workshops",
    "F": "warehouses_freight",
    "I": "institutional_public",
    "M": "fort_principal",
}
ANCILLARY_GROUPS = {"barns_stables", "small_outbuildings"}

DISTRICTS = ["south", "west", "north", "fort"]

# Ancillary roofs at the programme's own ratio: the inventory's targets are 508 principal
# to 154 ancillary, which is a reading of the dataset rather than a tuning knob. It was
# 154:511 until T-0032 took three phantom civic roofs off the total; all three were
# principal, so the ancillary half did not move. The ceiling is unchanged either way — an
# eight-lot block rounds to seven yard buildings at both ratios — which is worth saying,
# because a capacity that HAD moved would have re-dealt blocks this ticket never touched.
ANCILLARY_PER_PRINCIPAL = 154 / 508

# THE CORE DENSITY STANDARD (T-0079), and it replaces one principal roof per platted lot.
#
# The old rule was the reviewed phase-1 parcel's own density — 40 principal roofs into
# five blocks of eight lots, exactly one per lot — and it refused to go further in these
# words: "a denser core would be a decision about lot subdivision, and four lots to a face
# is a reading of ONE block that the grid itself grades `conjectural`, so that decision is
# not taken here." Two things retire that refusal.
#
# **The dataset already exceeds the ceiling.** Five of the twelve core blocks the plat
# module reaches stand at 11, 12, 13, 14 and 14 roofs against a ceiling of 10, put there by
# the reviewed phase-1 parcel and by the documented record. A ceiling the town passed by
# two fifths before this rule was written is not bounding anything; it is only refusing
# the NEXT roof, which is the one an owner asked for.
#
# **And it is counted in the conjectural unit.** The side lot lines are conjectural — every
# record this project writes says so in its own position note — while the block FACE is
# committed geometry derived from the street centrelines. Counting a block's capacity in
# lots counts it in the unit the grid grades lowest. T-0078's party-line run already stands
# on the face instead, and the count that binds a run is metres of frontage.
#
# So the ceiling is now a frontage count, and it is NOT lot subdivision: a run does not
# divide the lot, it stands across the face, and the side lines it crosses were never
# claimed. The ratio is measured, at the WORST case rather than the median so it holds for
# every lot on the committed grid:
#
#   * the eighteen units of the committed party-line rows — fourteen on South Water,
#     four on Lake at Dearborn — are 5.04 m to 6.75 m wide, mean 6.072 m;
#   * the SMALLEST lot on the committed grid has 23.56 m of frontage, and the plat
#     module keeps 1.5 m clear of a side line at each end of a run;
#   * (23.56 − 3.00) / 6.072 = 3.39, so three units fit on the meanest lot in the town
#     and the fourth does not.
#
# Three, therefore, and the third is the last one that fits. A run across adjoining lots
# pays the two end margins once rather than per lot, so 3 × lots is conservative there too.
#
# The owner's ruling of 2026-08-18 is the warrant for taking the decision now: "there
# should be more and denser buildings. this is important." What it does NOT do is grow the
# authored roof total — the roofs come out of `south_plat_beyond_committed_control`, the
# district balance waiting on street control that may never arrive, and the marginals
# still close.
ROW_UNITS_PER_LOT = 3


def block_capacity(lots: int) -> int:
    """The roofs a platted block's ground can hold: its frontage, plus its yard buildings.

    A CEILING and not a target — the file this feeds says so itself, and `block_rooms`
    below is where the restraint lives: a block still keeps a lot open, and a principal
    roof still needs a free lot to stand on.
    """
    principal = lots * ROW_UNITS_PER_LOT
    return principal + round(principal * ANCILLARY_PER_PRINCIPAL)

# The blocks the plat module refuses for want of street control, as against the three it
# refuses because what lies between the streets is the river. Named here so that a block
# which starts being emitted stops being scheduled as gated.
#
# T-0163 SPLIT THIS SET IN TWO, because a refusal distance cannot tell two very different
# cases apart and both were being counted as headroom waiting on the same owed trace.
# `tools/measure_block_gating.py` carries each named street toward the block it is supposed
# to bound and samples the run against the committed heightfield:
#
#   blk_south_water_market    south_water  25 m away,   0 of 5 samples wet
#   blk_south_water_clinton   south_water 328 m away,  20 of 66 samples wet
#
# THE FIRST IS STILL DRY AND STILL GATED, AND SINCE 2026-08-27 IT IS GATED ON A DIFFERENT
# THING. T-0183 went to fetch the one control point it waits on — Market x South Water —
# and the rule cannot make it: the two modern successors meet at a BEND, not a crossing,
# and return lake_market's own nodes 110 m away (data/traces/street_control.json,
# `refused_control.market_south_water`). The block stays here because it is real dry
# ground with 27 roofs of headroom, but what it waits on is now an owner decision about
# how to close South Water's west end, not an errand.
#
# The second is the South Branch. South Water Street is a SOUTH-BANK street; the block
# between Clinton and Canal is on the West Side, two blocks back from the west bank. No
# street control will ever join them, because the row does not run that far and never did:
# the west bank's own riverside street was WEST WATER STREET, and this project already
# records — on `data/traces/street_control.json` and as the largest residual uncertainty on
# green_tree_tavern and goss_cobb_saddlery — that West Water ran along the bank with modern
# Canal Street a full block (~146 m) further west. So West Water does not bound this block
# either. The pairing is an artifact of the grid being a CARTESIAN PRODUCT of rows and
# columns, and scheduling its 27 roofs against "street control ROADMAP S9 records as owed"
# promised ground that no trace can deliver. Those roofs go back to the West Division
# balance, where "waiting on coverage" is a statement the ledger can actually make.
STREET_CONTROL_OMISSIONS = {"blk_south_water_market"}

# Refused because the two streets never met, not because a centreline is short. Kept in the
# schedule rather than dropped, so the block is visibly answered instead of silently absent
# — and so the day a source shows the row really did run that far, this is where the claim
# is argued rather than re-discovered.
NEVER_PLATTED_OMISSIONS = {"blk_south_water_clinton"}

# The West recipe's own instantiation block: "do not emit structure records or meshes for
# any placement with centre E < -300 m until the heightfield, collision surface,
# vegetation sampler, minimap and water mask share the extended box." Read as a number
# here only to cross-check the recipe's remainder against the records actually emitted.
WEST_INSTANTIATION_BLOCK_E = -300.0

# What the balance of each district is waiting on. The West entry is the street control
# ROADMAP S9 records as owed; the North entry is the coverage the North parcel's own
# recipe names. No block can be named inside any of them, which is the point.
#
# THE SOUTH ENTRY IS NOT AUTHORED HERE ANY MORE, and T-0026 is why. It used to name street
# control alone — "no block east of State or south of Washington has four committed
# centrelines" — and that is true, downstream, and it sent the next parcel to go and carry
# a centreline. `tools/measure_southern_ground.py` measures what is actually there: the
# modelled box ends at local N -400 m, INSIDE Washington Street's own platted corridor, so
# every north-south column of the south plat has its committed line cut at exactly that
# line and Madison — the plat's south boundary, resolved from the section corner at State &
# Madison — is 125 m further south again. Street control stops where the ground does. The
# south's `waiting_on` is composed from that measurement below, so it cannot go stale the
# day the terrain moves.
BALANCE_UNITS = {
    "south": ("south_plat_beyond_committed_control", None),
    "west": (
        "west_division_beyond_committed_control",
        "West Division ground beyond the Wolf Point approaches: no committed street "
        "control west of Clinton and Canal, and no unified terrain, hydrology or map "
        "coverage past the recipe's own gate at local E -700 m.",
    ),
    "north": (
        "north_division_beyond_modelled_ground",
        "North Division ground beyond the initial parcel: the plat grid covers no North "
        "Division block at all — that street control is what ROADMAP S9 records as owed — "
        "and terrain, hydrology, flora and map coverage stop short of local N +760 m.",
    ),
    "fort": (
        "fort_dearborn_compound",
        "The compound's ten principal roofs are placed; the stockade, parade and props "
        "are outside the roof count by the inventory's own definition.",
    ),
}


def load(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def group_of(family: str) -> str:
    if family.startswith("A"):
        return "barns_stables" if family in ("A1", "A2") else "small_outbuildings"
    return GROUP_OF_LETTER[family[0]]


def apportion(total: int, weights: list[float]) -> list[int]:
    """Hamilton's method — proportional, integer, sums exactly, ties broken by position."""
    if total <= 0 or not weights:
        return [0] * len(weights)
    mass = sum(weights)
    if mass <= 0:
        out = [0] * len(weights)
        out[0] = total
        return out
    exact = [total * w / mass for w in weights]
    out = [int(x) for x in exact]
    order = sorted(range(len(weights)), key=lambda i: (-(exact[i] - out[i]), i))
    for i in order[: total - sum(out)]:
        out[i] += 1
    return out


def deal(counts: dict[str, int]) -> list[str]:
    """A deterministic mixed deal: each family's tokens are spread evenly over the whole
    run, so dealing the run to units in order gives every unit the district's mix rather
    than one family per block."""
    total = sum(counts.values())
    tokens = []
    for family, n in sorted(counts.items()):
        for i in range(n):
            tokens.append((((i + 0.5) * total) / n, family))
    tokens.sort(key=lambda t: (t[0], t[1]))
    return [family for _, family in tokens]


# ---- the business-front term (T-0213) --------------------------------------------
#
# The schedule apportions families by DISTRICT and has no notion of a street. Measured on
# the committed record, that is wrong in one particular: the DOCUMENTED trade share is
# monotone in the committed street hierarchy — 0.7778 of the documented buildings standing
# nearest a `principal` street carry a trade family, 0.4545 on an `ordinary` street and
# 0.0000 on a `light` one (`tools/measure_frontage_fabric.py --trade`, 68 records). So a
# block dealt a South Water face should be likelier to be dealt C, F and W than a block two
# streets back, and until this term it was not: `blk_south_water_franklin` and
# `blk_south_water_lasalle` between them held twelve of the business front's roofs and not
# one of them was a store, a warehouse or a workshop.
#
# What this is NOT. It does not raise or lower the target, it does not move a roof between
# districts, and it does not change how many roofs any unit is dealt. It is a PERMUTATION
# of the principal families a district's platted blocks were already dealt, among those
# same blocks — so every marginal that closed before it closes after it, by construction
# rather than by a check. The proof is cheap and it is asserted below.
#
# It reads only the RESEARCH layer, which is the part that makes it a measurement rather
# than a feedback loop: weighting the schedule by what the schedule invented would be the
# programme grading its own homework, and the share would ratchet with every block built.


def is_trade(family: str) -> bool:
    """C stores, F warehouses, W workshops — the letters the trade share was measured on.

    Imported from the census rather than restated here, so the weight and the measurement
    it is derived from cannot come to disagree about what a trade building is.
    """
    return family[0] in TRADE_LETTERS


def frontage_weight(bounded_by: dict, shares: dict, traffic: dict) -> float:
    """A block's expected trade share, read off the streets that bound it.

    Every face of a platted block is a committed street carrying a committed traffic class,
    and the documented record gives each class its own trade share. A block's weight is the
    mean of its own four faces' shares — a South Water block has two principal faces of
    four, a Randolph block has none — so the schedule tells them apart without anybody
    typing a number for either. Re-class a street on `data/streets/1835.json` and every
    block on it re-weights in the same commit.

    A face whose class the documented record says nothing about takes the mean of the
    classes it does speak for, so an unmeasured street neither promotes nor demotes a block.
    """
    if not bounded_by:
        return 0.0
    measured = [row["share"] for row in shares.values()]
    fallback = sum(measured) / len(measured) if measured else 0.0
    faces = [shares[traffic[street]]["share"]
             if traffic.get(street) in shares else fallback
             for street in bounded_by.values()]
    return sum(faces) / len(faces)


def _fit(quota: list[int], slots: list[int], weights: list[float]) -> list[int]:
    """Hamilton's quota, clipped to the slots each unit actually has.

    A weight says how MUCH of the trade a block should attract; it cannot say the block has
    room for it. Overflow is re-apportioned over the blocks that still have a principal slot
    free, at their own weights, until it fits — and it always fits, because the tokens being
    placed came out of these same slots.
    """
    quota = list(quota)
    while True:
        excess = sum(max(0, q - s) for q, s in zip(quota, slots))
        if not excess:
            return quota
        free = [i for i, (q, s) in enumerate(zip(quota, slots)) if q < s]
        quota = [min(q, s) for q, s in zip(quota, slots)]
        if not free:
            raise SystemExit("business front: more trade roofs than principal slots")
        for i, extra in zip(free, apportion(excess, [weights[i] for i in free])):
            quota[i] += extra


def weight_the_business_front(units: list[dict], shares: dict,
                              traffic: dict) -> list[dict]:
    """Re-deal each district's PRINCIPAL families across its platted blocks by frontage.

    Only units with a `bounded_by` take part: a district balance and the West recipe
    remainder stand on no committed street at all, so there is nothing to weight them by
    and they keep exactly what the district deal gave them.

    Returns one row per district that moved, for the ledger.
    """
    moved = []
    for district in DISTRICTS:
        blocks = [u for u in units
                  if u["district"] == district and u.get("bounded_by") and u.get("roofs")]
        if len(blocks) < 2:
            continue
        pool: dict[str, int] = {}
        slots: list[int] = []
        before: list[dict[str, int]] = []
        for unit in blocks:
            count = 0
            for family, n in unit["families"].items():
                if group_of(family) in ANCILLARY_GROUPS:
                    continue
                pool[family] = pool.get(family, 0) + n
                count += n
            slots.append(count)
            before.append(dict(unit["families"]))
        trade_total = sum(n for f, n in pool.items() if is_trade(f))
        if not trade_total or trade_total == sum(slots):
            continue

        weights = [n * frontage_weight(u["bounded_by"], shares, traffic)
                   for n, u in zip(slots, blocks)]
        quota = _fit(apportion(trade_total, weights), slots, weights)

        trade = deal({f: n for f, n in pool.items() if is_trade(f)})
        other = deal({f: n for f, n in pool.items() if not is_trade(f)})
        changed = 0
        for index, unit in enumerate(blocks):
            take = trade[:quota[index]] + other[:slots[index] - quota[index]]
            trade, other = trade[quota[index]:], other[slots[index] - quota[index]:]
            mix = {f: n for f, n in unit["families"].items()
                   if group_of(f) in ANCILLARY_GROUPS}
            for family in take:
                mix[family] = mix.get(family, 0) + 1
            unit["families"] = {f: mix[f] for f in sorted(mix)}
            unit["frontage_weight"] = round(
                frontage_weight(unit["bounded_by"], shares, traffic), 4)
            unit["trade_roofs"] = quota[index]
            changed += unit["families"] != before[index]
        if trade or other:
            raise SystemExit(f"{district}: business front left {len(trade) + len(other)} "
                             "principal roofs unplaced")

        # The permutation is the whole safety argument, so it is asserted rather than
        # trusted: the same families, the same count in every block, the same trade total.
        after: dict[str, int] = {}
        for unit in blocks:
            for family, n in unit["families"].items():
                after[family] = after.get(family, 0) + n
        combined: dict[str, int] = {}
        for row in before:
            for family, n in row.items():
                combined[family] = combined.get(family, 0) + n
        if after != combined:
            raise SystemExit(f"{district}: the business-front deal is not a permutation")
        for unit, count in zip(blocks, slots):
            got = sum(n for f, n in unit["families"].items()
                      if group_of(f) not in ANCILLARY_GROUPS)
            if got != count:
                raise SystemExit(f"{unit['id']}: dealt {got} principal roofs against "
                                 f"{count} before the business-front term")
        moved.append({"district": district, "blocks": len(blocks),
                      "trade_roofs": trade_total, "blocks_redealt": changed,
                      "quota": {u["id"]: q for u, q in zip(blocks, quota)}})
    return moved


# ---- the waterside term (T-0316) -------------------------------------------------
#
# THE PLAT IS NOT GROUND A LANDING APRON CAN STAND ON, AND THAT IS A FACT ABOUT THE
# GENERATOR RATHER THAN ABOUT ANY ONE BLOCK.
#
# `tools/generate_block_infill.py` authors no coordinates. Every metre it places comes
# from a committed lot polygon inside a block bounded by four platted STREETS, and the
# wharf and landing ground of the main stem lies outside that grid entirely — it is
# placed by `tools/generate_river_wharves.py` against the committed bank. So a family
# whose own crosswalk record makes water access a PRECONDITION OF THE FORM cannot be
# built by the parcel that builds platted blocks, at any distance: even on a block whose
# own face is a river street, the apron would have to cross a public one.
#
# T-0028 found this on 2026-08-28 by opening `blk_lake_franklin` and being unable to
# build the F3 it had been dealt, 134 m from the nearest water. The stopgap was to put
# F3 in the block generator's `REFUSED_FAMILIES`, so a recipe meeting the slot DEFERS it
# with a stated reason (L203) rather than reaching for a shape. That keeps the roof on
# the books, and it treats a fault in the DEAL as a fault at the block: every future
# platted block dealt an F3 defers it, and the deferrals accumulate. T-0316 moves the
# repair upstream, which is T-0213's shape — weight the deal, do not teach each block to
# refuse.
#
# IT IS A PERMUTATION, exactly as the business front is: a waterside roof on a platted
# block is exchanged for a principal roof of the same trade-ness sitting in that
# district's own unbounded balance — the ground beyond committed control, which is where
# the wharf and landing ground is. No total moves: not the target, not a district, not a
# family, not any unit's roof count, not its principal/ancillary split. A district with
# no unbounded partner to swap with HOLDS the roof and says so, because a deal that
# quietly dropped it would be worse than the fault.

# The words that make a crosswalk entry a CANDIDATE for the waterside rule. Read off the
# record's `required_variant` and its `variants` line, which is where the form lives.
WATERSIDE_CANDIDATE_WORDS = ("river", "landing", "dock", "wharf", "quay")

# ...and the judgement on each candidate, which the keyword scan cannot make: whether
# the record's own assumption note states water access as a REQUIREMENT of the form or
# as a conditional variant. The note is quoted VERBATIM so that editing the record fails
# this derive rather than silently re-classifying a family — and a new candidate the
# crosswalk grows tomorrow fails it by name, unjudged, which is the point.
WATERSIDE_JUDGEMENT = {
    "F3": (True, "Landing apron and cargo-door arrangement must follow site access and "
                 "cannot extend into water or duplicate a counted pier."),
    "W5": (True, "A crane/derrick is rare and must not become a default; river access "
                 "requires validated dry-bank terrain contact."),
    # NOT waterside, and the record is what says so: the dock relationship is unknown for
    # an anonymous slot and the skids are conditional on the site, so an F1 dealt to a
    # platted block is a freight shed without skids rather than a form that cannot stand.
    # T-0316 was asked to check F1, F2 and F4 while it was here; F2 ("Hoist beam presence
    # varies; cargo type and operator are not inferred") and F4 ("Board-stack quantity and
    # open-side pattern are visual variation, not inventory facts") name no water at all
    # and are not candidates, so they are not listed — being absent from this table is
    # itself the statement, and the scan below is what keeps it true.
    "F1": (False, "Stored goods and dock relationship are not known for anonymous slots; "
                  "skids belong only where terrain and route access support them."),
}


def waterside_families() -> dict[str, str]:
    """The families the committed crosswalk makes waterside, and the sentence that says so.

    Two readings of the same record have to agree or this refuses to derive: the keyword
    scan says which families are even in question, and `WATERSIDE_JUDGEMENT` says which of
    those the record REQUIRES water for, quoting its own assumption note back at it.
    """
    crosswalk = load(DATA / "reconstruction" / "1835_family_archetype_crosswalk.json")
    seen: dict[str, str] = {}

    def walk(node):
        if isinstance(node, dict):
            if "id" in node and "label" in node and "required_variant" in node:
                hay = " ".join([
                    str(node.get("required_variant") or ""),
                    str((node.get("key_geometry_parameters") or {}).get("variants") or ""),
                ]).lower()
                if any(word in hay for word in WATERSIDE_CANDIDATE_WORDS):
                    seen[node["id"]] = str(node.get("assumption_note") or "").strip()
            for value in node.values():
                walk(value)
        elif isinstance(node, list):
            for value in node:
                walk(value)

    walk(crosswalk)
    unjudged = sorted(set(seen) - set(WATERSIDE_JUDGEMENT))
    if unjudged:
        raise SystemExit(
            f"the crosswalk names water in the form of {', '.join(unjudged)} and "
            "tools/reconcile_665.py carries no judgement on them. Read each record's "
            "assumption_note and add it to WATERSIDE_JUDGEMENT — requiring water is a "
            "reading of the record, not of a keyword.")
    stale = sorted(set(WATERSIDE_JUDGEMENT) - set(seen))
    if stale:
        raise SystemExit(
            f"WATERSIDE_JUDGEMENT judges {', '.join(stale)}, which the crosswalk no "
            "longer names water in. The record moved; re-read it.")
    for family, (_, quoted) in sorted(WATERSIDE_JUDGEMENT.items()):
        if seen[family] != quoted:
            raise SystemExit(
                f"{family}: WATERSIDE_JUDGEMENT quotes an assumption note the crosswalk "
                "no longer carries. Re-read the record and re-make the judgement.\n"
                f"  crosswalk: {seen[family]}\n  here:      {quoted}")
    return {f: q for f, (requires, q) in sorted(WATERSIDE_JUDGEMENT.items()) if requires}


def _take_one(unit: dict, family: str) -> None:
    unit["families"][family] -= 1
    if unit["families"][family] == 0:
        del unit["families"][family]


def _give_one(unit: dict, family: str) -> None:
    unit["families"][family] = unit["families"].get(family, 0) + 1
    unit["families"] = {f: unit["families"][f] for f in sorted(unit["families"])}


def keep_the_waterside_off_the_plat(units: list[dict], waterside: dict[str, str],
                                    shares: dict, traffic: dict) -> dict:
    """Exchange every waterside roof on a platted block for a principal roof on the
    district's own unbounded balance. See the block comment above."""
    swapped, held = [], []
    for district in DISTRICTS:
        blocks = [u for u in units
                  if u["district"] == district and u.get("bounded_by") and u.get("roofs")]
        balances = [u for u in units
                    if u["district"] == district and not u.get("bounded_by")
                    and u.get("roofs")]
        for unit in blocks:
            for family in sorted(f for f in unit["families"] if f in waterside):
                for _ in range(unit["families"][family]):
                    partner = None
                    # Same trade-ness first, so the business-front weighting this term
                    # runs after is left exactly where T-0213 put it; anything principal
                    # and dry after that, and the ledger says which rule was used.
                    for want_same_trade in (True, False):
                        for other in balances:
                            for candidate in sorted(other["families"]):
                                if candidate in waterside:
                                    continue
                                if group_of(candidate) in ANCILLARY_GROUPS:
                                    continue
                                if want_same_trade and is_trade(candidate) != is_trade(family):
                                    continue
                                partner = (other, candidate)
                                break
                            if partner:
                                break
                        if partner:
                            break
                    if partner is None:
                        held.append({
                            "unit": unit["id"], "family": family,
                            "why": f"{district} has no unbounded balance holding a dry "
                                   "principal roof to exchange, so the roof stays on the "
                                   "block and the block generator defers it (L203)",
                        })
                        continue
                    other, candidate = partner
                    _take_one(unit, family)
                    _give_one(unit, candidate)
                    _take_one(other, candidate)
                    _give_one(other, family)
                    swapped.append({
                        "family": family, "from": unit["id"], "to": other["id"],
                        "for": candidate,
                        "same_trade": is_trade(candidate) == is_trade(family),
                    })
            if unit.get("bounded_by"):
                unit["trade_roofs"] = sum(n for f, n in unit["families"].items()
                                          if is_trade(f))
                unit["frontage_weight"] = round(
                    frontage_weight(unit["bounded_by"], shares, traffic), 4)
    # The permutation is the safety argument, so it is asserted rather than trusted.
    for unit in units:
        if not unit.get("families"):
            continue
        roofs = sum(unit["families"].values())
        if roofs != unit["roofs"]:
            raise SystemExit(f"{unit['id']}: the waterside term changed a roof count")
        principal = sum(n for f, n in unit["families"].items()
                        if group_of(f) not in ANCILLARY_GROUPS)
        if principal != unit["principal"]:
            raise SystemExit(f"{unit['id']}: the waterside term moved an ancillary roof")
    stranded = sorted(f"{u['id']}.{f}" for u in units if u.get("bounded_by")
                      for f in u.get("families", {}) if f in waterside)
    if len(stranded) != len(held):
        raise SystemExit("the waterside term left a waterside family on a platted block "
                         f"without holding it: {', '.join(stranded)}")
    return {"swapped": swapped, "held": held}


def inside(point, polygon) -> bool:
    x, y = point
    hit = False
    j = len(polygon) - 1
    for i in range(len(polygon)):
        xi, yi = polygon[i]
        xj, yj = polygon[j]
        if (yi > y) != (yj > y) and x < (xj - xi) * (y - yi) / (yj - yi) + xi:
            hit = not hit
        j = i
    return hit


def block_rooms(free_lots: int, headroom_roofs: int) -> tuple[int, int]:
    """(principal, ancillary) a block can actually take, from its FREE LOTS.

    A block's room was counted in roofs and nothing else until ROADMAP T-A6, and roofs
    are not what binds it. Three separate things do, and the schedule could see only the
    first:

    1. the town's own roof ratio — one principal per lot plus ancillary at 154:511 —
       less what already stands in the block. That is `headroom_roofs`, unchanged.
    2. **a principal roof needs a FREE LOT**, and a free lot carries up to
       `ROW_UNITS_PER_LOT` of them (T-0079): a party-line run is bounded by the metres of
       frontage it stands on, not by the conjectural side lines it crosses. A lot with
       somebody's house on it is not
       headroom, and `standing_roofs` cannot tell the difference: two roofs on one lot
       and two roofs on two lots subtract the same. Half the open blocks were being dealt
       principal roofs with nowhere to stand — `blk_south_water_clark` and
       `blk_lake_market` were dealt seven against six free lots, which no recipe could
       have written down, and three more were dealt exactly as many as they had free.
    3. **the block keeps one lot open.** The parcel recipe's own placement rule says so
       — "a block at capacity is a claim about 1835 that the evidence does not support;
       the schedule's capacity is a ceiling" — and until now that was a promise each
       parcel made by hand, which a block dealt exactly its free-lot count could not
       keep. A rule a parcel can be dealt out of is not a rule.

    And the ancillary count is bounded by the principal one, because the generator's
    yard-building gate is that an ancillary roof stands in the yard of a principal roof
    THIS parcel built. `blk_randolph_dearborn` was dealt one ancillary and no principal,
    so its backfill (T-A3h) was unbuildable for that reason rather than this one — the
    same blindness, seen from the other end.
    """
    principal = max(0, min(ROW_UNITS_PER_LOT * (free_lots - 1), headroom_roofs))
    ancillary = min(round(principal * ANCILLARY_PER_PRINCIPAL), headroom_roofs - principal)
    return principal, max(0, ancillary)


def standing_roofs(grid, datum, taken):
    """Every committed structure record, with the physical roofs it puts in the scene and
    the platted block it stands in, where the grid reaches it.

    **A roof standing on a block's lot stands in that block**, which is the second half
    of the T-A7 finding. The block was read off the record's position POINT against the
    block boundary, and a building placed a metre proud of its own frontage has that
    point in the roadway: the Exchange Coffee House holds nine tenths of a lot of
    `blk_south_water_franklin` and was counted as standing in no block at all. Its
    roof was therefore not subtracted from the headroom of the block it stands in, so
    the schedule offered that block room a visitor can see is already built on. The
    occupancy map — derived from the footprint, in `tools/plat_occupancy.py` — answers
    it where the point cannot.
    """
    home = block_of_structure(taken)
    reconciliation = {
        r["structure_id"]: r
        for r in load(RECON / "1835_existing_roof_reconciliation.json")["records"]
    }
    households = {
        b["id"]: b
        for b in load(RECON / "1835_inferred_household_programme.json")["buildings"]
    }
    rows = []
    for path in sorted((DATA / "structures").glob("*.json")):
        record = load(path)
        rid = record["id"]
        # WHICH PROGRAMME RAISED THIS ROOF, not merely whether it discloses a family
        # band. Both answers used to be the same question, because only the anonymous
        # generators wrote a reconstruction block. Since K21 the inferred-household
        # layer's 31 buildings carry one too — they are drawn from the same family
        # bands and now say so in a field — and a bare `"reconstruction" in record`
        # test moved all 31 out of `inferred_household_programme` and into
        # `generated`. The totals were unchanged, which is exactly why it is worth a
        # gate's attention: the ledger would have gone on reporting 665 roofs while
        # crediting a third of the household layer to a generator that never ran.
        block = record.get("reconstruction") or {}
        if block.get("status") == "inferred_anonymous":
            row = {"id": rid, "source": "generated", "district": block["district"],
                   "family": block["family"], "roofs_min": 1, "roofs_max": 1,
                   "programme_phase": block.get("programme_phase")}
        elif rid in reconciliation:
            entry = reconciliation[rid]
            count = entry["inventory_roof_count"] if entry["inventory_eligible"] else 0
            row = {"id": rid, "source": "pre_existing", "district": entry["district"],
                   "family": entry.get("likely_family"),
                   "roofs_min": count["min"] if isinstance(count, dict) else count,
                   "roofs_max": count["max"] if isinstance(count, dict) else count}
        elif rid in households:
            entry = households[rid]
            row = {"id": rid, "source": "inferred_household_programme",
                   "district": entry["district"], "family": entry["family"],
                   "roofs_min": 1, "roofs_max": 1}
        else:
            raise SystemExit(
                f"{rid} belongs to no programme this ledger can read. A structure record "
                "must carry a reconstruction block, or be an entry in the physical-roof "
                "reconciliation, or be a building of the inferred-household programme — "
                "otherwise it stands in the scene and not in the count."
            )
        if row["family"] is None and row["roofs_min"]:
            raise SystemExit(f"{rid} contributes a roof with no family to count it under")
        position = next((p["position"] for p in record["phases"]
                         if p.get("position") and p["position"].get("utm_e") is not None), None)
        row["block"] = home.get(rid)
        if row["block"] is None and position:
            point = (position["utm_e"] - datum["origin_utm_e"],
                     position["utm_n"] - datum["origin_utm_n"])
            for block in grid["blocks"]:
                if inside(point, block["boundary_local_enu_m"]):
                    row["block"] = block["id"]
                    break
        rows.append(row)
    return rows


def district_of_block(block) -> str:
    """A block is West Division ground when it lies west of the South Branch, which at
    this datum is local easting 0 — the origin IS the forks. No block in the grid
    straddles a division line."""
    return "west" if max(p[0] for p in block["boundary_local_enu_m"]) < 0 else "south"


def southern_ground() -> tuple[dict, str]:
    """The measured state of the ground south of the committed plat, and what it says.

    T-0026. Imported rather than restated so that the schedule's southern blocker and the
    command a reader can run to check it are the same arithmetic — the discipline
    `tools/measure_street_frontage.py` set for the face rule and `measure_block_gating.py`
    for the refused blocks. `tools/measure_southern_ground.py --gate` holds the pair
    together in `tools/check.sh`.
    """
    from measure_southern_ground import coverage_figures, measure  # noqa: PLC0415

    m = measure()
    figures = coverage_figures(m)
    return figures, (
        f"TERRAIN, and not the street control ROADMAP S9 records as owed. The modelled "
        f"heightfield ends at local N {figures['field_south_edge_n_m']:.1f} m, which falls "
        f"inside Washington Street's own platted corridor — "
        f"{m['washington_corridor']['area_m2'] / 1e4:.2f} ha of that street's south half "
        f"lies off the field. South of the corridor the field holds "
        f"{figures['land_south_of_committed_plat_ha']:.4f} ha of land above the water "
        f"surface and "
        f"{figures['south_division_land_south_of_committed_plat_ha']:.4f} ha of it is in "
        f"the South Division: the rest is the West Division bank, across the South Branch. "
        f"Madison Street, the plat's south boundary, is "
        f"{figures['madison_south_of_field_m']:.1f} m further south again, so the plat's "
        f"last tier — {figures['unmodelled_tier_blocks']} blocks and "
        f"{figures['unmodelled_tier_lots']} lots between Market and State, "
        f"{figures['unmodelled_tier_area_ha']:.2f} ha — is not modelled ground at all. "
        f"Every north-south column of the south plat has its committed centreline cut at "
        f"the field's own south edge, so carrying street control further south would emit "
        f"blocks whose every placement tools/generate_block_infill.py refuses for standing "
        f"outside the modelled terrain. Ground east of State is not coming at any date — "
        f"it is the United States Reservation (T-E2). Measured by "
        f"tools/measure_southern_ground.py."
    )


def programme_document():
    inventory = load(RECON / "1835_building_inventory.json")
    grid = load(DATA / "traces" / "vectors" / "thompson_lots.json")
    datum = load(DATA / "datum.json")
    west_recipe = load(RECON / "1835_phase2_west_wolf_point_approaches.json")
    targets = inventory["family_targets"]
    matrix = inventory["district_group_matrix"]

    for group, row in matrix.items():
        families = sum(t for f, t in targets.items() if group_of(f) == group)
        if families != row["total"]:
            raise SystemExit(f"family targets for {group} sum to {families}, "
                             f"not the group's own total of {row['total']}")

    # Derived once and used by both halves — which lot each roof holds, and, through
    # that, which block each roof stands in. Two questions, one measurement.
    taken = occupied_lots(grid, datum)
    rows = standing_roofs(grid, datum, taken)
    # …and a THIRD question, which is not the same as the first: which lots are still
    # AVAILABLE. Under the owner's 2026-08-27 clause a documented store standing at the
    # street on a declared business front does not exhaust its lot, so the lot is both
    # occupied — its roof counts against this block's headroom above — and free for the
    # frontage run. `tools/generate_block_infill.py` refuses on exactly this map, and
    # the schedule has to score against the same one or it goes back to promising a
    # block room its own generator will not build (T-A6, and the reason both halves
    # call one module).
    available = exclusive_lots(grid, datum)

    # ---- what stands ------------------------------------------------------------
    built_family: dict[str, int] = {}
    built_district: dict[str, int] = {}
    built_source: dict[str, int] = {}
    built_district_group: dict[tuple[str, str], int] = {}
    built_block: dict[str, int] = {}
    for row in rows:
        n = row["roofs_min"]
        built_source[row["source"]] = built_source.get(row["source"], 0) + n
        if not n:
            continue
        built_family[row["family"]] = built_family.get(row["family"], 0) + n
        built_district[row["district"]] = built_district.get(row["district"], 0) + n
        key = (row["district"], group_of(row["family"]))
        built_district_group[key] = built_district_group.get(key, 0) + n
        if row["block"]:
            built_block[row["block"]] = built_block.get(row["block"], 0) + n
            # A record standing in a block of another division is a defect in one of the
            # two, and it would put a roof on one district's ledger and take the headroom
            # off another's. Nothing in the dataset does this today.
            block = next(b for b in grid["blocks"] if b["id"] == row["block"])
            if district_of_block(block) != row["district"]:
                raise SystemExit(
                    f"{row['id']} is a {row['district']} record standing inside "
                    f"{row['block']}, which is {district_of_block(block)} Division ground")
    standing_min = sum(r["roofs_min"] for r in rows)
    standing_max = sum(r["roofs_max"] for r in rows)

    # ---- what remains -----------------------------------------------------------
    roof_total = inventory["targets"]["roof_total"]
    remaining_total = roof_total - standing_min
    overrun = {f: built_family.get(f, 0) - t
               for f, t in sorted(targets.items()) if built_family.get(f, 0) > t}
    remaining_family = {f: max(0, t - built_family.get(f, 0)) for f, t in targets.items()}
    # The excess has to come out of somewhere, because the authored total is the target and
    # a documented roof is not removable. It comes out one slot at a time, each from
    # whichever invented family has the most slack at that moment.
    absorbed: dict[str, int] = {}
    for _ in range(sum(overrun.values())):
        family = sorted(remaining_family, key=lambda f: (-remaining_family[f], f))[0]
        remaining_family[family] -= 1
        absorbed[family] = absorbed.get(family, 0) + 1
    if sum(remaining_family.values()) != remaining_total:
        raise SystemExit("family remainders do not sum to the programme remainder")

    remaining_district = {d: inventory["districts"][d]["target"] - built_district.get(d, 0)
                          for d in DISTRICTS}
    if sum(remaining_district.values()) != remaining_total:
        raise SystemExit("district remainders do not sum to the programme remainder")

    # A district's own mix: its group targets less what stands in it, apportioned across
    # that group's families in proportion to the global family remainder, with the same
    # absorption rule inside the district and for the same reason.
    district_families: dict[str, dict[str, int]] = {}
    district_group_remaining: dict[str, dict[str, int]] = {}
    # …and BOTH halves of what the clamp on the next line does, reported rather than
    # swallowed (T-0211). `max(0, …)` hides a division standing over one of its group
    # rows, and hiding it is not free: the ten clamped heads then sum to more than the
    # division's own remainder, by exactly the overshoot, and the loop below sheds the
    # difference out of whichever groups have the most head. So an authored row that is
    # wrong by six roofs quietly costs six roofs somewhere else in the same division, and
    # read exactly like a row that is right. tools/measure_group_district_rows.py gates
    # the overshoot; these two fields are what a reader of the ledger sees.
    district_group_overshoot: dict[str, dict[str, int]] = {}
    district_group_shed: dict[str, dict[str, int]] = {}
    for district in DISTRICTS:
        head = {g: max(0, matrix[g][district] - built_district_group.get((district, g), 0))
                for g in matrix}
        over = {g: built_district_group.get((district, g), 0) - matrix[g][district]
                for g in matrix
                if built_district_group.get((district, g), 0) > matrix[g][district]}
        if over:
            district_group_overshoot[district] = dict(sorted(over.items()))
        shed: dict[str, int] = {}
        for _ in range(max(0, sum(head.values()) - remaining_district[district])):
            group = sorted(head, key=lambda g: (-head[g], g))[0]
            head[group] -= 1
            shed[group] = shed.get(group, 0) + 1
        if shed:
            district_group_shed[district] = dict(sorted(shed.items()))
        mix: dict[str, int] = {}
        for group, count in sorted(head.items()):
            families = sorted(f for f in targets if group_of(f) == group)
            weights = [remaining_family[f] for f in families]
            if sum(weights) == 0:
                weights = [1.0] * len(families)
            for family, n in zip(families, apportion(count, weights)):
                if n:
                    mix[family] = mix.get(family, 0) + n
        if sum(mix.values()) != remaining_district[district]:
            raise SystemExit(f"{district}: family mix does not sum to its remainder")
        district_families[district] = mix
        district_group_remaining[district] = {g: n for g, n in sorted(head.items()) if n}

    # ---- where it can go --------------------------------------------------------
    units: list[dict] = []
    for block in grid["blocks"]:
        lots = len(block["lots"])
        capacity = block_capacity(lots)
        stands = built_block.get(block["id"], 0)
        free = lots - len(available.get(block["id"], ()))
        rooms = block_rooms(free, max(0, capacity - stands))
        unit = {
            "id": block["id"], "kind": "platted_block",
            "district": district_of_block(block), "bounded_by": block["bounded_by"],
            "lots": lots, "capacity_roofs": capacity, "standing_roofs": stands,
            "free_lots": free,
            "principal_room": rooms[0], "ancillary_room": rooms[1],
            "headroom": rooms[0] + rooms[1],
            "state": "open" if rooms[0] + rooms[1] > 0 else "at_capacity",
        }
        # A block the town held in common is not headroom. It reaches here with no lots
        # at all — the plat module withholds the subdivision (ROADMAP T-A16) — so the
        # arithmetic above already gives it nothing; what this does is stop it reading
        # as a block that happens to be full. `at_capacity` would be a claim that the
        # square was built out, which is the opposite of what the evidence says.
        hold = block.get("reserved")
        if hold:
            unit["kind"] = "platted_block_reserved"
            unit["state"] = "reserved"
            unit["reserved"] = hold
            unit["waiting_on"] = (
                f"nothing — {hold['name']} is not building ground. The reservation is "
                f"graded `{hold['confidence']}` and authored in {hold['authored_in']}; "
                "the roofs it would have taken are in this district's balance."
            )
        units.append(unit)
    for block in grid["omitted"]:
        if block["id"] not in STREET_CONTROL_OMISSIONS:
            continue
        lots = 8
        capacity = block_capacity(lots)
        rooms = block_rooms(lots, capacity)
        units.append({
            "id": block["id"], "kind": "platted_block_awaiting_street_control",
            "district": "west" if block["id"].endswith("clinton") else "south",
            "bounded_by": block["bounded_by"], "lots": lots,
            "capacity_roofs": capacity, "standing_roofs": 0, "free_lots": lots,
            "principal_room": rooms[0], "ancillary_room": rooms[1],
            "headroom": rooms[0] + rooms[1],
            "state": "gated",
            "waiting_on": f"{block['reason']} — the street control ROADMAP S9 records as owed. "
                          "Measured dry: tools/measure_block_gating.py carries South Water "
                          "toward this block over 25 m of ground with no wet sample on it, "
                          "so this one really is waiting on a trace. What is missing is one "
                          "control point at Market and South Water: the committed set holds "
                          "four (Lake-Canal, Lake-Market, Randolph-Canal, Kinzie-Canal) and "
                          "NONE anywhere on South Water, and Market's centreline stops at "
                          "its single control point where Lake crosses it. "
                          "AND THAT POINT CANNOT BE DERIVED, MEASURED 2026-08-27 BY T-0183. "
                          "Under the node rule in data/traces/street_control.json the two "
                          "modern successors — North Upper Wacker Drive and West Upper "
                          "Wacker Drive — share exactly two nodes, and they are lake_market's "
                          "own committed pair: Wacker changes name through a bend at the "
                          "Lake Street junction rather than crossing at South Water, so the "
                          "rule returns a plausible point 110 m south of the corner it names. "
                          "Re-run it with tools/refetch_control.py --discover "
                          "market_south_water, which now refuses the set rather than "
                          "reporting it; the reading is filed under `refused_control` in "
                          "street_control.json. So this block is NOT waiting on somebody "
                          "fetching a junction. It is waiting on an owner decision — close "
                          "South Water's west end onto Market from the 1834 sheets and the "
                          "committed bank, which is what the rest of that curve already "
                          "stands on, or return these 27 roofs to the South balance. "
                          "HE RULED FOR THE CLOSURE ON 2026-08-29, AND THE GROUND REFUSED "
                          "IT. Executed on the line as committed, the closure emits this "
                          "block as a bowtie — South Water has converged on Lake Street "
                          "before it reaches Market and their platted corridors overlap by "
                          "14.9 m there — and carried as far north as the committed "
                          "waterline allows it leaves 2.8 m of block depth at Market against "
                          "the 24.384 m one platted lot fronts. So these 27 roofs are not on "
                          "the ground the ruling was about: the block is a wedge the South "
                          "Branch pinches out at its west corner, and only its eastern two "
                          "thirds could ever carry a lot. The refusal now fires in "
                          "tools/generate_plat_lots.py --self-test rather than emitting a "
                          "4,411 m2 block with a plausible depth; the measurement is under "
                          "`refused_control.market_south_water` in street_control.json and "
                          "in docs/RESEARCH/thompson_plat_grid.md § 6.2, and what to do with "
                          "the wedge is back with the owner.",
            "lots_note": "eight lots assumed from the emitted blocks' own subdivision; the "
                         "block itself is not generated, so it has no measured geometry",
        })
    # A block the grid proposed and the ground refuses. It keeps its bounded_by and its
    # place in the schedule so the answer is visible, and it keeps NO headroom: its roofs
    # are not waiting on street control, so they go back to the district balance with the
    # rest of the ground this project has not reached. See NEVER_PLATTED_OMISSIONS above
    # for the evidence and tools/measure_block_gating.py for the measurement that gates it.
    for block in grid["omitted"]:
        if block["id"] not in NEVER_PLATTED_OMISSIONS:
            continue
        units.append({
            "id": block["id"], "kind": "platted_block_never_platted",
            "district": "west" if block["id"].endswith("clinton") else "south",
            "bounded_by": block["bounded_by"], "lots": 0,
            "capacity_roofs": 0, "standing_roofs": 0, "free_lots": 0,
            "principal_room": 0, "ancillary_room": 0, "headroom": 0,
            "state": "not_a_block",
            "waiting_on": "nothing — this pairing is an artifact of the plat grid being a "
                          "cartesian product of its east-west rows and north-south columns. "
                          "South Water Street is a south-bank street and this block is on "
                          "the West Side: measured, the two are 328 m apart with 20 of 66 "
                          "samples between them on water, which is the South Branch. The "
                          "west bank's own riverside street was West Water Street, and this "
                          "dataset records (data/traces/street_control.json, and as the "
                          "largest residual uncertainty on green_tree_tavern and "
                          "goss_cobb_saddlery) that West Water ran along the bank with "
                          "modern Canal Street a full block further west — so West Water "
                          "does not bound this block either. No street control can join "
                          "them; the roofs are in this district's balance.",
        })
    # The West recipe's own remainder, derived two ways and required to agree: its 55
    # reviewed placements less the ones already emitted as records, and the placements its
    # instantiation block holds back for standing beyond the modelled terrain box.
    # Counted by the phase each record names, not by the district it stands in. Every
    # anonymous roof in the West Division came from this one recipe until a platted block
    # parcel reached `blk_randolph_clinton`, so "generated and west" and "emitted by the
    # West recipe" were the same set — and the first West block parcel put seven roofs
    # into the district that this recipe never wrote, which read here as seven of its own
    # placements having been emitted out of order. The recipe's id IS the programme phase
    # its records carry, so the question can be asked exactly.
    west_built = sum(1 for r in rows if r.get("programme_phase") == west_recipe["id"])
    west_outer = west_recipe["roof_totals"]["all"] - west_built
    beyond_box = sum(1 for p in west_recipe["placements"]
                     if p["center_local_enu_m"][0] < WEST_INSTANTIATION_BLOCK_E)
    if west_outer != beyond_box:
        raise SystemExit(
            f"the West recipe has {west_outer} placements left to emit but {beyond_box} "
            "standing beyond its instantiation block — the parcel has been instantiated "
            "out of order and this schedule cannot say what is left")
    units.append({
        "id": "west_wolf_point_outer", "kind": "reviewed_recipe_remainder",
        "district": "west", "capacity_roofs": west_outer,
        "standing_roofs": 0, "headroom": west_outer,
        "state": "gated",
        "waiting_on": "unified terrain, hydrology, collision, flora and map coverage west "
                      "to local E -700 m; the recipe's placements are already written and "
                      "reviewed",
        "recipe": "data/reconstruction/1835_phase2_west_wolf_point_approaches.json",
    })

    southern_figures, southern_statement = southern_ground()

    for district in DISTRICTS:
        placed = sum(u["headroom"] for u in units if u["district"] == district)
        balance = remaining_district[district] - placed
        unit_id, waiting = BALANCE_UNITS[district]
        if waiting is None:
            waiting = southern_statement
        units.append({
            "id": unit_id, "kind": "district_balance", "district": district,
            "capacity_roofs": max(0, balance), "standing_roofs": 0,
            "headroom": max(0, balance),
            "state": "complete" if remaining_district[district] == 0 else "gated",
            "waiting_on": waiting,
        })
        if balance < 0:
            raise SystemExit(
                f"{district}: the named units hold {placed} roofs against a remainder of "
                f"{remaining_district[district]} — the schedule cannot over-subscribe a "
                "district, so the capacity rule or the district target has moved")

    # Deal each district's remaining families across its units, in schedule order. The
    # deal is what keeps every marginal exact: unit totals, district totals and the
    # 35-family schedule all close.
    #
    # A unit takes at most the principal and ancillary roofs it has room for (T-A6), and
    # a token it cannot take is offered to the next unit rather than dropped, so the
    # marginals still close. Before T-A6 the deal was a flat slice of `headroom` and the
    # KIND of roof in the slice was whatever the shuffle produced — which is how a block
    # with six free lots came to be scheduled seven principal roofs.
    for district in DISTRICTS:
        pool = deal(district_families[district])
        balance_id = BALANCE_UNITS[district][0]
        for unit in units:
            if unit["district"] != district:
                continue
            if unit["id"] == balance_id:
                # The district balance is the bucket for roofs no named unit can hold, so
                # it takes what is left rather than a fixed slice. A roof a block has no
                # lot for does not stop being one of the programme's roofs; it goes back to
                # waiting on coverage, a statement the ledger can make where "nowhere" is not.
                take, pool = pool, []
                unit["capacity_roofs"] = unit["headroom"] = len(take)
            else:
                take, passed = [], []
                principal_left = unit.get("principal_room", unit["headroom"])
                ancillary_left = unit.get("ancillary_room", unit["headroom"])
                for family in pool:
                    is_ancillary = group_of(family) in ANCILLARY_GROUPS
                    room = ancillary_left if is_ancillary else principal_left
                    if len(take) < unit["headroom"] and room > 0:
                        take.append(family)
                        if is_ancillary:
                            ancillary_left -= 1
                        else:
                            principal_left -= 1
                    else:
                        passed.append(family)
                pool = passed
            mix: dict[str, int] = {}
            for family in take:
                mix[family] = mix.get(family, 0) + 1
            unit["roofs"] = len(take)
            unit["families"] = {f: mix[f] for f in sorted(mix)}
            unit["principal"] = sum(n for f, n in mix.items()
                                    if group_of(f) not in ANCILLARY_GROUPS)
            unit["ancillary"] = unit["roofs"] - unit["principal"]
            # The room a unit was given and the roofs it was dealt have to agree, or the
            # next parcel to read this schedule writes a recipe its own generator refuses.
            if (unit["principal"] > unit.get("principal_room", unit["principal"])
                    or unit["ancillary"] > unit.get("ancillary_room", unit["ancillary"])):
                raise SystemExit(
                    f"{unit['id']}: dealt {unit['principal']} principal / "
                    f"{unit['ancillary']} ancillary against room for "
                    f"{unit.get('principal_room')} / {unit.get('ancillary_room')}")
        if pool:
            raise SystemExit(f"{district}: {len(pool)} roofs were not scheduled")

    # The business front, last: it re-deals what the district deal placed, so it has to run
    # after every unit's counts are settled and it must not disturb them (T-0213).
    trade_shares = trade_share_by_class()
    traffic = street_traffic()
    business_front = weight_the_business_front(units, trade_shares, traffic)
    # ...and the waterside term after it, for the same reason and in the same shape: it
    # exchanges roofs the business front has already placed, and it must not disturb any
    # count it finds (T-0316).
    waterside = waterside_families()
    waterside_term = keep_the_waterside_off_the_plat(units, waterside, trade_shares, traffic)

    schedulable = sum(u["roofs"] for u in units if u["state"] == "open")
    gated = sum(u["roofs"] for u in units if u["state"] == "gated")

    return {
        "$schema_note": "DERIVED — regenerate with tools/reconcile_665.py; tools/check.sh "
                        "re-derives it. Do not hand-edit: every number here is a function "
                        "of the committed structure records, the physical-roof "
                        "reconciliation and the authored target in "
                        "1835_building_inventory.json. THE 665 IN THE NAME IS HISTORY: the "
                        "authored total became 662 on 2026-08-27 (T-0032), when three of "
                        "family I3's six civic slots were shown to count nothing. The "
                        "filename and the tool keep their names because renaming them is "
                        "churn; the live total is always `remaining.of_target`.",
        "id": "chicago_july_1835_665_roof_programme",
        "target_date": "1835-07-01",
        "programme_id": inventory["id"],
        "derived_by": "tools/reconcile_665.py",
        "inputs": [
            "data/structures/*.json",
            "data/reconstruction/1835_building_inventory.json",
            "data/reconstruction/1835_existing_roof_reconciliation.json",
            "data/reconstruction/1835_inferred_household_programme.json",
            "data/reconstruction/1835_phase2_west_wolf_point_approaches.json",
            "data/traces/vectors/thompson_lots.json",
        ],
        "method": {
            "roof_not_record": "A structure record is not a roof. Bridges, piers, "
                               "palisades, parade grounds, yards and a building the "
                               "chronology puts outside July 1835 contribute nothing; the "
                               "physical-roof reconciliation decides, record by record.",
            "capacity": f"{ROW_UNITS_PER_LOT} principal roofs per platted lot plus "
                        f"ancillary at the programme's own "
                        f"{inventory['targets']['ancillary']}:"
                        f"{inventory['targets']['principal_functional']} ratio (T-0079, the "
                        "core density standard). The frontage rule is measured at the worst "
                        "case: the smallest lot on the committed grid carries 23.56 m, the "
                        "plat module keeps 1.5 m clear of a side line at each end of a run, "
                        "and the eighteen committed party-line units average 6.072 m wide — "
                        "so three fit on the meanest lot in the town and the fourth does "
                        "not. It replaces one roof per lot, which five of the twelve core "
                        "blocks already stood above. Capacity is a ceiling; `block_rooms` "
                        "carries the restraint.",
            "overrun": "Where evidence has put more roofs into a family than the target "
                       "allows, the excess is reported and the remainder is reduced in the "
                       "families with the most slack. A documented roof is never removed "
                       "to protect a family cap.",
            "family_mix": "An apportionment of the district's remainder across its "
                          "schedule units, not a claim about any block. Hamilton's method "
                          "throughout, so every marginal closes exactly.",
            "business_front": {
                "what": "Which of a district's principal roofs land on which platted "
                        "block is weighted by what the block FRONTS, because the "
                        "documented trade share is monotone in the committed street "
                        "hierarchy. It is a permutation of the families the district deal "
                        "already placed, among the same blocks, so no total moves: not the "
                        "target, not a district, not a family, not any block's roof count.",
                "measured": "tools/measure_frontage_fabric.py --trade — the share of "
                            "DOCUMENTED buildings carrying a trade family (C stores, F "
                            "warehouses, W workshops), by the traffic class of the street "
                            "they stand nearest. The research layer only: weighting the "
                            "schedule by what the schedule invented would ratchet.",
                "weight": "A block's weight is the mean of its four faces' class shares, "
                          "read off data/streets/1835.json. Re-class a street there and "
                          "every block on it re-weights in the same commit.",
                "trade_share_by_class": {k: {"n": v["n"], "trade": v["trade"],
                                             "share": round(v["share"], 4)}
                                         for k, v in sorted(trade_shares.items())},
                "moved": business_front,
                "ticket": "T-0213",
            },
            "waterside": {
                "what": "A family whose own crosswalk record makes water access a "
                        "precondition of the FORM is never dealt to a platted block. "
                        "tools/generate_block_infill.py authors no coordinates outside a "
                        "committed lot polygon inside four platted streets, and the wharf "
                        "and landing ground lies outside that grid, so the roof would be "
                        "deferred wherever it landed. Like the business front it is a "
                        "permutation — the roof is exchanged for a dry principal roof of "
                        "the same trade-ness on the district's own unbounded balance — so "
                        "no total moves and no unit's roof count or principal/ancillary "
                        "split changes.",
                "read_from": "data/reconstruction/1835_family_archetype_crosswalk.json — "
                             "the required_variant and variants lines say which families "
                             "are in question, and each one's own assumption_note says "
                             "whether water is required or conditional. The note is quoted "
                             "in the tool, so editing the record fails the re-derive.",
                "families": waterside,
                "swapped": waterside_term["swapped"],
                "held": waterside_term["held"],
                "ticket": "T-0316",
            },
            "naming": "A unit is named for a block only where the plat module reaches it. "
                      "Everything else is a district balance that states what it waits on.",
        },
        "standing": {
            "structure_records": len(rows),
            "physical_roofs": {"min": standing_min, "max": standing_max,
                               "range_note": "one record — the Robinson/Caldwell cabins — "
                                             "is two or three cabins in its source; the "
                                             "ledger counts the low reading."},
            "by_source": {k: built_source[k] for k in sorted(built_source)},
            "by_district": {d: built_district.get(d, 0) for d in DISTRICTS},
            "by_group": {g: sum(built_district_group.get((d, g), 0) for d in DISTRICTS)
                         for g in matrix},
            "by_family": {f: built_family.get(f, 0) for f in sorted(targets)},
            "records_contributing_no_roof": sorted(r["id"] for r in rows if not r["roofs_min"]),
        },
        "remaining": {
            "roofs": remaining_total,
            "of_target": roof_total,
            "by_district": remaining_district,
            "by_district_group": district_group_remaining,
            "by_family": {f: remaining_family[f] for f in sorted(remaining_family)},
            "by_district_family": district_families,
            "family_targets_already_exceeded": overrun,
            "absorbed_from": absorbed,
            # T-0211. The same pair of facts one level up, by division and group: what
            # stands ABOVE a group row, and which groups paid for it. Declared and
            # ratcheted in tools/measure_group_district_rows.py.
            "district_group_rows_overshot": district_group_overshoot,
            "district_group_slots_shed": district_group_shed,
        },
        "coverage": {
            "schedulable_on_committed_ground": schedulable,
            "gated_on_coverage": gated,
            "statement": f"{schedulable} of the {remaining_total} remaining roofs stand on "
                         "ground this project has already surveyed, platted and modelled. "
                         f"The other {gated} have nowhere to go until street control, "
                         "terrain and hydrology reach them. The binding constraint on the "
                         f"{roof_total}-roof programme is coverage, not recipes.",
            "platted_lots": sum(len(b["lots"]) for b in grid["blocks"]),
            "blocks_named": sum(1 for u in units if u["kind"].startswith("platted_block")),
            # T-0026. The South is the largest of the three gated balances and the one the
            # lane was opened to widen; these are the figures that say it cannot be widened
            # by a rule. Carried here so a scheduler reads them without re-running a
            # command, and held to the ground by tools/measure_southern_ground.py --gate.
            "southern_ground": southern_figures,
        },
        "schedule": units,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed programme is not what the dataset and "
                             "the target re-derive")
    args = parser.parse_args()
    programme = programme_document()
    text = json.dumps(programme, indent=1, ensure_ascii=False) + "\n"
    if args.check:
        if not OUT_PATH.exists():
            print(f"665 PROGRAMME DRIFT\n  - {OUT_PATH.relative_to(ROOT)} is missing")
            return 1
        if OUT_PATH.read_text(encoding="utf-8") != text:
            print("665 PROGRAMME DRIFT\n  - data/reconstruction/"
                  "1835_665_roof_programme.json is not what the committed structure "
                  "records, the roof reconciliation and the authored target re-derive. "
                  "Re-run tools/reconcile_665.py and commit the result alongside the "
                  "records that moved it.")
            return 1
    else:
        OUT_PATH.write_text(text, encoding="utf-8")
    print(f"{'verified' if args.check else 'generated'} the "
          f"{programme['remaining']['of_target']}-roof programme: "
          f"{programme['standing']['physical_roofs']['min']} standing, "
          f"{programme['remaining']['roofs']} remaining, "
          f"{programme['coverage']['schedulable_on_committed_ground']} of them on ground "
          "the project has coverage for")
    front = programme["method"]["business_front"]
    shares = ", ".join(f"{k} {v['share']:.4f}"
                       for k, v in front["trade_share_by_class"].items())
    moved = ", ".join(f"{row['district']} re-deals {row['trade_roofs']} trade roof(s) over "
                      f"{row['blocks']} platted block(s)" for row in front["moved"])
    print(f"  business front (T-0213): documented trade share {shares} — "
          f"{moved or 'no district has a platted block to weight'}")
    water = programme["method"]["waterside"]
    swaps = ", ".join(f"{row['family']} {row['from']} -> {row['to']} for {row['for']}"
                      for row in water["swapped"])
    families = ", ".join(sorted(water["families"]))
    print(f"  waterside (T-0316): {families} require water — "
          f"{swaps or 'no platted block was dealt one'}"
          + (f"; {len(water['held'])} HELD on the plat" if water["held"] else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
