#!/usr/bin/env python3
"""ONE LIST OF THE NAMES A ROOF-ID SWEEP MAY NOT MOVE. T-1499.

    tools/roof_id_pins.py --list       every pin, its category and its reason
    tools/roof_id_pins.py --check      the two sweeps agree, and every pin is earned
    tools/roof_id_pins.py --self-test  the guards, fired on fixtures

TWO TOOLS SWEEP THE SAME SURFACE. `tools/migrate_roof_ids.py` carries the phase-one
South parcel's ids across the committed tree; `tools/execute_roof_redeal.py
--check-migration` asks of the North Division parcel's whether any committed file
still names one. Both put the same question to the same file --- may this one keep
the old name? --- and until this module each kept its own answer: `KEEPS_THE_OLD_NAME`
in the first and `MIGRATION_PINNED` in the second, with overlapping contents and the
same reasoning written out twice.

WHY THAT MATTERED MORE THAN THE DUPLICATION. The two lists could DISAGREE, and a
disagreement was silent in the direction that hurts. A file pinned in one sweep and
not the other is red on whichever gate happens to run, and a file that should be
stale but is pinned in both is a dangling id nothing catches --- and a dangling id in
an enclosure or a signage run reads as a record about a building the scene does not
draw. The only thing keeping the two in agreement was that somebody edited both, and
twice nobody did: `tools/measure_roof_id_migration.py` had to be added to the first
list on #1588 and, an hour later and for word-for-word the same reason, to the second
on #1596. Each addition was made because a gate went red, not because anybody noticed
the other list.

THE DIVERGENCES THIS MODULE CLOSED, measured on the committed tree on 2026-09-21.
Six, and every one of them was a file one sweep would have rewritten and the other
would have refused to:

  * `tickets/`, `patches/`, `*.log` and `*.patch` --- pinned by the executor, not by
    the migrator. This is the divergence T-1499 demonstrated while it was being
    FILED: its own first draft quoted a migrated id, as the executor's prose does,
    and one sweep accepted the file while the other refused it, on the same tree, for
    the same text.
  * `tools/migrate_roof_ids.py`, `data/reconstruction/1835_phase2_west_wolf_point_approaches.json`
    and `renderers/web/js/changelog.js` --- pinned by the migrator, not by the
    executor.
  * `docs/unreal/prototype/` --- pinned whole by the executor, and by one named file
    inside it by the migrator.
  * `data/reconstruction/1835_north_division_initial_parcel.json` --- not in either
    LIST. The executor skipped it inline, two branches apart from the list, with its
    reason in a trailing comment; the migrator did not know about it at all. It is a
    pin, and it is written down here as one.

THE UNION IS THE CONSOLIDATION, AND IT MOVES NOTHING. Every one of those six is a
file added to the pinned set of the sweep that lacked it, so each sweep now exempts
MORE than it did, never less. A wider exemption can only turn a red gate green; it
cannot turn a green one red, and it cannot rewrite a name that was being rewritten
before. That is why this is a consolidation rather than a re-migration, and why no
committed record changes as a result of it.

WHAT THE GATE ASKS, and each of the four is a silence the old arrangement had:

  1. THE TWO SWEEPS AGREE. Both tools are imported and asked their own verdict for
     every file in the source tree, and an answer that differs from this module's is
     a red gate. A future run that re-introduces a private list inside one sweep does
     not quietly diverge; it fails here.
  2. NO PIN IS DEAD. A pin that matches no committed path is a typo or a file that
     has moved, and either way it is an exemption nobody can see the effect of.
  3. EVERY PIN IS EARNED. A pin declares a CATEGORY, and a category declares the
     scope of the tree a name of that kind may live in. Every committed file a pin
     matches must lie inside its category's scope --- so pinning `data/sidecars/`
     as a dated receipt is refused, because a sidecar is not under a receipts path.
     Adding a pin that is none of the recognised kinds therefore costs an argument:
     a new category, written down and reviewable, rather than one more line in a
     tuple.
  4. A RE-DERIVED FILE IS NEVER PINNED. `REDERIVED` is a different idea and it must
     stay one. Those files name every migrated roof and they are the measurement of
     whether the migration worked; a rewritten ledger would agree with the migration
     by construction, so they are REGENERATED by the tool that writes them. Pinning
     one would mean "leave the old name standing", which is the opposite instruction.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TICKET = "T-1499"

# Not the source tree: a build output, a dependency, and the published mirror. No
# sweep descends into these, and the agreement below is not asked about them.
NOT_THE_SOURCE_TREE = (".git/", "node_modules/", "site/")


@dataclass(frozen=True)
class Category:
    """A KIND of written name that is true as written, and where one may live.

    `scope` is the answer to "where in this tree could a name of this kind be?" and
    it is what makes a pin arguable rather than assertable: a pin may only reach
    files inside its category's scope, so a new exemption has to say what kind of
    thing it is and be right about it.
    """

    key: str
    name: str
    why: str
    scope: tuple[str, ...]


@dataclass(frozen=True)
class Pin:
    """One path prefix (or `*<suffix>`) the sweeps leave alone, and its reason."""

    match: str
    category: str
    reason: str


# The categories both lists already recognised, kept and named. The words are theirs.
CATEGORIES = (
    Category(
        "receipt", "a dated receipt",
        "records what one import run on one machine actually loaded, on the day it "
        "loaded it; rewriting the ids in a receipt would make it a record of an "
        "import that never happened, and nothing gates it against the live records",
        ("renderers/unreal/receipts/",),
    ),
    Category(
        "import_report", "an import report",
        "the report a signed build produced, true of the tree that build ran "
        "against and of no other",
        ("docs/unreal/prototype/",),
    ),
    Category(
        "ticket", "a ticket's account of a day",
        "a ticket records what was found on a day and is TRUE as written; rewriting "
        "a dated measurement so that it agrees with today is falsifying it",
        ("tickets/",),
    ),
    Category(
        "transcript", "a transcript or a patch",
        "says what one named moment looked like, the same kind of thing as a "
        "receipt; migrating an id inside one would make it say something that "
        "never happened",
        ("patches/", "*.log", "*.patch"),
    ),
    Category(
        "yard_group", "a yard group named for a roof",
        "a yard is named for the roof it stands behind, so the name is a reference "
        "to the building and not a record of a past moment",
        ("data/yard/",),
    ),
    Category(
        "recipe_record", "a recipe's record of what a roof was",
        "a parcel recipe keeps the block that says what each placement carried "
        "BEFORE the verdict was carried out; that block is the record of the move, "
        "and it is re-derived by the executor in any case, so a textual rewrite "
        "here would not survive the next run of it",
        ("data/reconstruction/",),
    ),
    Category(
        "rename_prose", "prose about the rename itself",
        "explains the migration by naming the id that moved and the id it moved to; "
        "rewriting the first half of \"the old id becomes the new one\" makes the "
        "sentence say nothing",
        ("renderers/web/js/changelog.js", "docs/"),
    ),
    Category(
        "fixture", "a self-test fixture",
        "passes an old id to the function under test as the worked example; "
        "rewriting the fixture leaves the test asserting that an already-migrated "
        "id migrates to itself, which is true of every id and a test of nothing",
        ("tools/",),
    ),
    Category(
        "sweeping_tool", "the sweeping tool's own file",
        "the sweep's own prose about the ids it moves is an argument to a function "
        "and an explanation of a surface, never a claim that a record still stands "
        "under the old name",
        ("tools/",),
    ),
)

CATEGORY = {c.key: c for c in CATEGORIES}

# THE ONE LIST. Each entry carries its own reason; the category carries the reason
# the KIND is true as written, and the two are not the same sentence.
PINS = (
    Pin("renderers/unreal/receipts/", "receipt",
        "a signed build pinned to a scene_source_commit, naming the roofs it loaded "
        "by the id they had that day"),
    Pin("docs/unreal/prototype/", "import_report",
        "the import report that build produced, including the 400 kB engine log the "
        "migrator cannot decode as UTF-8 and must not promise to have moved"),
    Pin("tickets/", "ticket",
        "a ticket's account of what it found, on the day it found it"),
    Pin("patches/", "transcript",
        "a patch against a tree as that tree stood"),
    Pin("*.log", "transcript",
        "a transcript of a run"),
    Pin("*.patch", "transcript",
        "a patch against a tree as that tree stood"),
    Pin("tools/execute_roof_redeal.py", "sweeping_tool",
        "one of the two sweeps; its docstring and its self-test use a moving id as "
        "the worked example of an id that moves"),
    Pin("tools/migrate_roof_ids.py", "sweeping_tool",
        "the other sweep, for the same reason"),
    Pin("tools/roof_id_pins.py", "sweeping_tool",
        "this file — the list the two sweeps read, and the third place their prose "
        "about a rename can live"),
    Pin("tools/measure_roof_id_migration.py", "fixture",
        "both reasons at once (T-1483): its docstring explains the surface by "
        "naming a move, and its self-test passes the old id to new_id() as the "
        "worked example of an id keeping its sequence"),
    Pin("data/reconstruction/1835_phase2_west_wolf_point_approaches.json",
        "recipe_record",
        "the West parcel's `redealt` block, which names the id each refamilied "
        "placement moved from"),
    Pin("data/reconstruction/1835_north_division_initial_parcel.json",
        "recipe_record",
        "the North parcel's `migrated` block, which records what each roof WAS; "
        "this was the executor's inline skip and belongs in the list with the rest"),
    Pin("renderers/web/js/changelog.js", "rename_prose",
        "the entry that told a visitor which roofs were renamed and to what"),
)

# DERIVED FROM THE ROOFS THEMSELVES, so they cannot be rewritten into agreement.
# This is NOT the pinned list and the gate below refuses any overlap: a pinned file
# keeps the old name, and a re-derived one is regenerated until it holds the new.
REDERIVED = (
    "data/reconstruction/1835_roof_redeal.json",
    "docs/RESEARCH/1835_anonymous_roof_redeal.md",
    "docs/RESEARCH/1835_roof_redeal_execution.md",
)


# --------------------------------------------------------------------------
# the question both sweeps ask
# --------------------------------------------------------------------------

def matches(rule: str, rel: str) -> bool:
    """`*<suffix>` matches on the extension, anything else is a path prefix.

    Prefix and not equality, because every pin that names a directory means the
    whole of it — which is also the semantics the two `str.startswith(tuple)` calls
    this module replaces already had.
    """
    if rule.startswith("*"):
        return rel.lower().endswith(rule[1:].lower())
    return rel.startswith(rule)


def pin_for(rel: str) -> Pin | None:
    """The pin that exempts this path, or None. The first match wins and they are
    disjoint in practice; `--check` does not depend on which one answers."""
    for pin in PINS:
        if matches(pin.match, rel):
            return pin
    return None


def is_pinned(rel: str) -> bool:
    """May this file keep a roof id that has been migrated? The whole question."""
    return pin_for(rel) is not None


def source_files() -> list[str]:
    """Every committed path a sweep could reach, as a repo-relative posix string."""
    out = []
    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        rel = path.relative_to(ROOT).as_posix()
        if rel.startswith(NOT_THE_SOURCE_TREE):
            continue
        out.append(rel)
    return sorted(out)


# --------------------------------------------------------------------------
# the gate
# --------------------------------------------------------------------------

def earned(tree: list[str]) -> list[str]:
    """Every committed file a pin reaches lies inside its category's scope."""
    faults = []
    for pin in PINS:
        cat = CATEGORY.get(pin.category)
        if cat is None:
            faults.append(f"{pin.match} claims the category {pin.category!r}, "
                          f"which is not one this module recognises")
            continue
        reached = [rel for rel in tree if matches(pin.match, rel)]
        if not reached:
            faults.append(f"{pin.match} is a dead pin — no committed file matches "
                          f"it, so its exemption cannot be seen to do anything")
            continue
        outside = [rel for rel in reached
                   if not any(matches(s, rel) for s in cat.scope)]
        if outside:
            faults.append(
                f"{pin.match} is pinned as {cat.name!r}, whose scope is "
                f"{', '.join(cat.scope)} — but it reaches {len(outside)} file(s) "
                f"outside it, the first being {outside[0]}")
    return faults


def disjoint() -> list[str]:
    """A re-derived file is never pinned."""
    return [f"{rel} is both pinned and re-derived — a pin says 'keep the old name' "
            f"and a re-derivation says 'regenerate until it holds the new one'"
            for rel in REDERIVED if is_pinned(rel)]


def agree(tree: list[str]) -> list[str]:
    """Both sweeps return this module's verdict, for every file in the tree.

    Imported here and not at module scope: each sweep imports this module, so the
    import is deferred to the moment the question is actually asked.
    """
    sys.path.insert(0, str(ROOT / "tools"))
    import execute_roof_redeal  # noqa: PLC0415
    import migrate_roof_ids  # noqa: PLC0415

    sweeps = (("tools/migrate_roof_ids.py", migrate_roof_ids.keeps_the_old_name),
              ("tools/execute_roof_redeal.py", execute_roof_redeal.keeps_the_old_name))
    faults = []
    for name, verdict in sweeps:
        differs = [rel for rel in tree if bool(verdict(rel)) != is_pinned(rel)]
        if differs:
            faults.append(f"{name} disagrees with the shared list on "
                          f"{len(differs)} file(s), the first being {differs[0]} "
                          f"(it says {bool(verdict(differs[0]))}, the list says "
                          f"{is_pinned(differs[0])})")
    return faults


def shared():
    """The module object the two sweeps actually read.

    Run as a script this file is `__main__` and `roof_id_pins` is a SECOND import of
    the same source, with its own `PINS`. A mutation test that bent `__main__`'s copy
    would be asking the sweeps about a list they have never seen — and would pass
    while proving nothing — so the self-test below bends this one.
    """
    sys.path.insert(0, str(ROOT / "tools"))
    import roof_id_pins  # noqa: PLC0415
    return roof_id_pins


def check() -> int:
    tree = source_files()
    faults = agree(tree) + earned(tree) + disjoint()
    if faults:
        print("ROOF-ID PIN LIST")
        for f in faults:
            print(f"  - {f}")
        return 1
    empty = [c.name for c in CATEGORIES
             if not any(p.category == c.key for p in PINS)]
    print(f"{len(PINS)} pin(s) in {len(CATEGORIES)} category(ies), every one earned, "
          f"and both sweeps return the same verdict for all {len(tree)} source files")
    for name in empty:
        print(f"  recognised and unused today: {name}")
    return 0


def show() -> int:
    for cat in CATEGORIES:
        pins = [p for p in PINS if p.category == cat.key]
        print(f"{cat.name} — {cat.why}")
        print(f"    scope: {', '.join(cat.scope)}")
        for pin in pins:
            print(f"  * {pin.match}")
            print(f"      {pin.reason}")
        if not pins:
            print("  * (no pin today — the sweeps move a name of this kind with the "
                  "roof rather than pinning it)")
        print()
    return 0


def self_test() -> int:
    mod = shared()
    fired = 0

    assert mod.matches("tickets/", "tickets/T-0001-a.md")
    assert not mod.matches("tickets/", "tools/tickets_report.py")
    assert mod.matches("*.log", "docs/unreal/prototype/build.LOG")
    assert not mod.matches("*.log", "docs/logbook.md")
    fired += 1

    # THE DIVERGENCE THAT FILED THIS TICKET, asserted rather than remembered: a
    # ticket file naming a migrated id is pinned, and it is pinned for BOTH sweeps
    # because there is now only one answer to give.
    assert mod.is_pinned("tickets/T-1499-two-tools.md")
    assert mod.is_pinned("renderers/web/js/changelog.js")
    assert mod.is_pinned("data/reconstruction/1835_north_division_initial_parcel.json")
    assert not mod.is_pinned("data/sidecars/1835/index.json")
    fired += 1

    tree = ["tickets/T-0001-a.md", "data/sidecars/1835/index.json",
            "renderers/unreal/receipts/r.json"]
    assert not mod.agree(tree)
    fired += 1

    keep = mod.PINS

    # MUTATION ONE — remove an entry, and BOTH sweeps report the same file. The
    # agreement holds in the changed state too, which is the property that matters:
    # the two sweeps cannot diverge, not even when the list is wrong.
    try:
        mod.PINS = tuple(p for p in keep if p.match != "tickets/")
        assert not mod.is_pinned("tickets/T-0001-a.md")
        assert not mod.agree(tree), mod.agree(tree)
    finally:
        mod.PINS = keep
    assert mod.is_pinned("tickets/T-0001-a.md")
    fired += 1

    # MUTATION TWO — pin a file that should be stale, and the gate refuses it. A
    # sidecar is compiled from the structure records: it holds a live pointer at a
    # roof, and it is not a receipt of anything.
    tree_now = mod.source_files()
    try:
        mod.PINS = keep + (mod.Pin("data/sidecars/", "receipt", "it is not"),)
        faults = mod.earned(tree_now)
        assert any("data/sidecars/" in f and "dated receipt" in f for f in faults), faults
    finally:
        mod.PINS = keep
    assert not mod.earned(tree_now)
    fired += 1

    # A pin that names nothing is an exemption nobody can see the effect of.
    try:
        mod.PINS = keep + (mod.Pin("data/reconstruction/no_such_recipe.json",
                                   "recipe_record", "it does not exist"),)
        assert any("dead pin" in f for f in mod.earned(tree_now))
    finally:
        mod.PINS = keep
    fired += 1

    # A category nothing recognises is refused rather than silently ignored.
    try:
        mod.PINS = keep + (mod.Pin("docs/", "not_a_category", "invented"),)
        assert any("not one this module recognises" in f
                   for f in mod.earned(tree_now))
    finally:
        mod.PINS = keep
    fired += 1

    # THE THIRD IDEA STAYS A THIRD IDEA.
    try:
        mod.PINS = keep + (mod.Pin(mod.REDERIVED[0], "recipe_record",
                                   "it is re-derived"),)
        assert mod.disjoint(), "a re-derived file was pinned and nothing said so"
    finally:
        mod.PINS = keep
    assert not mod.disjoint()
    fired += 1

    print(f"roof_id_pins self-test: {fired} guard(s) fired")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()
    if args.self_test:
        return self_test()
    if args.check:
        return check()
    return show()


if __name__ == "__main__":
    raise SystemExit(main())
