#!/usr/bin/env python3
"""THE ONE-LETTER CARD PAIRS, WEIGHED BY MACHINE SO THEY CAN BE RULED IN ONE PASS.

T-1291, which folded T-1027's epic and four satellites into one ticket on the owner's
instruction of 2026-09-17: *the research spend is a CHECK before reconstruction, not a
programme.* Every pair in that epic asks the same question — ARE THESE TWO READINGS ONE
PERSON? — and the rulings already landed (C9, C12, C14, D5, D6, D7 in
data/residents/card_merge_rulings.json) answer it from the same four facts each time:

  1. IS EITHER CARD AN ANCHOR? A trade, a dwelling, a premises, a research finding —
     the thing a bare reading is allowed to attach to (`consolidate_town_cards.anchored`).
  2. IS EITHER SPELLING POPULATED AT THIS TOWN? Two surnames that each carry several
     live bearers is the case a one-letter distance is WEAKEST in — the Paine/Payne
     argument, and T-1001's measurement over the land register's 427 purchaser spellings.
  3. WHAT DOES THE CORPUS SET? Two censuses, because the two answer different questions.
     A word-boundary census of each SPELLING over every deposited transcription, so "set
     exactly once in the whole corpus" is a counted claim rather than an impression — and
     the READING INDEX of data/research/residents/identity_master.json, which is what the
     project actually asserts the page says. The raw transcriptions matter because they
     are the page; the reading index matters more because the post-office columns are OCR
     wreckage ("Allin, Rach»", "allin, Roebant") and a grep over them under-counts a name
     the project has read correctly. Where the two disagree, the reading index governs
     and the raw census is the reminder that somebody should look at the image.
  4. IS ANY ONE TITLE CAUGHT SETTING BOTH SPELLINGS OF THIS MAN'S NAME? That is C9's
     and C10's demonstration, and its ABSENCE is precisely what D6 and D7 rest on. The
     test is deliberately narrow: a volume that prints both surnames SOMEWHERE proves
     nothing, because a book naming a Barre and a Barry is naming two families. So the
     census also counts each card's FULL NAME as printed — the surname within a short
     window of its own forename or initial, in either order — and only a title that sets
     both of THOSE is reported as a candidate for C9's demonstration. Even then it is a
     candidate and not the demonstration: a human still reads the line, because two
     namesakes in one volume look identical to a window.

Those four were gathered by hand, one cluster per run, which is what made T-1027 an epic
of 68 rows. This module gathers them for every pair at once. It DOES NOT RULE: no output
of this file merges, folds or regrades anything. It prints the table a ruling is written
from, and it holds the gate that keeps the pool from silting up again.

    tools/rule_fuzzy_card_pairs.py                 the coverage count
    tools/rule_fuzzy_card_pairs.py --evidence      the four facts, per unruled pair
    tools/rule_fuzzy_card_pairs.py --triage        one line per pair, and the rule its
                                                   conditions POINT AT — a proposal for a
                                                   human to adopt or reject, never a ruling
    tools/rule_fuzzy_card_pairs.py --check         red while a pair carries no ruling
    tools/rule_fuzzy_card_pairs.py --self-test     the pair-level coverage test

WHY --check IS STRICTER THAN THE POOL IT REPLACES. T-1027 counted a pair as `ruled` when
EITHER card stood in some ruled cluster, and said so in its own table: "it does not mean
the PAIR is ruled". A ruling that weighs `wright_j` against two Wrights says nothing
about `wight_j_f`. This gate asks for a ruling that names BOTH cards of the pair, which
is the only thing that answers the question the pair asks.
"""

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESEARCH = ROOT / "data" / "research"

sys.path.insert(0, str(Path(__file__).resolve().parent))
import consolidate_town_cards as ctc  # noqa: E402
import measure_card_fuzzy_candidates as fuzzy  # noqa: E402

IDENTITY_MASTER = RESEARCH / "residents" / "identity_master.json"


def reading_index() -> tuple[dict, dict]:
    """person_id -> its identity row, and surname -> the identities bearing it.

    The identity master is GENERATED by consolidate_resident_evidence.py --build and is
    the project's own answer to "what does every source say this person's name is". A
    pair is weighed against it rather than against a grep because it carries the reading,
    its source, its locator and the date the reading describes."""
    doc = json.loads(IDENTITY_MASTER.read_text(encoding="utf-8"))
    by_person, by_surname = {}, defaultdict(list)
    for row in doc.get("identities", []):
        for pid in [row.get("canonical_person_id"), *(row.get("town_person_ids") or [])]:
            if pid:
                by_person[pid] = row
        by_surname[row.get("surname") or ""].append(row)
    return by_person, dict(by_surname)


def pair_ruling(pair: dict, rulings: dict) -> dict | None:
    """The ruling that names BOTH cards of this pair, or None.

    A merge ruling names its survivor and everything folded onto it; a distinct or
    undecided ruling names its members. Either counts, because either is an answer to
    the question the pair asks. A ruling that names one card and not the other is not.
    """
    want = {c["person"] for c in pair["cards"]}
    for cluster in rulings.get("clusters", []):
        for ruling in cluster.get("rulings", []):
            if ruling["state"] == "merge":
                named = {ruling["survivor"], *(ruling.get("folded") or [])}
            else:
                named = set(ruling.get("members") or [])
            if want <= named:
                return dict(ruling, cluster=cluster["id"])
    return None


def name_pattern(surname: str, forename: str) -> re.Pattern:
    """The card's name as a printer might set it: surname and forename within a short
    window of each other, in either order, so 'Allin, Richard' and 'Richard Allin' both
    count and 'Richard' three paragraphs from an Allin does not. A one-letter forename
    is matched as an initial, optional point, which is how the lists print it."""
    fore = (re.escape(forename) + r"\.?" if len(forename) == 1
            else re.escape(forename) + r"\w{0,2}")
    sur = re.escape(surname)
    return re.compile(r"\b(?:%s\b[\s,.;:]{1,4}%s|%s\b[\s,.;:]{1,4}%s)\b"
                      % (sur, fore, fore, sur), re.I)


def corpus_census(words: set, names: dict) -> tuple[dict, dict]:
    """One pass over every deposited transcription, returning two censuses:

      the SURNAME census   word -> {file: count}, word-boundary, case-folded
      the NAME census      key  -> {file: count}, the surname beside its own forename

    One pass and not two because the corpus is 84 MB and fifty spellings."""
    pats = {w: re.compile(r"\b%s\b" % re.escape(w), re.I) for w in words}
    npats = {k: name_pattern(*v) for k, v in names.items()}
    out = {w: defaultdict(int) for w in words}
    nout = {k: defaultdict(int) for k in names}
    for path in sorted(RESEARCH.glob("*/text/*.txt")):
        text = path.read_text(encoding="utf-8", errors="replace")
        low = text.lower()
        rel = str(path.relative_to(ROOT))
        for word, pat in pats.items():
            if word.lower() not in low:
                continue
            hits = len(pat.findall(text))
            if hits:
                out[word][rel] = hits
        for key, pat in npats.items():
            if names[key][0].lower() not in low:
                continue
            hits = len(pat.findall(text))
            if hits:
                nout[key][rel] = hits
    return ({w: dict(v) for w, v in out.items()},
            {k: dict(v) for k, v in nout.items()})


def surname_of(person_id: str, name: str) -> str:
    parsed = ctc.forename_tokens(name)
    return parsed[0] if parsed else ""


def town_bearers(town: list) -> dict:
    """surname as the candidate test buckets it -> the cards that bear it."""
    out = defaultdict(list)
    for row in town:
        parsed = ctc.forename_tokens(row["name"])
        if parsed:
            out[parsed[0]].append(row)
    return out


def evidence(root: Path | None = None) -> dict:
    m = fuzzy.measure(root)
    rulings = ctc.load_rulings()
    town = ctc.read_town(root)
    by_person = {r["person"]: r for r in town}
    bearers = town_bearers(town)

    for pair in m["added"]:
        pair["pair_ruling"] = pair_ruling(pair, rulings)

    unruled = [p for p in m["added"] if not p["pair_ruling"]]
    words, names = set(), {}
    for pair in unruled:
        for card in pair["cards"]:
            row = by_person.get(card["person"])
            if not row:
                continue
            parsed = ctc.forename_tokens(row["name"])
            if not parsed:
                continue
            words.add(parsed[0])
            if parsed[1]:
                names[card["person"]] = (parsed[0], parsed[1][0])
    words.discard("")
    census, name_census = corpus_census(words, names)
    ident_by_person, ident_by_surname = reading_index()

    for pair in unruled:
        for card in pair["cards"]:
            row = by_person.get(card["person"])
            if not row:
                card["missing"] = True
                continue
            person, doc = row["record"], row["doc"]
            sur = surname_of(card["person"], row["name"])
            files = census.get(sur, {})
            card.update({
                "surname": sur,
                "anchored": ctc.anchored(person, doc),
                "source_pass": doc.get("source_pass"),
                "occupation": (person.get("occupation") or {}).get("value"),
                "sources": person.get("sources") or [],
                "town_bearers": sorted(r["person"] for r in bearers.get(sur, [])),
                "corpus_settings": sum(files.values()),
                "corpus_files": len(files),
                "corpus_where": dict(sorted(files.items(), key=lambda kv: -kv[1])[:6]),
                "name_settings": sum(name_census.get(card["person"], {}).values()),
                "name_where": dict(sorted(name_census.get(card["person"], {}).items(),
                                          key=lambda kv: -kv[1])[:6]),
            })
            ident = ident_by_person.get(card["person"]) or {}
            card["readings"] = [
                {"source": ap.get("source_id"), "locator": ap.get("locator"),
                 "date": ap.get("describes_date"), "as_read": ap.get("as_read"),
                 "domain": ap.get("domain")}
                for ap in ident.get("appearances") or []]
            card["corpus_bearers_of_the_spelling"] = sorted(
                r["id"] for r in ident_by_surname.get(card.get("surname") or "", []))
        a, b = pair["cards"]
        wa = census.get(a.get("surname"), {})
        wb = census.get(b.get("surname"), {})
        pair["files_setting_both"] = sorted(set(wa) & set(wb))
        pair["titles_setting_both_names"] = sorted(
            set(name_census.get(a["person"], {})) & set(name_census.get(b["person"], {})))
        ra = {(r["source"], r["locator"]) for r in a.get("readings") or []}
        rb = {(r["source"], r["locator"]) for r in b.get("readings") or []}
        pair["one_locator_setting_both"] = sorted(
            "%s @ %s" % (src, loc) for src, loc in ra & rb if src or loc)
        pair["one_title_setting_both"] = sorted(
            {r["source"] for r in a.get("readings") or [] if r["source"]}
            & {r["source"] for r in b.get("readings") or [] if r["source"]})
        pair["shared_sources"] = sorted(set(a.get("sources") or [])
                                        & set(b.get("sources") or []))
    m["unruled"] = unruled
    return m


# The post office's returns of letters uncalled-for are this corpus's one SERIAL closed
# roll — one office re-compiling and re-publishing the same kind of list on a schedule —
# which is the corpus D6 was written for. The poll, tax and muster lists are ONE-OFF
# closed rolls, which is D5's and C12's corpus. A card's source_pass says which it came
# through, and the reading locators say which return.
SERIAL_ROLL_PASSES = {"letter_list"}


def points_at(pair: dict) -> tuple[str, str]:
    """The rule this pair's measured conditions POINT AT, and why in one clause.

    THIS IS NOT A RULING and nothing in this module acts on it. The rules it names are
    the landed ones in data/residents/card_merge_rulings.json; what this function does is
    check their stated conditions against the four facts gathered above, so a pass over
    forty pairs starts from the same reading of the evidence a pass over one would. A
    human adopts it, narrows it, or throws it away at the page.
    """
    a, b = pair["cards"]
    if any("[" in (c.get("name") or "") for c in (a, b)):
        return "R5", "a bracketed reading — a garbled name cannot be tested (T-0695)"
    if pair["one_locator_setting_both"]:
        return "D5", ("one locator enters both readings as separate entries: "
                      + ", ".join(pair["one_locator_setting_both"]))
    if pair["titles_setting_both_names"]:
        return "C9?", ("a deposited text sets both names — read the line before folding: "
                       + ", ".join(pair["titles_setting_both_names"]))
    anchors = [c["person"] for c in (a, b) if c.get("anchored")]
    both_serial = all((c.get("source_pass") in SERIAL_ROLL_PASSES) for c in (a, b))
    if both_serial:
        return "D6", ("both cards stand only on the post office's serial returns and no "
                      "return sets both spellings")
    if pair["folds"] == "surname":
        why = "no title reached sets both spellings of this man's name"
        if anchors:
            why += "; the anchor is %s, and a bare reading beside an anchor is C9's shape" % (
                ", ".join(anchors))
        return "D7", why
    return "D8?", ("C10's shape on the forename and no title sets both spellings — the "
                   "refusal D7 makes on the surname, which no landed rule yet makes here")


def triage() -> int:
    m = evidence()
    for pair in m["unruled"]:
        a, b = pair["cards"]
        rule, why = points_at(pair)
        print("%-5s %-22s %-22s %-8s %s"
              % (rule, a["person"], b["person"], pair["folds"], why))
    print("\n   %d unruled pair(s). The rule named is a PROPOSAL, not a ruling."
          % len(m["unruled"]))
    return 0


def report(detail: bool) -> int:
    m = evidence()
    total = m["pairs_a_one_letter_test_would_add"]
    ruled = sum(1 for p in m["added"] if p["pair_ruling"])
    print("   %5d pairs one letter of slack proposes beyond the exact test" % total)
    print("   %5d of them carry a ruling that names BOTH cards" % ruled)
    print("   %5d do not" % (total - ruled))
    if not detail:
        print("   tools/rule_fuzzy_card_pairs.py --evidence weighs every unruled pair")
        return 0
    for pair in m["unruled"]:
        a, b = pair["cards"]
        print("\n=== %s / %s   (folds the %s)" % (a["person"], b["person"], pair["folds"]))
        for card in (a, b):
            print("  %-22s %-24r anchor=%-5s pass=%-11s trade=%s"
                  % (card["person"], card["name"], card.get("anchored"),
                     card.get("source_pass"), card.get("occupation")))
            print("      surname %r set %d time(s) in %d deposited text(s); town bears %s"
                  % (card.get("surname"), card.get("corpus_settings", 0),
                     card.get("corpus_files", 0),
                     ", ".join(card.get("town_bearers") or []) or "nothing"))
            print("      THIS NAME set %d time(s) in %d text(s): %s"
                  % (card.get("name_settings", 0), len(card.get("name_where") or {}),
                     ", ".join(card.get("name_where") or {}) or "none"))
            for path, n in (card.get("corpus_where") or {}).items():
                print("        %4d  %s" % (n, path))
            for r in card.get("readings") or []:
                print("        READ %-30r %-28s %-12s %s"
                      % (r["as_read"], r["source"] or "-", r["date"] or "-",
                         r["locator"] or "-"))
            print("      the reading index holds %d identity(ies) of this spelling"
                  % len(card.get("corpus_bearers_of_the_spelling") or []))
        print("  ONE LOCATOR setting both readings (D5's roll test): %s"
              % (", ".join(pair["one_locator_setting_both"]) or "NONE"))
        print("  ONE TITLE setting both readings: %s"
              % (", ".join(pair["one_title_setting_both"]) or "NONE"))
        print("  titles setting both SURNAMES anywhere: %d" % len(pair["files_setting_both"]))
        print("  titles setting BOTH NAMES (C9's candidate demonstration): %s"
              % (", ".join(pair["titles_setting_both_names"]) or "NONE"))
        print("  sources both cards cite: %s"
              % (", ".join(pair["shared_sources"]) or "none"))
    return 0


def check() -> int:
    m = evidence()
    unruled = m["unruled"]
    if not unruled:
        print("   every one-letter card pair carries a ruling that names both cards")
        return 0
    print("   %d one-letter card pair(s) carry no ruling naming both cards:" % len(unruled))
    for pair in unruled:
        a, b = pair["cards"]
        print("     %s (%r) / %s (%r) — T-1291: rule it MERGE, DISTINCT or UNDECIDED"
              % (a["person"], a["name"], b["person"], b["name"]))
    return 1


def self_test() -> int:
    """A ruling naming ONE card of a pair does not cover the pair; naming both does."""
    pair = {"cards": [{"person": "x_a"}, {"person": "y_b"}]}
    one = {"clusters": [{"id": "c", "rulings": [
        {"state": "distinct", "members": ["x_a", "z_c"]}]}]}
    both = {"clusters": [{"id": "c", "rulings": [
        {"state": "distinct", "members": ["x_a", "y_b"]}]}]}
    folded = {"clusters": [{"id": "c", "rulings": [
        {"state": "merge", "survivor": "x_a", "folded": ["y_b"]}]}]}
    fails = []
    if pair_ruling(pair, one) is not None:
        fails.append("a ruling naming one card was counted as covering the pair")
    if pair_ruling(pair, both) is None:
        fails.append("a distinct ruling naming both cards was not recognised")
    if pair_ruling(pair, folded) is None:
        fails.append("a merge folding one card onto the other was not recognised")
    for line in fails:
        print("   FAIL: " + line)
    if fails:
        return 1
    print("   pair-level coverage: 3 case(s) pass")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--evidence", action="store_true",
                    help="the four facts a ruling is written from, per unruled pair")
    ap.add_argument("--triage", action="store_true",
                    help="one line per unruled pair and the rule its conditions point at")
    ap.add_argument("--check", action="store_true",
                    help="red while a one-letter pair carries no ruling naming both cards")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args(argv)
    if args.self_test:
        return self_test()
    if args.triage:
        return triage()
    if args.check:
        return check()
    return report(args.evidence)


if __name__ == "__main__":
    raise SystemExit(main())
