export const CHANGELOG = [ // newest first
  { v: 12, title: 'A guessed roof is an invention too', kind: 'feature',
    ts: '2026-08-10T05:26:06.281Z', date: 'Aug 10, 2026, 12:26 AM CT',
    items: [
      'Owning up used to stop at the shapes on the ground. If a building\'s outline or its place on the map was invented, the liberties list had to say so — but the roof over it, the height of its walls and whether it had a porch could all be guesses without anyone writing that down.',
      'They are guesses you cannot see being made. A dithered wall tells you a size is unknown; nothing tells you that a gable was chosen because gables were usual, or that a front was left plain because no source mentioned a porch either way. The confidence tint says we do not know. Only the liberty says what we did about not knowing.',
      'So the gate now holds every stated value to the same rule, and four more admissions were owed. The Sauganash\'s 1829 log cabin — the oldest thing standing in the scene — has an invented height and an invented roof. The Green Tree and the Western are both drawn with plain fronts because nobody found a porch, which is a decision, not a finding.',
      'The chips in the Evidence panel and on each building\'s card now name those too: "Sauganash Hotel roof type", "Western Hotel gallery". What is still unclaimed is what was left out entirely — an omission has no record to point at, and that needs a different kind of claim.',
    ] },
  { v: 11, title: 'Where the lake was in 1834', kind: 'feature',
    ts: '2026-08-10T05:06:01.254Z', date: 'Aug 10, 2026, 12:06 AM CT',
    items: [
      'The reconstruction now knows where the water ended. The shore from the edge of the modelled ground east to Lake Michigan is traced — the river past Fort Dearborn, the harbour cut between its two piers, the old channel still curling south behind the sand bar, and the bar itself.',
      'It had to come off the 1834 survey rather than a modern map. Everything east of about Michigan Avenue is later landfill, a good deal of it rubble from the 1871 fire, so today\'s coast sits roughly a kilometre out from the 1835 one. Drawing it would have been the largest false claim in the dataset, and it would have looked like care.',
      'Two edges the map does carry were found and thrown away: out in the lake the grey wash simply stops, and that stopping line is where the draughtsman lifted his brush. It is not a coast, so nothing was recorded there.',
      'You will not see any of this yet. The ground still ends where it ended yesterday — this is the survey, not the land. Building it needs elevations, and for the sand bar nobody wrote one down: a bar is a thing a foot of lake level moves.',
    ] },
  { v: 10, title: 'Each admission now says what it admits to', kind: 'feature',
    ts: '2026-08-10T04:12:36.029Z', date: 'Aug 9, 2026, 11:12 PM CT',
    items: [
      'The liberties in the Evidence panel now carry dashed chips naming exactly what they own up to — "Sauganash Hotel footprint", "Miller House footprint" — so you can see which invented shape an entry is answering for instead of reading three paragraphs to work it out.',
      'That is also how the commit gate decides. Until now it matched the wording of an entry against the building record, which meant a liberty could discharge an invented footprint by mentioning the word while discussing something else. Coverage is now declared by the document and checked against the data.',
      'The check runs both ways: an invention with no admission fails the build, and so does an admission with no invention. Claiming to have guessed something the sources actually settle reads as diligence and provides none.',
      'One entry was quietly out of date because of it. The Walker meeting house was recorded as "placed on the west bank, inferred" in the liberties document, while the record itself had already been downgraded to conjectural — a choice between two readings 150 m apart across a river is not a derivation. The document now says so.',
    ] },
  { v: 9, title: 'Rise above the town', kind: 'feature',
    ts: '2026-08-10T03:39:28.412Z', date: 'Aug 9, 2026, 10:39 PM CT',
    items: [
      'A free-fly mode: press F, or the ▲ button, and lift off the prairie to see the whole reconstruction from above — the forks, both branches of the river, and where each building sits along them.',
      'Settings now offers "From above" as a place to go, which arrives already in the air rather than standing in a field.',
      'On a phone, ▲ and ▼ appear at the bottom right while flying. Rise and descend follow where you are looking, and the ground is still solid — you can skim the prairie but not sink through it.',
      'Seen from above, the modelled town visibly ends where the detail does. That edge is honest: what lies past it is a plain skirt of ground, not a claim about 1835.',
    ] },
  { v: 8, title: 'The list of what we made up is now checked for gaps', kind: 'feature',
    ts: '2026-08-10T03:25:03.587Z', date: 'Aug 9, 2026, 10:25 PM CT',
    items: [
      'The walkthrough has been telling you which parts we invented. Nothing checked that the telling was complete — both views reported the liberties that had been written down, which is a weaker claim than it sounds.',
      'The commit gate now works the other way round: it reads every building record, finds the footprints and positions drawn from nothing, and refuses the build unless the liberties document names that building and that specific invention. A liberty about a building\'s gallery no longer counts as owning up to the footprint underneath it.',
      'Six inventions currently stand behind the six buildings at the forks — five drawn footprints and Walker\'s meeting house, placed on a bank the sources disagree about. All six are named in the panel, and now they have to be.',
    ] },
  { v: 7, title: 'What we made up about the building you are looking at', kind: 'feature',
    ts: '2026-08-10T02:41:16.630Z', date: 'Aug 9, 2026, 9:41 PM CT',
    items: [
      'Inspect a building and the card now lists the liberties taken with that building — the Green Tree\'s footprint reasoned out of a single room and its side additions left off, three Wolf Point buildings placed from the shape of the bank because no surviving corner fixes them.',
      'Until now those admissions sat in the Evidence panel as one list of eighteen covering the whole scene, so the visitor most likely to want them — someone standing in front of the building and asking — was the one who had to go looking.',
      'Both views render from the same derived record, which the commit gate re-derives from the append-only liberties document. A building with nothing recorded says so plainly, rather than implying nothing was invented.',
    ] },
  { v: 6, title: 'What we made up, in the walkthrough', kind: 'feature',
    ts: '2026-08-10T02:03:59.472Z', date: 'Aug 9, 2026, 9:03 PM CT',
    items: [
      'The Evidence panel now lists every liberty the reconstruction takes — eighteen of them, from the town being uniformly unpeopled to two prairie swales drawn where nothing attests them.',
      'Each one gives the decision, the reasoning behind it, what it costs the scene, and what evidence would settle it. The confidence chips cover attributes; this covers the choices that belong to no attribute.',
      'The list is derived from the project\'s append-only liberties record and re-derived by the commit gate, so what the panel shows cannot drift from what the repository admits.',
    ] },
  { v: 5, title: 'What\'s new, in the walkthrough itself', kind: 'feature',
    ts: '2026-08-10T01:48:34.145Z', date: 'Aug 9, 2026, 8:48 PM CT',
    items: [
      'The release notes now live in the panel, on their own tab — press N, or open the panel with H. Anything published since your last visit is marked, and the help button carries a dot until you have read it.',
      'The changelog moved into the app so the page can read it directly; publishing still copies it to the address the rest of the fleet reads, so nothing downstream moves.',
    ] },
  { v: 4, title: 'Five more buildings at the forks', kind: 'feature',
    ts: '2026-08-10T00:28:38.608Z', date: 'Aug 9, 2026, 7:28 PM CT',
    items: [
      'The Wolf Point Tavern, the Green Tree, Miller House, the Western Hotel and Walker\'s log meeting house, each placed from the 1834 survey rather than guessed at.',
      'Two new archetypes: hewn-log construction with corner notching and frame additions, and the timber log bridges over the branches.',
      'Source conflicts are recorded rather than resolved away — the Wolf Point Tavern\'s disputed build date, the Green Tree\'s possible log core, and Walker\'s meeting house, where the evidence may describe two different buildings on opposite banks.',
    ] },
  { v: 3, title: 'The Sauganash stands at Lake and Market', kind: 'feature',
    ts: '2026-08-09T23:26:56.854Z', date: 'Aug 9, 2026, 6:26 PM CT',
    items: [
      'The georeference now places buildings. The Sauganash moved off the datum origin — which is in the middle of the river — to its surveyed corner at Lake and Market, about a hundred metres east of the forks.',
      'Placement method is recorded on the record itself: modern street successors, the platted eighty-foot street width, and the georeference\'s twenty-metre uncertainty carried forward rather than hidden.',
      'Fixed a convention bug where the archetype built its facade facing south while the contract defines a bearing of zero as facing north. The first rotated building would have faced backwards.',
    ] },
  { v: 2, title: 'Controls, and three fixes found by looking', kind: 'fix',
    ts: '2026-08-09T23:11:09.000Z', date: 'Aug 9, 2026, 6:11 PM CT',
    items: [
      'The building rendered pure black on real GPUs. The confidence shader touched its channel even when switched off, and a NaN multiplied by zero is still a NaN.',
      'A well-documented building was drawn as guesswork: two attributes were tagged conjectural while their own notes gave typological reasoning, and an unknown size was dithering the whole massing. Size and character are different kinds of not-knowing.',
      'The sky-derived environment map was overriding albedo, so every surface converged on the sky colour whatever it was made of. A documented white wall now reads white.',
      'Added a real controls panel — key map, walking speed, field of view, render quality and jump-to viewpoints. Run already existed on Shift and there was no way to discover it.',
    ] },
  { v: 1, title: 'Milestone 0 — one building, end to end', kind: 'feature',
    ts: '2026-08-09T22:16:34.000Z', date: 'Aug 9, 2026, 5:16 PM CT',
    items: [
      'A walkable reconstruction of the Sauganash Hotel as it stood in summer 1835, generated from a provenance-tracked record rather than modelled by hand.',
      'The confidence view: documented geometry renders solid, inferred is tinted, and anything we are guessing at becomes dithered massing. The tint and the citation come from the same record.',
      'The datum is verified — the forks at Wolf Point, derived from the 1834 Wright survey against modern control and re-derived from its own traces on every commit.',
    ] },
];

export const LATEST_VERSION = CHANGELOG[0].v;
