/**
 * roof-relief.js — the two roof coverings, bound as relief rather than colour.
 *
 * T-1488, and the second half of T-1465. T-1487 put `shingle` and `roof_board`
 * on the material sheet and named every roof primitive in the town for the
 * covering it carries, so `assets/gltf/` ships 241 materials called
 * `roof_shingle` and 128 called `roof_board` — and every one of them renders as
 * a flat brown plane, because a covering with no relief is a colour and not a
 * covering. This module is what makes a roof read as a roof.
 *
 * ## The question T-1487 could not answer, and the answer
 *
 * A shingle field tiles at **4.48 m** — `docs/RESEARCH/texture_library.md` and
 * the library's own `material.json`, 32 courses at the 0.14 m exposure L263
 * committed. A tile rate in METRES needs UVs that mean metres, and the town's
 * do not: `generators/build.py`'s `unwrap()` runs `smart_project` per object,
 * which is an island pack into 0..1 laid out for an AO atlas. The same map would
 * land at a different scale on every roof and on every island of one roof.
 *
 * Three routes were open, and the ticket asked for the bargain each strikes:
 *
 *   1. **Metric UV0 on roof primitives.** Cheapest in the renderer — bind and
 *      go. It costs the AO path the atlas: `bake_ao` packs occlusion into the
 *      same UV0, and a metric unwrap overlaps by construction (that is what
 *      tiling IS), so two roofs would write the same texels. It also moves a UV
 *      on 369 primitives, so the whole town rebakes.
 *   2. **A second UV set.** Keeps the atlas; costs a TEXCOORD_1 on every roof
 *      primitive, an addition to `docs/GLB-CONTRACT.md`'s vertex attributes, a
 *      full town bake, and a new branch through seven archetypes' `add_poly`
 *      call sites, none of which carry UVs today.
 *   3. **Derive the UV in the shader from world position.** Costs no attribute,
 *      no vertex, no UV, no bake and no change to what a GLB contains. It costs
 *      a shader patch and the honesty of saying that the projection is the
 *      renderer's and not the asset's.
 *
 * **Route 3, with the projection slope-aligned rather than world-axis.** Plain
 * triplanar was rejected on the look: the top projection tiles in world XY, so
 * the courses would run along a world axis and this town's buildings do not —
 * the Lake Street fronts alone sit at four bearings, and a shingle course that
 * crosses the eave at 20 deg reads as a mistake from the street, which is the
 * one thing this ticket exists to fix. So the frame is taken from the FACE:
 *
 *     t = normalize( cross( n, up ) )      along the eave, for any pitched roof
 *     b = cross( t, n )                    straight up the slope
 *     uv = ( dot( p, t ), dot( p, b ) ) / tile_m
 *
 * `t` is horizontal whenever `n` is not vertical, and the eave line of a pitched
 * roof is exactly the horizontal line in its plane — so the courses run parallel
 * to the eave on every roof in the town without any roof being asked its bearing.
 * The two slopes of a gable get opposite `t` and therefore mirrored courses,
 * which is what a lapped field looks like anyway. A face whose normal IS vertical
 * — a fascia soffit, an eave underside — is degenerate and falls back to world x.
 *
 * It is computed per VERTEX, not per fragment, and that is exact rather than
 * cheap: `to_object()` sets `use_smooth = False` on every polygon, so a vertex
 * carries its own face's normal, the projection is affine over a planar face,
 * and the rasteriser's interpolation of an affine function is that function.
 *
 * ## How the renderer knows a roof is shingled
 *
 * **By the material's name, and `docs/GLB-CONTRACT.md` § Roof coverings now pins
 * it** — proposed there in the terms that document requires rather than assumed
 * here. The alternative the ticket named — carrying the substrate in the
 * material's `extras` — is the better-typed channel and was still rejected, on a
 * measurement: the extras route rebakes all 384 GLBs to add a field the name
 * already carries, and the name is generated by exactly one function
 * (`common.materials.roof_material_name`), which is the condition a pin needs.
 *
 * The contract's own 2026-08-17 note argued AGAINST keying on a material name,
 * and it was right at the time and cited ROADMAP K36(a) — 38 shipped assets with
 * their material names gone. **That is no longer true and was re-measured for
 * this ticket: across all 384 GLBs in `assets/gltf/` and all 384 in
 * `assets/web/`, ZERO materials are unnamed.** A pin is a promise to keep them,
 * which is what turns the convention the note distrusted into one a renderer may
 * read.
 *
 * ## What is bound, and what is not
 *
 * The relief maps only. `normalMap` from `normal_gl`, and the packed `orm` as
 * both `roughnessMap` (green) and `aoMap` (red) — one file, two slots, the
 * glTF-native packing the library already writes. **The basecolors are NOT
 * bound.** Colour stays on the per-vertex stream, which is what keeps T-0007's
 * roof-condition grading and T-0002's per-building jitter alive and leaves
 * `materialKey()` reading exactly what it read before.
 *
 * The tile rate is read from the library's `material.json` (`span_m`) rather
 * than written here, so the renderer cannot drift from the sheet the generators
 * deal off.
 */

import * as THREE from 'three';
import { resolveBases } from './scene-loader.js';

/**
 * Material name -> the library directory that covers it.
 *
 * The names are `common.materials.roof_material_name()`'s, pinned by
 * `docs/GLB-CONTRACT.md` § Roof coverings. `roof_plane` — the sheet's fallback —
 * is deliberately absent: it carries zero records, and a covering nothing is
 * made of has no relief to bind.
 */
const COVERINGS = {
  roof_shingle: 'roofs/wood_shingles_weathered',
  roof_board: 'roofs/roof_boards_weathered',
};

const LIBRARY = 'textures/chicago_1835_pbr/';

/**
 * The same eight-line frame as the docstring, in GLSL, written into the vertex
 * stage after `<project_vertex>` — the first point at which both `transformed`
 * (object-space position) and `objectNormal` are in scope.
 *
 * It assigns three of three's own map varyings rather than introducing one, so
 * the fragment stage is stock: `<normal_fragment_begin>` builds its tangent
 * frame from `vNormalMapUv` by screen-space derivative, and the roughness and AO
 * chunks sample at the same coordinate. Nothing downstream knows the UV did not
 * come off the mesh.
 *
 * A consequence worth naming: `texture.repeat` and `texture.offset` are no
 * longer read, because `<uv_vertex>`'s product is overwritten. The metric tile
 * is the whole of the transform.
 */
function metricRoofUv(material, tileM) {
  const prior = material.onBeforeCompile;
  material.onBeforeCompile = (shader, renderer) => {
    if (typeof prior === 'function') prior(shader, renderer);
    shader.uniforms.chiRoofTileM = { value: tileM };
    shader.vertexShader = 'uniform float chiRoofTileM;\n'
      + shader.vertexShader.replace(
        '#include <project_vertex>',
        `#include <project_vertex>
  {
    vec3 chiWorldPos = ( modelMatrix * vec4( transformed, 1.0 ) ).xyz;
    vec3 chiWorldNrm = normalize( mat3( modelMatrix ) * objectNormal );
    vec3 chiAlongEave = cross( chiWorldNrm, vec3( 0.0, 1.0, 0.0 ) );
    float chiEaveLen = length( chiAlongEave );
    chiAlongEave = chiEaveLen > 1e-4
      ? chiAlongEave / chiEaveLen
      : vec3( 1.0, 0.0, 0.0 );
    vec3 chiUpSlope = cross( chiAlongEave, chiWorldNrm );
    vec2 chiRoofUv = vec2( dot( chiWorldPos, chiAlongEave ),
                           dot( chiWorldPos, chiUpSlope ) ) / chiRoofTileM;
    #ifdef USE_NORMALMAP
      vNormalMapUv = chiRoofUv;
    #endif
    #ifdef USE_ROUGHNESSMAP
      vRoughnessMapUv = chiRoofUv;
    #endif
    #ifdef USE_AOMAP
      vAoMapUv = chiRoofUv;
    #endif
  }`,
      );
  };
  material.needsUpdate = true;
}

/** A linear (non-colour) map, tiling, off the vendored library. */
function reliefTexture(loader, url) {
  return new Promise((resolve, reject) => {
    loader.load(url, (tex) => {
      tex.wrapS = THREE.RepeatWrapping;
      tex.wrapT = THREE.RepeatWrapping;
      // Every one of these is data, not colour — the library's material.json
      // records `normal_gl` and `orm` as linear. Tagging one sRGB would decode
      // a normal vector through a gamma curve.
      tex.colorSpace = THREE.NoColorSpace;
      // The same 8 the water ripple uses (terrain.js): a roof seen from the
      // street is a grazing surface, and without anisotropy its courses turn to
      // aliased mush at the ridge.
      tex.anisotropy = 8;
      resolve(tex);
    }, undefined, () => reject(new Error(`roof relief map did not load — ${url}`)));
  });
}

/**
 * Load both coverings' maps. Returns an object with `apply(material)`, or
 * `null` if anything did not arrive.
 *
 * **It degrades rather than throws.** A missing map is a town whose roofs read
 * the way they read today, which is the state this ticket improves on; it is
 * not a boot failure, and `site/`'s smoke holds the page to zero pageerrors.
 * The caller reports the miss through the same `problems` list every other
 * asset complaint travels on.
 */
export async function loadRoofRelief({ assetBase = resolveBases().assetBase } = {}) {
  const loader = new THREE.TextureLoader();
  const base = new URL(LIBRARY, assetBase);
  const bound = new Map();
  try {
    await Promise.all(Object.entries(COVERINGS).map(async ([name, dir]) => {
      const here = new URL(`${dir}/`, base);
      const res = await fetch(new URL('material.json', here), { cache: 'no-cache' });
      if (!res.ok) throw new Error(`${res.status} — ${new URL('material.json', here)}`);
      const sheet = await res.json();
      const tileM = Number(sheet.span_m);
      if (!(tileM > 0)) throw new Error(`${dir}: material.json states no span_m`);
      const [normalMap, orm] = await Promise.all([
        reliefTexture(loader, new URL(`${sheet.id}_normal_gl.png`, here).href),
        reliefTexture(loader, new URL(`${sheet.id}_orm.png`, here).href),
      ]);
      bound.set(name, { normalMap, orm, tileM });
    }));
  } catch (err) {
    return { problem: `roof relief maps not bound — ${err.message}`, apply: () => null };
  }

  /** The roughness the first material of each covering carried, for the check below. */
  const roughnessSeen = new Map();

  return {
    problem: null,
    /**
     * Bind the covering this material names, if it names one.
     *
     * Called on EVERY material before `materialKey()` reads it, which is the
     * whole reason it is a separate step: the key separates on map uuids, so a
     * roof that is bound here lands in its own batch and a wall that is not
     * stays in the town's. Both coverings share one texture pair across the
     * whole town, so that is two batches for 369 roofs and not 369.
     *
     * Returns a warning string, or null.
     */
    apply(material) {
      const covering = bound.get(material?.name);
      if (!covering || material.userData?.chiRoofRelief) return null;
      material.normalMap = covering.normalMap;
      // One file in two slots: ORM is R=AO, G=roughness, B=metallic, and three
      // samples exactly those channels for `aoMap` and `roughnessMap`. Binding
      // it twice costs one upload and one resident texture rather than two.
      material.roughnessMap = covering.orm;
      material.aoMap = covering.orm;
      metricRoofUv(material, covering.tileM);
      material.userData = { ...(material.userData ?? {}), chiRoofRelief: material.name };

      // `perVertexRoughness` refuses a material with a `roughnessMap` — it
      // cannot substitute for a chunk that samples a texture — so a roof batch
      // reads its roughness from the shared uniform instead of per vertex, and
      // that is only honest if every roof of this covering carries the same
      // number. Measured 2026-09-20 over all 384 GLBs in both trees: exactly one
      // value per covering (shingle 0.90, board 0.93), which is what the sheet
      // deals. Say so out loud if that ever stops being true.
      const first = roughnessSeen.get(material.name);
      if (first === undefined) roughnessSeen.set(material.name, material.roughness);
      else if (Math.abs(first - material.roughness) > 1e-4) {
        return `${material.name}: roughness ${material.roughness} differs from the `
          + `${first} the batch renders — the sheet deals one value per covering, and `
          + 'a roof batch carries a roughness map so it cannot carry one per vertex';
      }
      return null;
    },
  };
}
