#!/usr/bin/env python3
"""
Parametric Sandstone Strata Base/Platter Generator
====================================================
Creates a complementary base or platter piece that sits seamlessly below
a sandstone strata lamp generated by generate_sandstone.py.

The top edge (z=0) matches the lamp's bottom ring exactly, and the piece
extends downward with the same organic strata texture — interpolated from
the original model's ring data.

Usage examples:
  # Default solid 40mm base
  python3 generate_sandstone_base.py --height 40

  # Hollow base with 2mm wall
  python3 generate_sandstone_base.py --height 40 --wall 2

  # Hollow with solid floor at the bottom
  python3 generate_sandstone_base.py --height 40 --wall 2 --base 3

  # Wider platter (flare outward at bottom)
  python3 generate_sandstone_base.py --height 40 --flare 1.3

  # Vase-style: hollow, flared, solid bottom
  python3 generate_sandstone_base.py --height 60 --wall 2 --base 3 --flare 1.2

  # Output to specific file
  python3 generate_sandstone_base.py --height 50 -o my_base.scad
"""

import argparse
import math
import os
import re
import struct
import sys
from pathlib import Path


# ── Constants ────────────────────────────────────────────────────────────────
BASELINE_HEIGHT = 120.0       # mm – original model height
BASELINE_NUM_LAYERS = 111     # original ring count (0 through 110)
POINTS_PER_RING = 120         # angular samples per ring (3° spacing)
SCRIPT_DIR = Path(__file__).parent
DEFAULT_SOURCE = SCRIPT_DIR / ".." / "raw" / "1-illinois_sandstone_cylinder_v3.scad"


# ── Parsing ──────────────────────────────────────────────────────────────────

def parse_original_scad(filepath):
    """Parse the original SCAD polyhedron into structured ring data.

    Returns:
        rings       : list of lists – rings[i][j] = (x, y, z)
        ring_avg_z  : list of float – average Z per ring
    """
    points = []
    point_re = re.compile(r'\[\s*([^,]+),\s*([^,]+),\s*([^\]]+)\]')

    with open(filepath) as f:
        for line in f:
            if 'faces' in line and '=' in line:
                break
            m = point_re.search(line)
            if m:
                x = float(m.group(1))
                y = float(m.group(2))
                z = float(m.group(3))
                points.append((x, y, z))

    rings = []
    ring_avg_z = []
    for i in range(BASELINE_NUM_LAYERS):
        start = i * POINTS_PER_RING
        end = start + POINTS_PER_RING
        ring = points[start:end]
        rings.append(ring)
        avg_z = sum(p[2] for p in ring) / POINTS_PER_RING
        ring_avg_z.append(avg_z)

    return rings, ring_avg_z


# ── Interpolation ────────────────────────────────────────────────────────────

def lerp(a, b, t):
    return a + (b - a) * t


def interpolate_rings_downward(original_rings, ring_avg_z, num_new_layers,
                               base_height, top_scale=1.0,
                               bottom_scale=1.0, sharp=False):
    """Generate new rings by interpolating original ring data, going downward.

    The rings go from z=0 (top, matching lamp bottom) to z=-base_height.
    The original ring XY profiles are sampled to preserve the organic strata
    texture. XY can scale independently at top/bottom, linearly blended
    across height.

    Two modes:
      sharp=False (default):
        XY profiles are linearly blended between bracketing original rings.
        Produces smooth, natural strata matching the lamp's look.

      sharp=True:
        XY profiles snap to the NEAREST original ring (nearest-neighbor).
        Creates crisp, pronounced strata ledges.
    """
    n_orig = len(original_rings)
    new_rings = []

    for k in range(num_new_layers):
        if num_new_layers == 1:
            t_new = 0.5
        else:
            t_new = k / (num_new_layers - 1)

        # Map to original ring index space [0, n_orig - 1]
        orig_pos = t_new * (n_orig - 1)
        i_lo = int(math.floor(orig_pos))
        i_hi = min(i_lo + 1, n_orig - 1)
        alpha = orig_pos - i_lo

        # For sharp mode: snap to nearest original ring for XY
        if sharp:
            i_nearest = i_lo if alpha < 0.5 else i_hi

        # XY scale: top_scale at top (k=0) → bottom_scale at bottom (k=N-1)
        current_scale = lerp(top_scale, bottom_scale, t_new)

        # Nominal Z for this layer
        nominal_z = -base_height * t_new

        ring = []
        for j in range(POINTS_PER_RING):
            if sharp:
                # Nearest-neighbor: exact XY from closest original ring
                p_src = original_rings[i_nearest][j]
                x = p_src[0] * current_scale
                y = p_src[1] * current_scale
            else:
                # Linear blend of XY between bracketing rings (default)
                p_lo = original_rings[i_lo][j]
                p_hi = original_rings[i_hi][j]
                x = lerp(p_lo[0], p_hi[0], alpha) * current_scale
                y = lerp(p_lo[1], p_hi[1], alpha) * current_scale

            # Z undulation offset (always interpolated smoothly)
            p_lo = original_rings[i_lo][j]
            p_hi = original_rings[i_hi][j]
            z_lo_nominal = ring_avg_z[i_lo]
            z_hi_nominal = ring_avg_z[i_hi]
            z_lo_offset = p_lo[2] - z_lo_nominal
            z_hi_offset = p_hi[2] - z_hi_nominal
            z_offset = lerp(z_lo_offset, z_hi_offset, alpha)

            # Scale the offset proportionally to the base height
            z_offset_scaled = z_offset * (base_height / BASELINE_HEIGHT)

            z = nominal_z + z_offset_scaled

            ring.append((x, y, z))

        new_rings.append(ring)

    return new_rings


# ── Mesh Building ────────────────────────────────────────────────────────────
# These are adapted directly from generate_sandstone.py with the Z direction
# flipped (top=0, bottom=-height).

def build_mesh(new_rings, base_height):
    """Build the complete solid mesh with flat cap rings.

    Structure identical to generate_sandstone.py's build_mesh:
      flat_top (z=0) + organic rings + flat_bottom (z=-base_height)
      + center point caps on top and bottom.
    """
    P = POINTS_PER_RING

    first_organic = new_rings[0]
    last_organic = new_rings[-1]
    flat_top_ring = [(p[0], p[1], 0.0) for p in first_organic]
    flat_bottom_ring = [(p[0], p[1], -base_height) for p in last_organic]

    # Full ring list: flat_top + organic interior + flat_bottom
    # Skip first/last organic rings — they coincide with the flat caps
    # (same XY, z ≈ 0 / -base_height) which creates coincident vertices
    # and non-manifold edges in STL output.
    organic_interior = list(new_rings[1:-1]) if len(new_rings) > 2 else []
    all_rings = [flat_top_ring] + organic_interior + [flat_bottom_ring]
    total_rings = len(all_rings)

    all_points = []
    for ring in all_rings:
        all_points.extend(ring)

    # Center points
    center_top_idx = len(all_points)
    all_points.append((0.0, 0.0, 0.0))
    center_bot_idx = len(all_points)
    all_points.append((0.0, 0.0, -base_height))

    faces = []

    # Side faces
    for i in range(total_rings - 1):
        for j in range(P):
            j_next = (j + 1) % P
            a = i * P + j
            b = i * P + j_next
            c = (i + 1) * P + j_next
            d = (i + 1) * P + j
            faces.append([a, b, c])
            faces.append([a, c, d])

    # Top cap (z=0): fan from center — normals up
    for j in range(P):
        j_next = (j + 1) % P
        faces.append([center_top_idx, j, j_next])

    # Bottom cap (z=-base_height): fan from center — normals down
    last_ring_start = (total_rings - 1) * P
    for j in range(P):
        j_next = (j + 1) % P
        faces.append([center_bot_idx, last_ring_start + j_next,
                      last_ring_start + j])

    return all_points, faces


def offset_ring_inward(ring, wall_thickness):
    """Offset a ring inward by wall_thickness in XY, preserving Z.

    Identical to generate_sandstone.py's version.
    """
    cx = sum(p[0] for p in ring) / len(ring)
    cy = sum(p[1] for p in ring) / len(ring)

    inner_ring = []
    for (x, y, z) in ring:
        dx = x - cx
        dy = y - cy
        dist = math.sqrt(dx * dx + dy * dy)
        if dist < 1e-9:
            inner_ring.append((x, y, z))
        else:
            ux = dx / dist
            uy = dy / dist
            inner_ring.append((x - ux * wall_thickness,
                               y - uy * wall_thickness, z))

    return inner_ring


def ring_nominal_diameter(ring):
    """Return nominal outer diameter (mm) for a ring.

    Uses max radial distance from ring centroid for robustness to slight
    off-center/asymmetric geometry.
    """
    cx = sum(p[0] for p in ring) / len(ring)
    cy = sum(p[1] for p in ring) / len(ring)
    max_r = 0.0
    for x, y, _ in ring:
        r = math.hypot(x - cx, y - cy)
        if r > max_r:
            max_r = r
    return 2.0 * max_r


def build_hollow_mesh(new_rings, base_height, wall_thickness,
                      solid_base=0.0):
    """Build a hollow tube mesh — adapted from generate_sandstone.py.

    Structure:
      - Outer shell: flat_top + organic rings + flat_bottom
      - Inner shell: offset inward by wall_thickness
      - Top annulus: connects outer ring 0 to inner ring 0 (z=0)
      - Bottom closure: solid disc or annulus depending on solid_base

    For the base piece, "solid_base" means a solid floor at the bottom
    (z = -base_height), with the inner wall starting at
    z = -(base_height - solid_base).
    """
    P = POINTS_PER_RING

    # ── Outer rings ──────────────────────────────────────────────────────
    first_organic = new_rings[0]
    last_organic = new_rings[-1]
    flat_top_outer = [(p[0], p[1], 0.0) for p in first_organic]
    flat_bottom_outer = [(p[0], p[1], -base_height) for p in last_organic]
    # Skip first/last organic rings — they coincide with flat caps
    organic_interior = list(new_rings[1:-1]) if len(new_rings) > 2 else []
    outer_rings = [flat_top_outer] + organic_interior + [flat_bottom_outer]
    total_outer_rings = len(outer_rings)

    # ── Determine where inner wall starts ────────────────────────────────
    def ring_avg_z(ring):
        return sum(p[2] for p in ring) / len(ring)

    # Inner wall goes from top down to (base_height - solid_base)
    inner_cutoff_z = -(base_height - solid_base) if solid_base > 0 else -base_height

    inner_stop_idx = total_outer_rings
    if solid_base > 0:
        for idx in range(total_outer_rings - 1, -1, -1):
            if ring_avg_z(outer_rings[idx]) >= inner_cutoff_z - 1e-6:
                inner_stop_idx = idx + 1
                break

    inner_source_rings = outer_rings[0:inner_stop_idx]

    # ── Build inner rings ────────────────────────────────────────────────
    inner_rings_offset = [offset_ring_inward(ring, wall_thickness)
                          for ring in inner_source_rings]

    # Force the last inner ring to sit at the cutoff Z
    if solid_base > 0 and len(inner_rings_offset) > 0:
        inner_rings_offset[-1] = [
            (p[0], p[1], inner_cutoff_z) for p in inner_rings_offset[-1]
        ]

    total_inner_rings = len(inner_rings_offset)

    # ── Flatten all points ───────────────────────────────────────────────
    all_points = []
    for ring in outer_rings:
        all_points.extend(ring)
    outer_count = len(all_points)

    for ring in inner_rings_offset:
        all_points.extend(ring)

    faces = []

    # ── Outer side faces (normal outward) ────────────────────────────────
    for i in range(total_outer_rings - 1):
        for j in range(P):
            j_next = (j + 1) % P
            a = i * P + j
            b = i * P + j_next
            c = (i + 1) * P + j_next
            d = (i + 1) * P + j
            faces.append([a, b, c])
            faces.append([a, c, d])

    # ── Inner side faces (normal inward = reversed winding) ──────────────
    for i in range(total_inner_rings - 1):
        for j in range(P):
            j_next = (j + 1) % P
            a = outer_count + i * P + j
            b = outer_count + i * P + j_next
            c = outer_count + (i + 1) * P + j_next
            d = outer_count + (i + 1) * P + j
            faces.append([a, c, b])
            faces.append([a, d, c])

    # ── Top annulus (z=0): connects outer top to inner top ───────────────
    for j in range(P):
        j_next = (j + 1) % P
        o_a = j
        o_b = j_next
        i_a = outer_count + j
        i_b = outer_count + j_next
        faces.append([o_a, o_b, i_b])
        faces.append([o_a, i_b, i_a])

    # ── Bottom closure ───────────────────────────────────────────────────
    if solid_base > 0:
        # Solid bottom disc at z = -base_height (outer bottom ring)
        center_bot_idx = len(all_points)
        all_points.append((0.0, 0.0, -base_height))
        bot_ring_start = (total_outer_rings - 1) * P
        for j in range(P):
            j_next = (j + 1) % P
            faces.append([center_bot_idx, bot_ring_start + j_next,
                          bot_ring_start + j])

        # Inner floor disc at z = inner_cutoff_z
        # (No lip needed — outer shell + bottom disc + inner shell + floor disc
        #  form a closed manifold without connecting them at the cutoff ring.
        #  Adding a lip would create 3 faces per edge = non-manifold.)
        center_floor_idx = len(all_points)
        all_points.append((0.0, 0.0, inner_cutoff_z))
        inner_floor_start = outer_count + (total_inner_rings - 1) * P
        for j in range(P):
            j_next = (j + 1) % P
            faces.append([center_floor_idx, inner_floor_start + j,
                          inner_floor_start + j_next])
    else:
        # No solid base: bottom annulus connecting outer to inner
        bot_outer_start = (total_outer_rings - 1) * P
        bot_inner_start = outer_count + (total_inner_rings - 1) * P
        for j in range(P):
            j_next = (j + 1) % P
            o_a = bot_outer_start + j
            o_b = bot_outer_start + j_next
            i_a = bot_inner_start + j
            i_b = bot_inner_start + j_next
            faces.append([o_a, i_a, i_b])
            faces.append([o_a, i_b, o_b])

    return all_points, faces


# ── Output ───────────────────────────────────────────────────────────────────

def cross(u, v):
    return (u[1]*v[2] - u[2]*v[1],
            u[2]*v[0] - u[0]*v[2],
            u[0]*v[1] - u[1]*v[0])


def normalize(v):
    length = math.sqrt(v[0]**2 + v[1]**2 + v[2]**2)
    if length < 1e-12:
        return (0.0, 0.0, 0.0)
    return (v[0]/length, v[1]/length, v[2]/length)


def write_stl(filepath, all_points, faces):
    """Write a binary STL file — identical to generate_sandstone.py."""
    num_triangles = len(faces)
    with open(filepath, 'wb') as f:
        header = b'Binary STL - Parametric Sandstone Base'
        f.write(header.ljust(80, b'\0'))
        f.write(struct.pack('<I', num_triangles))

        for face in faces:
            p0 = all_points[face[0]]
            p1 = all_points[face[1]]
            p2 = all_points[face[2]]
            u = (p1[0]-p0[0], p1[1]-p0[1], p1[2]-p0[2])
            v = (p2[0]-p0[0], p2[1]-p0[1], p2[2]-p0[2])
            n = normalize(cross(u, v))
            f.write(struct.pack('<3f', *n))
            f.write(struct.pack('<3f', *p0))
            f.write(struct.pack('<3f', *p1))
            f.write(struct.pack('<3f', *p2))
            f.write(struct.pack('<H', 0))


def write_scad(filepath, all_points, faces, base_height, num_layers):
    """Write OpenSCAD polyhedron — same format as generate_sandstone.py."""
    with open(filepath, 'w') as f:
        f.write(f"""\
// ═══════════════════════════════════════════════════════════════════════════
// Parametric Illinois Sandstone Strata Base / Platter
// ═══════════════════════════════════════════════════════════════════════════
//
// Generated by generate_sandstone_base.py
//
// This piece connects seamlessly to the bottom of a sandstone lamp
// generated by generate_sandstone.py — the top edge (z=0) matches
// the lamp's bottom ring exactly.
//
// Parameters:
//   base_height = {base_height} mm
//   num_layers  = {num_layers}
//

/* [Height Fine-Tuning] */
fine_tune_scale = 1.0;  // [0.25:0.01:4.0]

// ── Render ──────────────────────────────────────────────────────────────

scale([1, 1, fine_tune_scale])
""")
        f.write("polyhedron(\n")
        f.write("  points = [\n")
        for idx, (x, y, z) in enumerate(all_points):
            comma = "," if idx < len(all_points) - 1 else ""
            f.write(f"        [{x:.5f}, {y:.5f}, {z:.5f}]{comma}\n")
        f.write("      ],\n")
        f.write("      faces = [\n")
        for idx, face in enumerate(faces):
            comma = "," if idx < len(faces) - 1 else ""
            f.write(f"        [{face[0]}, {face[1]}, {face[2]}]{comma}\n")
        f.write("      ],\n")
        f.write("      convexity = 10\n")
        f.write("    );\n")


# ── CLI ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generate a parametric base/platter for sandstone lamps.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    parser.add_argument('--height', type=float, default=40.0,
                        help='Base height downward (mm) [40]')
    parser.add_argument('--layers', type=int, default=None,
                        help='Number of strata layers [auto: proportional]')
    parser.add_argument('--flare', type=float, default=1.0,
                        help='Radial flare at bottom (>1=wider) [1.0]')
    parser.add_argument('--top-diameter', type=float, default=None,
                        help='Target outer diameter at top opening (mm)')
    parser.add_argument('--bottom-diameter', type=float, default=None,
                        help='Target outer diameter at bottom/floor (mm)')
    parser.add_argument('--wall', type=float, default=None,
                        help='Wall thickness (mm) — makes hollow [solid]')
    parser.add_argument('--base', type=float, nargs='?', const=3.0, default=None,
                        help='Solid floor at the bottom (mm). '
                             '--base alone = 3mm, or --base 5 [no floor]')
    parser.add_argument('--source', type=str, default=str(DEFAULT_SOURCE),
                        help='Path to source SCAD polyhedron')
    parser.add_argument('--sharp', action='store_true', default=False,
                        help='Use sharp nearest-neighbor XY snapping for crisp, '
                             'pronounced strata ledges (default: smooth blending)')
    parser.add_argument('-o', '--output', type=str, default=None,
                        help='Output filename (auto-generated if omitted)')

    args = parser.parse_args()

    # ── Resolve layers ───────────────────────────────────────────────────
    if args.layers is None:
        # Scale proportionally so strata density matches the original
        # (~1.09mm per layer). Nearest-neighbor XY interpolation keeps
        # ledges sharp even with the extra rings.
        args.layers = max(2, int(round(
            BASELINE_NUM_LAYERS * (args.height / BASELINE_HEIGHT))))

    # ── Resolve hollow / wall / base ─────────────────────────────────────
    wall_thickness = None
    solid_base = 0.0

    if args.wall is not None:
        wall_thickness = args.wall
    elif args.base is not None:
        wall_thickness = 2.0  # --base implies hollow

    if args.base is not None:
        solid_base = args.base
        if wall_thickness is None:
            wall_thickness = 2.0

    is_hollow = wall_thickness is not None

    # ── Parse original ───────────────────────────────────────────────────
    source_path = args.source
    if not os.path.exists(source_path):
        print(f"ERROR: Source file not found: {source_path}", file=sys.stderr)
        sys.exit(1)

    print(f"Parsing original: {source_path}")
    rings, ring_avg_z = parse_original_scad(source_path)
    print(f"  → {len(rings)} rings × {POINTS_PER_RING} points/ring")

    baseline_top_d = ring_nominal_diameter(rings[0])
    top_scale = 1.0
    if args.top_diameter is not None:
        top_scale = args.top_diameter / baseline_top_d

    if args.bottom_diameter is not None:
        bottom_scale = args.bottom_diameter / baseline_top_d
    else:
        bottom_scale = top_scale * args.flare

    # ── Generate downward rings ──────────────────────────────────────────
    print(f"\nGenerating parametric base:")
    print(f"  Height       : {args.height:.1f} mm (downward)")
    print(f"  Strata layers: {args.layers}")
    print(f"  Flare factor : {args.flare:.2f}x")
    top_outer_d = baseline_top_d * top_scale
    bottom_outer_d = baseline_top_d * bottom_scale
    print(f"  Top outer Ø  : {top_outer_d:.2f} mm")
    print(f"  Bottom outer Ø: {bottom_outer_d:.2f} mm")
    layer_thickness = args.height / max(1, args.layers - 1)
    print(f"  Avg layer    : {layer_thickness:.2f} mm")
    print(f"  Strata mode  : {'SHARP (nearest-neighbor)' if args.sharp else 'SMOOTH (blended)'}")

    if is_hollow:
        mode_parts = [f"wall = {wall_thickness:.2f} mm"]
        if solid_base > 0:
            mode_parts.append(f"solid floor = {solid_base:.2f} mm")
        print(f"  Mode         : HOLLOW ({', '.join(mode_parts)})")
    else:
        print(f"  Mode         : SOLID")

    new_rings = interpolate_rings_downward(
        rings, ring_avg_z, args.layers, args.height,
        top_scale=top_scale, bottom_scale=bottom_scale, sharp=args.sharp)

    # ── Build mesh ───────────────────────────────────────────────────────
    if is_hollow:
        all_points, faces = build_hollow_mesh(
            new_rings, args.height, wall_thickness, solid_base)
    else:
        all_points, faces = build_mesh(new_rings, args.height)

    # ── Output filenames ─────────────────────────────────────────────────
    if args.output:
        base_output = args.output
        if base_output.lower().endswith(('.scad', '.stl')):
            base_output = base_output.rsplit('.', 1)[0]
    else:
        h_tag = f"{args.height:.0f}mm"
        l_tag = f"{args.layers}L"
        w_tag = ""
        if args.flare != 1.0:
            flare_str = f"{args.flare:.2f}".rstrip('0').rstrip('.')
            w_tag += f"_flare{flare_str}"
        if args.top_diameter is not None:
            top_d_str = f"{args.top_diameter:.2f}".rstrip('0').rstrip('.')
            w_tag += f"_top{top_d_str}"
        if args.bottom_diameter is not None:
            bot_d_str = f"{args.bottom_diameter:.2f}".rstrip('0').rstrip('.')
            w_tag += f"_bot{bot_d_str}"
        if is_hollow:
            w_tag += f"_wall{wall_thickness:.0f}"
            if solid_base > 0:
                base_str = f"{solid_base:.2f}".rstrip('0').rstrip('.')
                w_tag += f"_base{base_str}"
        base_output = f"illinois_sandstone_parametric_base_{h_tag}_{l_tag}{w_tag}"

    scad_path = base_output + '.scad'
    stl_path = base_output + '.stl'

    # ── Write ────────────────────────────────────────────────────────────
    write_scad(scad_path, all_points, faces, args.height, args.layers)
    write_stl(stl_path, all_points, faces)

    stl_mb = os.path.getsize(stl_path) / (1024 * 1024)

    print(f"\n✓ SCAD: {scad_path}")
    print(f"✓ STL:  {stl_path}  ({stl_mb:.1f} MB)")
    print(f"  Points: {len(all_points):,}  |  Faces: {len(faces):,}")
    print(f"  Top edge at z=0 matches sandstone lamp bottom exactly.")
    print()


if __name__ == '__main__':
    main()
