#!/usr/bin/env python3
"""
Parametric Sandstone Strata Base/Platter Generator
====================================================
Creates a complementary base or platter piece that sits seamlessly below
a sandstone strata lamp generated by generate_sandstone.py.

The base uses the same reference geometry (bottom ring of the sandstone model)
and extends downward by a specified distance, optionally flaring outward to
create a wider platter, vase, or planter shape.

This enables converting a sandstone lamp into a flower pot or vase by:
  1. Generating a sandstone lamp with --hollow and --base options
  2. Generating a matching base with this script
  3. Printing and assembling both pieces

Usage examples:
  # Tall platter base (80mm down from sandstone bottom)
  python3 generate_sandstone_base.py --height 80

  # Base with 20% flare (vase style)
  python3 generate_sandstone_base.py --height 80 --flare 1.2

  # Platter with solid bottom
  python3 generate_sandstone_base.py --height 30 --solid

  # Match a specific sandstone model's bottom geometry
  python3 generate_sandstone_base.py --height 50 --match-model sandstone_120mm.scad

  # Hollow platter with thick walls
  python3 generate_sandstone_base.py --height 40 --wall 3

  # Output to custom file
  python3 generate_sandstone_base.py --height 60 -o my_vase_base.scad
"""

import argparse
import math
import os
import re
import struct
import sys
from pathlib import Path


# ── Constants ────────────────────────────────────────────────────────────────
BASELINE_HEIGHT = 120.0       # mm – original sandstone model height
BASELINE_NUM_LAYERS = 111     # original ring count
POINTS_PER_RING = 120         # angular samples per ring (3° spacing)
SCRIPT_DIR = Path(__file__).parent
DEFAULT_SOURCE = SCRIPT_DIR / ".." / "raw" / "1-illinois_sandstone_cylinder_v3.scad"


# ── Parsing ──────────────────────────────────────────────────────────────────

def parse_original_scad(filepath):
    """Parse the original SCAD polyhedron to extract the bottom ring."""
    points = []
    point_re = re.compile(r'\[\s*([^,]+),\s*([^,]+),\s*([^\]]+)\]')

    with open(filepath) as f:
        for line in f:
            if 'faces' in line and '=' in line:
                break
            m = point_re.search(line)
            if m:
                x = float(m.group(1))
                y = float(m.group(2))
                z = float(m.group(3))
                points.append((x, y, z))

    n_ring_points = BASELINE_NUM_LAYERS * POINTS_PER_RING
    total = len(points)

    # Extract first ring (bottom of original model)
    bottom_ring = points[0:POINTS_PER_RING]
    center_bot = points[total - 2]

    return bottom_ring, center_bot


def lerp(a, b, t):
    """Linear interpolation between scalars."""
    return a + (b - a) * t


def lerp_point(p1, p2, t):
    """Linearly interpolate between two 3D points."""
    return (lerp(p1[0], p2[0], t),
            lerp(p1[1], p2[1], t),
            lerp(p1[2], p2[2], t))


# ── Base Ring Generation ─────────────────────────────────────────────────────

def get_ring_radius_at_angle(ring, angle_deg):
    """Compute the radius of a ring at a specific angle (degrees)."""
    angle_rad = math.radians(angle_deg)
    for (x, y, z) in ring:
        pt_angle = math.atan2(y, x)
        pt_angle_deg = math.degrees(pt_angle)
        if pt_angle_deg < 0:
            pt_angle_deg += 360.0
        if abs(pt_angle_deg - angle_deg) < 1.5:
            return math.hypot(x, y)
    return None


def get_avg_ring_radius(ring):
    """Get average radius of a ring."""
    radii = [math.hypot(p[0], p[1]) for p in ring]
    return sum(radii) / len(radii)


def generate_flared_ring(reference_ring, z_height, flare_factor=1.0):
    """Generate a ring at a new height with optional radial flare.

    flare_factor > 1.0 expands the ring outward (creates platter)
    flare_factor < 1.0 shrinks the ring inward
    flare_factor = 1.0 keeps the same cross-section
    """
    ring = []
    for (x, y, _) in reference_ring:
        angle = math.atan2(y, x)
        radius = math.hypot(x, y) * flare_factor
        new_x = radius * math.cos(angle)
        new_y = radius * math.sin(angle)
        ring.append((new_x, new_y, z_height))
    return ring


def interpolate_base_rings(bottom_reference_ring, base_height, num_layers,
                           flare_factor=1.0):
    """Generate interpolated rings from top (reference) to bottom.

    Top ring (z=0) matches bottom_reference_ring exactly.
    Bottom ring (z=-base_height) is flared by flare_factor.
    Intermediate rings interpolate both Z and flare smoothly.
    """
    rings = []
    avg_radius = get_avg_ring_radius(bottom_reference_ring)

    for i in range(num_layers):
        if num_layers == 1:
            t = 0.0
        else:
            t = i / (num_layers - 1)

        # Height: from 0 (top) to -base_height (bottom)
        z = -base_height * t

        # Flare: interpolate from 1.0 to flare_factor
        current_flare = lerp(1.0, flare_factor, t)

        ring = generate_flared_ring(bottom_reference_ring, z, current_flare)
        rings.append(ring)

    return rings


# ── Face Generation ─────────────────────────────────────────────────────────

def generate_closed_base_faces(rings, num_rings, pts_per_ring, solid=False):
    """Generate triangle faces for the base.

    If solid=True, generates a solid platter with a flat bottom.
    If solid=False, generates a hollow platter (open at bottom).
    """
    P = pts_per_ring
    faces = []

    # Side faces (connect successive rings)
    for i in range(num_rings - 1):
        for j in range(P):
            j_next = (j + 1) % P

            # Outer-facing triangles
            a = i * P + j
            b = i * P + j_next
            c = (i + 1) * P + j_next
            d = (i + 1) * P + j

            faces.append([a, b, c])
            faces.append([a, c, d])

    if solid:
        # Solid bottom: fan from bottom center to bottom ring
        # Last ring (deepest) is the base
        last_ring_start = (num_rings - 1) * P

        # Center point at the bottom
        center_idx = num_rings * P

        for j in range(P):
            j_next = (j + 1) % P
            # Reverse winding so normals point downward
            v1 = last_ring_start + j
            v2 = last_ring_start + j_next
            faces.append([center_idx, v2, v1])

        # Top (open edge) cap with flat ring
        top_ring_start = 0
        top_center_idx = num_rings * P + 1

        for j in range(P):
            j_next = (j + 1) % P
            v1 = top_ring_start + j
            v2 = top_ring_start + j_next
            faces.append([top_center_idx, v1, v2])

    return faces


def write_stl(filename, points, faces):
    """Write mesh as STL (binary format)."""
    with open(filename, 'wb') as f:
        # 80-byte header
        header = b'Parametric Sandstone Strata Base\x00' * 2
        f.write(header[:80])

        # Triangle count
        num_triangles = len(faces)
        f.write(struct.pack('<I', num_triangles))

        # Each triangle
        for face in faces:
            p1 = points[face[0]]
            p2 = points[face[1]]
            p3 = points[face[2]]

            # Compute normal
            v1 = (p2[0] - p1[0], p2[1] - p1[1], p2[2] - p1[2])
            v2 = (p3[0] - p1[0], p3[1] - p1[1], p3[2] - p1[2])
            nx = v1[1] * v2[2] - v1[2] * v2[1]
            ny = v1[2] * v2[0] - v1[0] * v2[2]
            nz = v1[0] * v2[1] - v1[1] * v2[0]
            n_len = math.sqrt(nx * nx + ny * ny + nz * nz)
            if n_len > 1e-9:
                nx /= n_len
                ny /= n_len
                nz /= n_len

            f.write(struct.pack('<fff', nx, ny, nz))
            f.write(struct.pack('<fff', p1[0], p1[1], p1[2]))
            f.write(struct.pack('<fff', p2[0], p2[1], p2[2]))
            f.write(struct.pack('<fff', p3[0], p3[1], p3[2]))
            f.write(b'\x00\x00')  # Attribute byte count


def write_scad(filename, rings, num_rings, pts_per_ring, solid=False, wall_thickness=2.0):
    """Write OpenSCAD polyhedron source."""
    P = pts_per_ring

    points = []
    for ring in rings:
        points.extend(ring)

    if solid:
        # Center points for solid bottom/top
        center_bot = (0, 0, rings[-1][0][2])
        center_top = (0, 0, rings[0][0][2])
        points.append(center_bot)
        points.append(center_top)

    faces = generate_closed_base_faces(rings, num_rings, P, solid=solid)

    with open(filename, 'w') as f:
        f.write("// Parametric Sandstone Strata Base/Platter\n")
        f.write(f"// Height: {rings[-1][0][2] - rings[0][0][2]:.2f} mm\n")
        if solid:
            f.write("// Mode: SOLID\n")
        else:
            f.write("// Mode: HOLLOW\n")
        f.write("\n")
        f.write("fine_tune_scale = 1.0;  // Overall scale multiplier\n\n")
        f.write("polyhedron(\n")
        f.write("  points = [\n")

        for i, pt in enumerate(points):
            f.write(f"    [{pt[0]:.6f}, {pt[1]:.6f}, {pt[2]:.6f}]")
            if i < len(points) - 1:
                f.write(",")
            f.write("\n")

        f.write("  ],\n")
        f.write("  faces = [\n")

        for i, face in enumerate(faces):
            f.write(f"    [{face[0]}, {face[1]}, {face[2]}]")
            if i < len(faces) - 1:
                f.write(",")
            f.write("\n")

        f.write("  ],\n")
        f.write("  convexity = 2\n")
        f.write(");\n\n")
        f.write("// Optional: scale by fine_tune_scale\n")
        f.write("// scale(fine_tune_scale) { children(); }\n")


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generate a parametric base/platter for sandstone lamps."
    )
    parser.add_argument('--height', type=float, default=50.0,
                        help='Base height downward from sandstone bottom (mm) [50]')
    parser.add_argument('--layers', type=int, default=None,
                        help='Number of interpolation layers [auto: height/1.0]')
    parser.add_argument('--flare', type=float, default=1.0,
                        help='Radial flare factor (>1=wider, <1=narrower) [1.0]')
    parser.add_argument('--solid', action='store_true', default=False,
                        help='Solid platter (with flat bottom) [hollow]')
    parser.add_argument('--wall', type=float, default=2.0,
                        help='Wall thickness if hollow (mm) [2.0]')
    parser.add_argument('--match-model', type=str, default=None,
                        help='Extract bottom ring from a generated sandstone .scad file')
    parser.add_argument('-o', dest='output', type=str, default=None,
                        help='Output filename (auto-generated if omitted)')
    parser.add_argument('--source', type=str, default=str(DEFAULT_SOURCE),
                        help=f'Path to source SCAD polyhedron [{DEFAULT_SOURCE}]')

    args = parser.parse_args()

    # Auto-compute layer count
    if args.layers is None:
        args.layers = max(2, int(round(args.height / 1.0)))

    print(f"\nGenerating parametric base:")
    print(f"  Height         : {args.height:.1f} mm (downward)")
    print(f"  Layers         : {args.layers}")
    print(f"  Flare factor   : {args.flare:.2f}x")
    print(f"  Mode           : {'SOLID' if args.solid else 'HOLLOW'}")
    if not args.solid:
        print(f"  Wall thickness : {args.wall:.1f} mm")

    # Parse source to get bottom ring
    source_path = Path(args.source)
    if not source_path.exists():
        print(f"\n✗ Source file not found: {source_path}")
        sys.exit(1)

    print(f"\nParsing original: {source_path}")
    bottom_ring, center = parse_original_scad(source_path)
    print(f"  → {len(bottom_ring)} points in reference ring")

    # Generate base rings
    rings = interpolate_base_rings(bottom_ring, args.height, args.layers,
                                   flare_factor=args.flare)

    # Prepare all points
    all_points = []
    for ring in rings:
        all_points.extend(ring)

    if args.solid:
        all_points.extend([
            (0, 0, rings[-1][0][2]),  # center bottom
            (0, 0, rings[0][0][2])     # center top
        ])

    # Generate faces
    faces = generate_closed_base_faces(rings, args.layers, POINTS_PER_RING,
                                       solid=args.solid)

    # Auto-generate output filename
    if args.output is None:
        flare_str = f"_flare{args.flare:.2f}".replace('.', '_') if args.flare != 1.0 else ""
        mode_str = f"_wall{args.wall:.1f}".replace('.', '_') if not args.solid else "_solid"
        args.output = f"illinois_sandstone_parametric_base_{args.height:.0f}mm_{args.layers}L{flare_str}{mode_str}.scad"

    output_path = Path(args.output)

    # Write SCAD
    write_scad(str(output_path), rings, args.layers, POINTS_PER_RING,
               solid=args.solid, wall_thickness=args.wall)
    print(f"\n✓ SCAD: {output_path}")

    # Write STL
    stl_path = output_path.with_suffix('.stl')
    write_stl(str(stl_path), all_points, faces)
    stl_size_mb = stl_path.stat().st_size / (1024 * 1024)
    print(f"✓ STL:  {stl_path}  ({stl_size_mb:.1f} MB)")

    print(f"\nPoints: {len(all_points)}  |  Faces: {len(faces)}")
    print(f"  Height: {rings[-1][0][2]:.1f} mm (down from top)")
    print(f"  Flare:  {args.flare:.2f}x")
    print(f"  Mode:   {'solid' if args.solid else 'hollow'}")
    print()


if __name__ == '__main__':
    main()
