#!/usr/bin/env python3
"""
Parametric Sandstone Strata Base/Platter Generator
====================================================
Creates a complementary base or platter piece that sits seamlessly below
a sandstone strata lamp generated by generate_sandstone.py.

The base uses the same reference geometry (bottom ring of the sandstone model)
and extends downward by a specified distance, optionally flaring outward to
create a wider platter, vase, or planter shape.

The top edge of this piece is contiguous with the bottom of the sandstone
lamp — same ring of vertices, same organic profile.

Usage examples:
  # Simple 40mm solid platter base
  python3 generate_sandstone_base.py --height 40

  # Hollow base (2mm wall default)
  python3 generate_sandstone_base.py --height 40 --wall 2

  # Base with outward flare (vase/planter style)
  python3 generate_sandstone_base.py --height 80 --flare 1.3

  # Tall hollow vase base with thick walls
  python3 generate_sandstone_base.py --height 60 --wall 3

  # Drain hole for planter use
  python3 generate_sandstone_base.py --height 40 --drain 10

  # Output to custom file
  python3 generate_sandstone_base.py --height 60 -o my_vase_base.scad
"""

import argparse
import math
import os
import re
import struct
import sys
from pathlib import Path


# ── Constants ────────────────────────────────────────────────────────────────
BASELINE_HEIGHT = 120.0
BASELINE_NUM_LAYERS = 111
POINTS_PER_RING = 120
SCRIPT_DIR = Path(__file__).parent
DEFAULT_SOURCE = SCRIPT_DIR / ".." / "raw" / "1-illinois_sandstone_cylinder_v3.scad"


# ── Parsing ──────────────────────────────────────────────────────────────────

def parse_original_scad(filepath):
    """Parse the original SCAD polyhedron to extract the bottom ring."""
    points = []
    point_re = re.compile(r'\[\s*([^,]+),\s*([^,]+),\s*([^\]]+)\]')

    with open(filepath) as f:
        for line in f:
            if 'faces' in line and '=' in line:
                break
            m = point_re.search(line)
            if m:
                x = float(m.group(1))
                y = float(m.group(2))
                z = float(m.group(3))
                points.append((x, y, z))

    # First ring = bottom of original model (ring 0)
    bottom_ring = points[0:POINTS_PER_RING]
    return bottom_ring


# ── Geometry Helpers ─────────────────────────────────────────────────────────

def lerp(a, b, t):
    return a + (b - a) * t


def get_avg_ring_radius(ring):
    return sum(math.hypot(p[0], p[1]) for p in ring) / len(ring)


def offset_ring_inward(ring, wall_thickness):
    """Offset a ring inward by wall_thickness in XY, preserving Z."""
    cx = sum(p[0] for p in ring) / len(ring)
    cy = sum(p[1] for p in ring) / len(ring)
    inner = []
    for (x, y, z) in ring:
        dx, dy = x - cx, y - cy
        dist = math.hypot(dx, dy)
        if dist < 1e-9:
            inner.append((x, y, z))
        else:
            ux, uy = dx / dist, dy / dist
            inner.append((x - ux * wall_thickness,
                          y - uy * wall_thickness, z))
    return inner


def generate_flared_ring(reference_ring, z_height, flare_factor=1.0):
    """Generate a ring at a new Z with optional radial flare."""
    ring = []
    for (x, y, _) in reference_ring:
        angle = math.atan2(y, x)
        radius = math.hypot(x, y) * flare_factor
        ring.append((radius * math.cos(angle),
                      radius * math.sin(angle),
                      z_height))
    return ring


def generate_hole_ring(reference_ring, hole_radius, z):
    """Generate a hole ring matching angular positions of reference_ring."""
    ring = []
    for (x, y, _) in reference_ring:
        angle = math.atan2(y, x)
        ring.append((hole_radius * math.cos(angle),
                      hole_radius * math.sin(angle), z))
    return ring


# ── Ring Generation ──────────────────────────────────────────────────────────

def generate_base_rings(bottom_reference_ring, base_height, num_layers,
                        flare_factor=1.0):
    """Generate rings from top (z=0, matches lamp bottom) down to z=-base_height.

    Top ring matches the reference exactly.
    Bottom ring is optionally flared.
    Intermediate rings interpolate Z and flare smoothly.
    """
    rings = []
    for i in range(num_layers):
        t = i / max(1, num_layers - 1)
        z = -base_height * t
        current_flare = lerp(1.0, flare_factor, t)
        ring = generate_flared_ring(bottom_reference_ring, z, current_flare)
        rings.append(ring)
    return rings


# ── Mesh Building ────────────────────────────────────────────────────────────

def build_solid_mesh(rings, base_height):
    """Build a completely solid (filled) base mesh.

    Structure:
      - Side wall (organic rings)
      - Flat top cap (fan from center at z=0)
      - Flat bottom cap (fan from center at z=-base_height)
    """
    P = POINTS_PER_RING
    num_rings = len(rings)

    all_points = []
    for ring in rings:
        all_points.extend(ring)

    # Center points for top and bottom caps
    center_top_idx = len(all_points)
    all_points.append((0.0, 0.0, 0.0))

    center_bot_idx = len(all_points)
    all_points.append((0.0, 0.0, -base_height))

    faces = []

    # Side faces (outward normals)
    for i in range(num_rings - 1):
        for j in range(P):
            j_next = (j + 1) % P
            a = i * P + j
            b = i * P + j_next
            c = (i + 1) * P + j_next
            d = (i + 1) * P + j
            faces.append([a, b, c])
            faces.append([a, c, d])

    # Top cap (z=0): normals pointing up (CCW from above)
    for j in range(P):
        j_next = (j + 1) % P
        faces.append([center_top_idx, j, j_next])

    # Bottom cap (z=-base_height): normals pointing down (CW from above)
    bot_start = (num_rings - 1) * P
    for j in range(P):
        j_next = (j + 1) % P
        faces.append([center_bot_idx, bot_start + j_next, bot_start + j])

    return all_points, faces


def build_hollow_mesh(rings, base_height, wall_thickness,
                      drain_diameter=0.0):
    """Build a hollow base with inner and outer walls — proper closed manifold.

    Structure:
      - Outer shell: all rings (top to bottom)
      - Inner shell: all rings offset inward by wall_thickness
      - Top annulus: connects outer ring 0 to inner ring 0 (z=0)
      - Bottom closure: solid floor or drain hole annulus
    """
    P = POINTS_PER_RING
    num_rings = len(rings)

    # Outer rings
    all_points = []
    for ring in rings:
        all_points.extend(ring)
    outer_count = len(all_points)

    # Inner rings (offset inward)
    inner_rings = [offset_ring_inward(ring, wall_thickness) for ring in rings]
    for ring in inner_rings:
        all_points.extend(ring)

    faces = []

    # ── Outer side faces (outward normals) ───────────────────────────────
    for i in range(num_rings - 1):
        for j in range(P):
            j_next = (j + 1) % P
            a = i * P + j
            b = i * P + j_next
            c = (i + 1) * P + j_next
            d = (i + 1) * P + j
            faces.append([a, b, c])
            faces.append([a, c, d])

    # ── Inner side faces (inward normals = reversed winding) ─────────────
    for i in range(num_rings - 1):
        for j in range(P):
            j_next = (j + 1) % P
            a = outer_count + i * P + j
            b = outer_count + i * P + j_next
            c = outer_count + (i + 1) * P + j_next
            d = outer_count + (i + 1) * P + j
            faces.append([a, c, b])
            faces.append([a, d, c])

    # ── Top annulus (z=0): outer ring 0 → inner ring 0, normals up ───────
    top_outer_start = 0
    top_inner_start = outer_count
    for j in range(P):
        j_next = (j + 1) % P
        o_a = top_outer_start + j
        o_b = top_outer_start + j_next
        i_a = top_inner_start + j
        i_b = top_inner_start + j_next
        faces.append([o_a, o_b, i_b])
        faces.append([o_a, i_b, i_a])

    # ── Bottom closure ───────────────────────────────────────────────────
    bot_outer_start = (num_rings - 1) * P
    bot_inner_start = outer_count + (num_rings - 1) * P
    hole_radius = drain_diameter / 2.0 if drain_diameter > 0 else 0.0

    if hole_radius > 0:
        # Bottom outer annulus: outer last ring → hole ring at z=-base_height
        hole_outer_ring = generate_hole_ring(rings[-1], hole_radius,
                                             -base_height)
        hole_outer_start = len(all_points)
        all_points.extend(hole_outer_ring)

        # Outer bottom annulus (normals down)
        for j in range(P):
            j_next = (j + 1) % P
            faces.append([bot_outer_start + j,
                          hole_outer_start + j_next,
                          hole_outer_start + j])
            faces.append([bot_outer_start + j,
                          bot_outer_start + j_next,
                          hole_outer_start + j_next])

        # Inner bottom annulus: inner last ring → hole ring at z=-base_height
        hole_inner_ring = generate_hole_ring(inner_rings[-1], hole_radius,
                                             -base_height)
        hole_inner_start = len(all_points)
        all_points.extend(hole_inner_ring)

        # Inner bottom annulus (normals up = reversed)
        for j in range(P):
            j_next = (j + 1) % P
            faces.append([bot_inner_start + j,
                          hole_inner_start + j,
                          hole_inner_start + j_next])
            faces.append([bot_inner_start + j,
                          hole_inner_start + j_next,
                          bot_inner_start + j_next])

        # Hole tube: connect outer hole ring to inner hole ring (inward normals)
        for j in range(P):
            j_next = (j + 1) % P
            a = hole_outer_start + j
            b = hole_outer_start + j_next
            c = hole_inner_start + j_next
            d = hole_inner_start + j
            faces.append([a, d, c])
            faces.append([a, c, b])
    else:
        # Solid bottom floor: two discs (outer down-facing, inner up-facing)
        # Outer bottom disc (normals down)
        center_outer_idx = len(all_points)
        all_points.append((0.0, 0.0, -base_height))

        for j in range(P):
            j_next = (j + 1) % P
            faces.append([center_outer_idx,
                          bot_outer_start + j_next,
                          bot_outer_start + j])

        # Inner bottom disc (normals up)
        center_inner_idx = len(all_points)
        all_points.append((0.0, 0.0, -base_height))

        for j in range(P):
            j_next = (j + 1) % P
            faces.append([center_inner_idx,
                          bot_inner_start + j,
                          bot_inner_start + j_next])

    return all_points, faces


# ── Output ───────────────────────────────────────────────────────────────────

def cross(u, v):
    return (u[1]*v[2] - u[2]*v[1],
            u[2]*v[0] - u[0]*v[2],
            u[0]*v[1] - u[1]*v[0])


def normalize(v):
    length = math.sqrt(v[0]**2 + v[1]**2 + v[2]**2)
    if length < 1e-12:
        return (0.0, 0.0, 0.0)
    return (v[0]/length, v[1]/length, v[2]/length)


def write_stl(filepath, all_points, faces):
    """Write binary STL."""
    with open(filepath, 'wb') as f:
        header = b'Binary STL - Parametric Sandstone Base'
        f.write(header.ljust(80, b'\0'))
        f.write(struct.pack('<I', len(faces)))

        for face in faces:
            p0 = all_points[face[0]]
            p1 = all_points[face[1]]
            p2 = all_points[face[2]]
            u = (p1[0]-p0[0], p1[1]-p0[1], p1[2]-p0[2])
            v = (p2[0]-p0[0], p2[1]-p0[1], p2[2]-p0[2])
            n = normalize(cross(u, v))
            f.write(struct.pack('<3f', *n))
            f.write(struct.pack('<3f', *p0))
            f.write(struct.pack('<3f', *p1))
            f.write(struct.pack('<3f', *p2))
            f.write(struct.pack('<H', 0))


def write_scad(filepath, all_points, faces, base_height, num_layers,
               wall_thickness, flare_factor, drain_diameter, is_hollow):
    """Write OpenSCAD polyhedron source."""
    with open(filepath, 'w') as f:
        f.write(f"""\
// ═══════════════════════════════════════════════════════════════════════════
// Parametric Illinois Sandstone Strata Base / Platter
// ═══════════════════════════════════════════════════════════════════════════
//
// Generated by generate_sandstone_base.py
//
// This piece connects seamlessly to the bottom of a sandstone lamp
// generated by generate_sandstone.py — the top edge (z=0) matches
// the lamp's bottom ring exactly.
//
// Parameters:
//   base_height    = {base_height:.2f} mm (extends downward)
//   num_layers     = {num_layers}
//   flare          = {flare_factor:.2f}x
""")
        if is_hollow:
            f.write(f"//   wall_thickness = {wall_thickness:.2f} mm\n")
            if drain_diameter > 0:
                f.write(f"//   drain_hole     = ⌀{drain_diameter:.2f} mm\n")
            f.write(f"//   mode           = HOLLOW\n")
        else:
            f.write(f"//   mode           = SOLID\n")

        f.write(f"""//
// ── OpenSCAD Fine-Tuning ────────────────────────────────────────────────

/* [Scale] */
fine_tune_scale = 1.0;  // [0.25:0.01:4.0]

// ── Render ──────────────────────────────────────────────────────────────

scale([1, 1, fine_tune_scale])
""")
        f.write("polyhedron(\n")
        f.write("  points = [\n")

        for idx, (x, y, z) in enumerate(all_points):
            comma = "," if idx < len(all_points) - 1 else ""
            f.write(f"        [{x:.5f}, {y:.5f}, {z:.5f}]{comma}\n")

        f.write("      ],\n")
        f.write("      faces = [\n")

        for idx, face in enumerate(faces):
            comma = "," if idx < len(faces) - 1 else ""
            f.write(f"        [{face[0]}, {face[1]}, {face[2]}]{comma}\n")

        f.write("      ],\n")
        f.write("      convexity = 10\n")
        f.write("    );\n")


# ── CLI ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generate a parametric base/platter for sandstone lamps.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    parser.add_argument('--height', type=float, default=40.0,
                        help='Base height downward from lamp bottom (mm) [40]')
    parser.add_argument('--layers', type=int, default=None,
                        help='Number of interpolation layers [auto: ~1mm/layer]')
    parser.add_argument('--flare', type=float, default=1.0,
                        help='Radial flare factor at bottom (>1=wider) [1.0]')
    parser.add_argument('--wall', type=float, default=None,
                        help='Wall thickness (mm) — makes it hollow [solid if omitted]')
    parser.add_argument('--drain', type=float, nargs='?', const=10.0, default=None,
                        help='Drain hole diameter at bottom (mm) — for planter use. '
                             '--drain alone = 10mm, or --drain 15 [no hole]')
    parser.add_argument('--source', type=str, default=str(DEFAULT_SOURCE),
                        help=f'Path to source SCAD polyhedron')
    parser.add_argument('-o', dest='output', type=str, default=None,
                        help='Output filename (auto-generated if omitted)')

    args = parser.parse_args()

    # Auto-compute layers
    if args.layers is None:
        args.layers = max(2, int(round(args.height / 1.0)))

    # Resolve hollow vs solid
    wall_thickness = args.wall if args.wall is not None else 2.0
    is_hollow = args.wall is not None or args.drain is not None
    drain_diameter = args.drain if args.drain is not None else 0.0

    if drain_diameter > 0 and not is_hollow:
        is_hollow = True

    # Parse source
    source_path = Path(args.source).resolve()
    if not source_path.exists():
        print(f"\n✗ Source file not found: {source_path}", file=sys.stderr)
        sys.exit(1)

    print(f"\nParsing original: {source_path}")
    bottom_ring = parse_original_scad(source_path)
    avg_r = get_avg_ring_radius(bottom_ring)
    print(f"  → {len(bottom_ring)} points in reference ring")
    print(f"  → Average radius: {avg_r:.1f} mm")

    # Generate rings
    rings = generate_base_rings(bottom_ring, args.height, args.layers,
                                flare_factor=args.flare)

    print(f"\nGenerating parametric base:")
    print(f"  Height       : {args.height:.1f} mm (downward from z=0)")
    print(f"  Layers       : {args.layers}")
    print(f"  Flare factor : {args.flare:.2f}x")
    if is_hollow:
        print(f"  Mode         : HOLLOW (wall = {wall_thickness:.1f} mm)")
        if drain_diameter > 0:
            print(f"  Drain hole   : ⌀{drain_diameter:.1f} mm")
    else:
        print(f"  Mode         : SOLID")

    # Build mesh
    if is_hollow:
        all_points, faces = build_hollow_mesh(
            rings, args.height, wall_thickness, drain_diameter)
    else:
        all_points, faces = build_solid_mesh(rings, args.height)

    # Output filenames
    if args.output:
        base_output = args.output
        if base_output.lower().endswith(('.scad', '.stl')):
            base_output = base_output.rsplit('.', 1)[0]
    else:
        flare_str = f"_flare{args.flare:.0f}p{int((args.flare%1)*100):02d}" if args.flare != 1.0 else ""
        if is_hollow:
            mode_str = f"_wall{wall_thickness:.0f}"
            if drain_diameter > 0:
                mode_str += f"_drain{drain_diameter:.0f}"
        else:
            mode_str = "_solid"
        base_output = str(SCRIPT_DIR /
            f"illinois_sandstone_parametric_base_{args.height:.0f}mm"
            f"_{args.layers}L{flare_str}{mode_str}")

    scad_path = base_output + '.scad'
    stl_path = base_output + '.stl'

    # Write
    write_scad(scad_path, all_points, faces, args.height, args.layers,
               wall_thickness, args.flare, drain_diameter, is_hollow)
    write_stl(stl_path, all_points, faces)

    stl_mb = os.path.getsize(stl_path) / (1024 * 1024)

    print(f"\n✓ SCAD: {scad_path}")
    print(f"✓ STL:  {stl_path}  ({stl_mb:.1f} MB)")
    print(f"\n  Points: {len(all_points):,}  |  Faces: {len(faces):,}")
    print(f"  Top edge at z=0 matches sandstone lamp bottom exactly.")
    print()


if __name__ == '__main__':
    main()
